export type PrivacyReferenceService = {
  name: string;
  category: "P2P" | "DEX" | "Wallet" | "Privacy tools";
  description: string;
  posture: string;
  custody: string;
  bestFor: string;
  caution: string;
  tags: string[];
  href: string;
  status?: string;
};

const sourceUrl = "https://kycnot.me/";

const entries: Array<Omit<PrivacyReferenceService, "href"> & { href?: string }> = [
  {
    name: "eigenwallet",
    category: "DEX",
    description: "A Bitcoin-to-Monero atomic-swap project listed as a decentralized, open-source exchange option.",
    posture: "Atomic-swap reference entry",
    custody: "Protocol-dependent",
    bestFor: "Advanced Bitcoin and Monero research",
    caution: "Verify the current project status, software integrity, liquidity, supported networks, and legal context before use.",
    tags: ["Bitcoin", "Monero", "Atomic swaps"],
  },
  {
    name: "IVPN",
    category: "Privacy tools",
    description: "A privacy-focused VPN service listed for anonymous-payment and no-KYC research.",
    posture: "Network privacy utility",
    custody: "Not a financial service",
    bestFor: "Reducing exposure on untrusted networks",
    caution: "A VPN does not anonymize blockchain activity, override platform rules, or remove local legal obligations.",
    tags: ["VPN", "Network", "Privacy"],
  },
  {
    name: "PegasusSwap",
    category: "DEX",
    description: "A swap service listed as a no-registration and no-JavaScript-needed exchange option.",
    posture: "Account-light swap reference entry",
    custody: "Route-dependent",
    bestFor: "Comparing exchange workflows",
    caution: "Confirm the live domain, underlying liquidity provider, refund policy, limits, and transaction monitoring before sending funds.",
    tags: ["Exchange", "Swap", "No registration"],
  },
  {
    name: "MyNymBox",
    category: "Privacy tools",
    description: "A hosting and domain reference entry listed for privacy-oriented infrastructure paid with cryptocurrency.",
    posture: "Privacy-hosting reference entry",
    custody: "Service-account dependent",
    bestFor: "Comparing privacy-oriented hosting providers",
    caution: "Verify current ownership, service terms, abuse policy, uptime, retention, payment handling, and jurisdiction.",
    tags: ["Hosting", "VPS", "Domains"],
  },
  {
    name: "XmrBazaar",
    category: "P2P",
    description: "A peer-to-peer Monero marketplace reference entry for trading products or services.",
    posture: "Peer-to-peer marketplace",
    custody: "Counterparty and escrow dependent",
    bestFor: "Researching Monero marketplace models",
    caution: "Review seller reputation, escrow, disputes, delivery, sanctions, and local rules; do not treat a directory listing as endorsement.",
    tags: ["Monero", "Marketplace", "P2P"],
  },
  {
    name: "Xeovo",
    category: "Privacy tools",
    description: "A Finland-based VPN and proxy reference entry listed for privacy-focused network access.",
    posture: "Network privacy utility",
    custody: "Not a financial service",
    bestFor: "Comparing VPN and proxy options",
    caution: "Check current privacy policy, infrastructure, support, payment methods, and whether the service fits your threat model.",
    tags: ["VPN", "Proxy", "Network"],
  },
  {
    name: "Infinity Exchanger",
    category: "DEX",
    description: "A Tor-oriented exchange reference entry listed without a conventional user account.",
    posture: "Account-light exchange reference entry",
    custody: "Route-dependent",
    bestFor: "Researching privacy-oriented exchange interfaces",
    caution: "Verify the official domain, liquidity, supported assets, refund handling, operator identity, and current operational status.",
    tags: ["Exchange", "Tor", "No account"],
  },
  {
    name: "BasicSwap",
    category: "DEX",
    description: "A cross-chain peer-to-peer trading project listed for atomic swaps and scriptless transactions.",
    posture: "Open-source P2P protocol reference entry",
    custody: "Non-custodial protocol model",
    bestFor: "Advanced cross-chain swap research",
    caution: "Check software releases, liquidity, wallet compatibility, chain support, and operational risks before using funds.",
    tags: ["P2P", "Atomic swaps", "Open source"],
  },
  {
    name: "NYM",
    category: "Privacy tools",
    description: "A decentralized mixnet and dVPN reference entry designed to reduce metadata exposure.",
    posture: "Metadata privacy network",
    custody: "Not a financial service",
    bestFor: "Studying network-level privacy tools",
    caution: "Understand the threat model, performance, node assumptions, token economics, and whether the application protects the activity you care about.",
    tags: ["Mixnet", "VPN", "Metadata"],
  },
  {
    name: "Obscura",
    category: "Privacy tools",
    description: "A privacy-focused VPN reference entry listed with anonymous signup and Bitcoin Lightning payment options.",
    posture: "Network privacy utility",
    custody: "Not a financial service",
    bestFor: "Comparing privacy-oriented VPN services",
    caution: "Verify current operator, server routing, logging policy, payment flow, and client security before relying on it.",
    tags: ["VPN", "Lightning", "Privacy"],
  },
  {
    name: "RetoSwap",
    category: "P2P",
    description: "A private, non-custodial P2P exchange reference entry built around Haveno, Tor, and Monero.",
    posture: "P2P exchange reference entry",
    custody: "Non-custodial trade flow claimed by project; verify implementation",
    bestFor: "Researching private P2P exchange models",
    caution: "Verify the current software, escrow design, liquidity, dispute handling, and jurisdiction before trading.",
    tags: ["P2P", "Monero", "Haveno"],
  },
  {
    name: "cryptostorm",
    category: "Privacy tools",
    description: "A VPN reference entry listed for no-log claims, anonymous payments, and Tor or I2P access.",
    posture: "Network privacy utility",
    custody: "Not a financial service",
    bestFor: "Comparing VPN payment and network models",
    caution: "Read the current privacy policy, service terms, technical documentation, and independent security information.",
    tags: ["VPN", "Tor", "I2P"],
  },
  {
    name: "Intercambio",
    category: "Privacy tools",
    description: "An exchange-aggregator reference entry listed for comparing multi-hop swap routes.",
    posture: "Privacy-oriented aggregator",
    custody: "Underlying-provider dependent",
    bestFor: "Comparing multi-hop swap options",
    caution: "The underlying exchange controls custody, KYC, pricing, limits, refunds, and data handling.",
    tags: ["Aggregator", "Exchange", "Multi-hop"],
  },
  {
    name: "servers.guru",
    category: "Privacy tools",
    description: "A privacy-hosting reference entry listed for VPS and infrastructure services.",
    posture: "Privacy-hosting reference entry",
    custody: "Service-account dependent",
    bestFor: "Comparing crypto-payable infrastructure",
    caution: "Verify service limits, data retention, abuse response, jurisdiction, backups, and current availability.",
    tags: ["VPS", "Hosting", "Infrastructure"],
  },
  {
    name: "Proton Mail",
    category: "Privacy tools",
    description: "An encrypted email reference entry included for privacy-oriented account and communication research.",
    posture: "Encrypted communication utility",
    custody: "Not a financial service",
    bestFor: "Separating communication from financial accounts",
    caution: "Email privacy is not the same as financial anonymity; review recovery, metadata, jurisdiction, and account policies.",
    tags: ["Email", "Privacy", "Security"],
  },
  {
    name: "OrangeFren",
    category: "Privacy tools",
    description: "An aggregator reference entry listed for comparing non-KYC exchange rates.",
    posture: "Exchange comparison layer",
    custody: "Underlying-provider dependent",
    bestFor: "Comparing exchange routes",
    caution: "Confirm the actual provider, rate, fees, refund policy, KYC triggers, and current operator before sending funds.",
    tags: ["Aggregator", "Exchange", "Rates"],
  },
  {
    name: "PrivateAlps",
    category: "Privacy tools",
    description: "An offshore cloud-services reference entry listed for privacy-oriented hosting research.",
    posture: "Privacy-hosting reference entry",
    custody: "Service-account dependent",
    bestFor: "Comparing offshore infrastructure options",
    caution: "Offshore location is not a security guarantee; verify ownership, legal jurisdiction, data policy, uptime, and support.",
    tags: ["Hosting", "Cloud", "Privacy"],
  },
  {
    name: "Safing SPN",
    category: "Privacy tools",
    description: "A network-privacy reference entry listed for app-specific identities and private routing.",
    posture: "Network privacy utility",
    custody: "Not a financial service",
    bestFor: "Segmenting network identities by application",
    caution: "Review technical design, node trust, performance, logging, and the limits of network-layer privacy.",
    tags: ["VPN", "Network", "Compartmentalisation"],
  },
  {
    name: "Silent.Link",
    category: "Privacy tools",
    description: "An eSIM and mobile-connectivity reference entry listed for private mobile access and phone numbers.",
    posture: "Connectivity privacy utility",
    custody: "Service-account dependent",
    bestFor: "Comparing private mobile connectivity options",
    caution: "Verify coverage, number retention, identity requirements, payment metadata, emergency-service limitations, and local telecom rules.",
    tags: ["eSIM", "Mobile", "Privacy"],
  },
  {
    name: "Peach Bitcoin",
    category: "P2P",
    description: "A mobile P2P Bitcoin marketplace reference entry listed for connecting buyers and sellers.",
    posture: "Peer-to-peer Bitcoin marketplace",
    custody: "Counterparty and escrow dependent",
    bestFor: "Researching mobile P2P Bitcoin trading",
    caution: "Verify the current app, escrow and dispute process, payment reversibility, seller risk, fees, and local rules.",
    tags: ["Bitcoin", "P2P", "Mobile"],
  },
  {
    name: "Crypton.sh",
    category: "Privacy tools",
    description: "An encrypted SMS and phone-number reference entry listed for private communications research.",
    posture: "Communication privacy utility",
    custody: "Service-account dependent",
    bestFor: "Comparing private messaging and number services",
    caution: "Check current coverage, number lifecycle, recovery, payment data, legal requirements, and service reliability.",
    tags: ["SMS", "eSIM", "Privacy"],
  },
];

export const privacyReferenceServices: PrivacyReferenceService[] = entries.map((entry) => ({
  ...entry,
  href: entry.href ?? sourceUrl,
  status: "Reference profile",
}));
