import { notFound } from "next/navigation";
import Link from "next/link";
import { guides } from "../../content";
import { ArticleShell, Figure, RelatedPages } from "../../MemeArticle";
import type { Metadata } from "next";
export function generateStaticParams() { return guides.map((g) => ({ slug: g.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const g = guides.find((x) => x.slug === slug); return g ? { title: g.title, description: g.description, alternates: { canonical: `https://www.cryptosbeginner.com/meme-coins/guides/${g.slug}` }, openGraph: { title: g.title, description: g.description, url: `https://www.cryptosbeginner.com/meme-coins/guides/${g.slug}`, type: "article" } } : {}; }
export default async function GuidePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const g = guides.find((x) => x.slug === slug); if (!g) notFound();
  if (slug === "token-verification") return <ArticleShell path={`/meme-coins/guides/${slug}`} kicker="Meme coins · Guide · 28 August 2026" title={g.title} description="The checks below are designed to answer the questions a chart cannot answer."><h2>TL;DR</h2><p>Verify the exact contract, inspect permissions and deployer history, review holders and wallet clusters, confirm liquidity and sellability, and authenticate the project’s social accounts. If one critical answer is missing, waiting is the safer decision.</p><h2>Contract identity</h2><p>Start from an official project account or another independently verified source. Compare the address character by character and beware copied tickers, lookalike domains, reused logos, and search-result impersonation.</p><Figure src={g.image} alt="GMGN Radar discovery surface showing token-finding controls and market candidates" caption="GMGN Radar discovery surface; discovery helps form a research queue but does not independently verify a contract." /><h2>Permissions and deployer history</h2><p>Where the chain and token standard expose them, review mint, freeze, blacklist, and other privileged permissions. Trace the deployer’s prior launches and look for repeated clusters or abandoned projects. A clean history is context, not proof of the next launch.</p><h2>Holders, clusters, liquidity and sellability</h2><p>Review top holders and bubble maps, then ask whether related wallets could distort the view. Confirm where liquidity sits and whether a sale of your intended size could move the market. Where appropriate, test sellability with a tiny amount before committing more.</p><h2>Social authenticity</h2><p>A large follower count, copied account, paid post, or caller screenshot is attention—not independent evidence. Use the <Link href="/public-wallets">public wallet explorer</Link>, <Link href="/crypto-screener">crypto screener</Link>, and <Link href="/dexes">DEX directory</Link> to supplement a terminal’s labels.</p><RelatedPages /></ArticleShell>;
  if (slug === "slippage-mev") return <ArticleShell path={`/meme-coins/guides/${slug}`} kicker="Meme coins · Guide · 28 August 2026" title={g.title} description="Execution controls manage how a transaction is submitted; they do not validate the token or guarantee the outcome."><h2>TL;DR</h2><p>Slippage is the maximum price deviation accepted. Priority fees and tips are additional ordering costs. MEV protection may reduce exposure to some transaction-ordering strategies but can change route, speed, and cost.</p><Figure src={g.image} alt="Axiom trading workspace showing chart and buy or sell execution controls" caption="Axiom trading workspace showing chart and execution controls; supplied screenshot, reviewed 28 August 2026." /><h2>What slippage means</h2><p>A narrow limit can cause a transaction to fail. A wide limit can authorize a materially worse fill. A higher number is permission to accept more deviation, not a safety margin.</p><h2>Priority fees, tips and MEV</h2><p>A priority fee or tip can increase ordering probability while adding cost. A protected route can change latency and routing. The Axiom and GMGN documentation describe different modes and settings, but neither removes contract, liquidity, or adverse-selection risk.</p><h2>A conservative first-use setup</h2><p>Use a dedicated low-balance wallet, verify the route and contract, start with an amount you can lose completely, set a slippage ceiling before the market moves, budget priority and tips separately, and record the invalidation point. Fear of missing a move is not a reason to widen execution permissions.</p><RelatedPages /></ArticleShell>;
  return <ArticleShell path={`/meme-coins/guides/${slug}`} kicker="Meme coins · Guide · 28 August 2026" title={g.title} description="Presets save repeated trade settings, but a badly understood preset can turn one mistake into a repeatable action."><h2>TL;DR</h2><p>Review amount, slippage, priority fee, tip, route, and exit fields before saving a preset. Never copy another trader’s configuration without understanding its trade-offs.</p><Figure src={g.image} alt="Axiom preset controls showing saved execution settings" caption="Axiom preset controls; a saved instruction set is not a safety system." /><h2>What a preset stores</h2><p>A platform may save order amount, slippage, priority fee, tip, MEV route, or exit instructions. Exact fields vary. Treat every field as an instruction that can affect cost or execution.</p><Figure src="/images/meme-coins/platforms/gmgn-presets.png" alt="GMGN presets screen showing saved execution settings" caption="GMGN saved preset controls; defaults can change and can repeat mistakes." /><h2>A five-field review</h2><div className="not-prose overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="border-b p-3">Field</th><th className="border-b p-3">Question before saving</th></tr></thead><tbody>{[["Amount","What is the maximum exposure on one order?"],["Slippage","What deviation is acceptable before failure?"],["Priority and tip","What extra cost is reasonable?"],["MEV route","Do you understand speed, privacy, and cost trade-offs?"],["Exit","What invalidates the thesis and what happens first?"]].map(([a,b]) => <tr key={a}><td className="border-b p-3 font-bold">{a}</td><td className="border-b p-3">{b}</td></tr>)}</tbody></table></div><RelatedPages /></ArticleShell>;
}
