export type WalletCategory = "hardware" | "mobile" | "extension" | "desktop";

export type Wallet = {
  slug: string;
  name: string;
  category: WalletCategory;
  fit: string;
  chains: string;
  security: string;
  watchFor: string;
  price: string;
  href: string;
  affiliate: boolean;
  image: string;
  domain: string;
  color: string;
  mark: string;
};

export const categoryLabels: Record<WalletCategory, string> = {
  hardware: "Hardware",
  mobile: "Mobile",
  extension: "Browser extension",
  desktop: "Desktop",
};

export const wallets: Wallet[] = [
  {
    slug: "ledger",
    name: "Ledger",
    category: "hardware",
    fit: "Long-term storage with a dedicated signing device",
    chains: "Bitcoin, Ethereum, Solana and many others via Ledger Live",
    security: "Keys stay on the device. Confirm each send on the screen.",
    watchFor: "Buy new and sealed. Never type a seed phrase into a popup.",
    price: "Paid device",
    href: "https://go.cryptosbeginner.com/LedgerWallet",
    affiliate: true,
    image: "/images/wallets/ledger.png",
    domain: "ledger.com",
    color: "#111827",
    mark: "Ld",
  },
  {
    slug: "trezor",
    name: "Trezor",
    category: "hardware",
    fit: "Open-source hardware for Bitcoin and Ethereum users",
    chains: "Bitcoin, Ethereum and a wide software-wallet ecosystem",
    security: "On-device confirmation and optional passphrase accounts.",
    watchFor: "Buy sealed from Trezor. A used device is not a bargain.",
    price: "Paid device",
    href: "https://go.cryptosbeginner.com/Trezor",
    affiliate: true,
    image: "/images/wallets/trezor.png",
    domain: "trezor.io",
    color: "#16a34a",
    mark: "Tz",
  },
  {
    slug: "safepal",
    name: "SafePal",
    category: "hardware",
    fit: "Budget hardware with QR or air-gapped signing",
    chains: "Multi-chain via the SafePal app",
    security: "Air-gapped models can keep the seed offline if you follow the official setup.",
    watchFor: "The phone app is still a hot-wallet surface. Treat the device as the vault.",
    price: "Paid device",
    href: "https://go.cryptosbeginner.com/SafePal",
    affiliate: true,
    image: "/images/wallets/safepal.png",
    domain: "safepal.com",
    color: "#4f46e5",
    mark: "SP",
  },
  {
    slug: "tangem",
    name: "Tangem",
    category: "hardware",
    fit: "Card-shaped NFC wallet for people who want fewer cables",
    chains: "Multi-chain through the Tangem app",
    security: "Keys are generated in the card chip. Seed phrases are optional, not required.",
    watchFor: "Order extra cards as backup. One card with no backup is a single point of failure.",
    price: "Paid device",
    href: "https://tangem.com",
    affiliate: false,
    image: "/images/wallets/tangem.png",
    domain: "tangem.com",
    color: "#0ea5e9",
    mark: "Tg",
  },
  {
    slug: "secux",
    name: "SecuX",
    category: "hardware",
    fit: "Touchscreen hardware for users who want USB or Bluetooth signing",
    chains: "Bitcoin, Ethereum and a large asset list",
    security: "Secure-element hardware with on-screen address checks.",
    watchFor: "Buy from SecuX or a known retailer. Check the seal before setup.",
    price: "Paid device",
    href: "https://secuxtech.com",
    affiliate: false,
    image: "/images/wallets/secux.png",
    domain: "secuxtech.com",
    color: "#1d4ed8",
    mark: "SX",
  },
  {
    slug: "coolwallet",
    name: "CoolWallet Pro",
    category: "hardware",
    fit: "Credit-card sized Bluetooth hardware for travel",
    chains: "Bitcoin, Ethereum, major tokens and DeFi via the CoolWallet app",
    security: "Secure element in a thin card. Confirm sends in the official app.",
    watchFor: "Keep the card and phone pairing under your control. Do not set it up from a random QR poster.",
    price: "Paid device",
    href: "https://www.coolwallet.io/products/coolwallet-pro/?ref=ywvizdk",
    affiliate: true,
    image: "/images/wallets/coolwallet.png",
    domain: "coolwallet.io",
    color: "#111827",
    mark: "CW",
  },
  {
    slug: "metamask",
    name: "MetaMask",
    category: "extension",
    fit: "Ethereum and EVM apps in the browser",
    chains: "Ethereum and EVM networks",
    security: "Non-custodial. You hold the seed. Phishing is the usual failure.",
    watchFor: "Fake extensions and blind signature requests.",
    price: "Free app",
    href: "https://metamask.io",
    affiliate: false,
    image: "/images/wallets/metamask.png",
    domain: "metamask.io",
    color: "#f6851b",
    mark: "MM",
  },
  {
    slug: "phantom",
    name: "Phantom",
    category: "mobile",
    fit: "Solana users who also want a simple extension",
    chains: "Solana first, with extra networks in the current app",
    security: "Non-custodial daily wallet. Not a vault for large savings.",
    watchFor: "Download only from phantom.app or official stores.",
    price: "Free app",
    href: "https://phantom.app",
    affiliate: false,
    image: "/images/wallets/phantom.svg",
    domain: "phantom.app",
    color: "#ab9ff2",
    mark: "Ph",
  },
  {
    slug: "trust-wallet",
    name: "Trust Wallet",
    category: "mobile",
    fit: "Multi-chain phone wallet for beginners",
    chains: "Multi-chain mobile wallet",
    security: "Non-custodial if you create it and back up the phrase yourself.",
    watchFor: "Clone apps in unofficial stores.",
    price: "Free app",
    href: "https://trustwallet.com",
    affiliate: false,
    image: "/images/wallets/trustwallet.png",
    domain: "trustwallet.com",
    color: "#3375bb",
    mark: "TW",
  },
  {
    slug: "backpack",
    name: "Backpack",
    category: "extension",
    fit: "Solana users who want a trading-focused wallet",
    chains: "Solana-focused",
    security: "Non-custodial hot wallet.",
    watchFor: "Use backpack.app only.",
    price: "Free app",
    href: "https://backpack.app",
    affiliate: false,
    image: "/images/wallets/backpackwallet.jpg",
    domain: "backpack.app",
    color: "#e11d48",
    mark: "Bp",
  },
  {
    slug: "okx-wallet",
    name: "OKX Wallet",
    category: "extension",
    fit: "Multi-chain DeFi users who already use OKX",
    chains: "EVM, Solana and other networks in the OKX Wallet app",
    security: "Non-custodial wallet product. Separate from an OKX exchange account if you create your own seed.",
    watchFor: "Do not mix exchange login recovery with wallet seed recovery.",
    price: "Free app",
    href: "https://www.okx.com/web3",
    affiliate: false,
    image: "/images/wallets/okxwallet.png",
    domain: "okx.com",
    color: "#111827",
    mark: "OK",
  },
  {
    slug: "base-wallet",
    name: "Base / Coinbase Wallet",
    category: "mobile",
    fit: "Users who want a self-custody app beside Base and Coinbase products",
    chains: "Base, Ethereum and other networks supported in Coinbase Wallet",
    security: "Self-custody if you hold the recovery phrase. A Coinbase.com account is a different product.",
    watchFor: "Download from wallet.coinbase.com. An exchange password is not a seed phrase.",
    price: "Free app",
    href: "https://wallet.coinbase.com",
    affiliate: false,
    image: "/images/wallets/basewallet.png",
    domain: "base.org",
    color: "#0052ff",
    mark: "Bs",
  },
  {
    slug: "bitget-wallet",
    name: "Bitget Wallet",
    category: "mobile",
    fit: "Multi-chain mobile wallet with swaps and Web3 access",
    chains: "Multi-chain Web3 wallet",
    security: "Non-custodial if you create the wallet and store the phrase yourself.",
    watchFor: "Use the official Bitget Wallet invite or store listing. Do not restore a seed from a chat message.",
    price: "Free app",
    href: "https://web3.bitget.com/share/h0Nk8?inviteCode=pC8Hzp",
    affiliate: true,
    image: "/images/wallets/bitgetwallet.png",
    domain: "bitget.com",
    color: "#00f0ff",
    mark: "BG",
  },
];

export const walletFaqs = [
  {
    q: "What is the best crypto wallet in 2026?",
    a: "There is no single best wallet. Hardware suits savings. Mobile and extensions suit daily use. Pick the one whose chains and backup process you understand.",
  },
  {
    q: "Is an exchange account a wallet?",
    a: "No. An exchange balance is an IOU. A self-custody wallet holds keys that you control.",
  },
  {
    q: "Should I keep all my crypto on a phone?",
    a: "No. Keep a small amount for spending. Keep larger savings on hardware.",
  },
  {
    q: "What happens if I lose my seed phrase?",
    a: "If the device and the phrase are both gone, the funds are usually unrecoverable. Support cannot recreate a lost phrase.",
  },
];
