export type CardCategory = "prepaid" | "debit" | "dual-mode" | "self-custody";

export type CardListing = {
  slug: string;
  name: string;
  provider: string;
  network: string;
  categories: CardCategory[];
  shortDescription: string;
  editorialSummary: string;
  bestFor: string;
  availability: string;
  regions: string[];
  pricing: string;
  rewards: string;
  funding: string;
  cardFormats: string[];
  sourceUrl: string;
  sourceLabel: string;
  imageUrl: string;
  imageAlt: string;
  imageSourceNote: string;
  reviewedAt: string;
  caution: string;
  referralUrl?: string;
  referralLabel?: string;
  feesUrl?: string;
  updateUrl?: string;
  updateLabel?: string;
  updateNote?: string;
  applicationMethod?: string;
  verification?: string;
  galleryImages?: { url: string; alt: string; source: string }[];
  featureTags?: string[];
  pros?: string[];
  cons?: string[];
  noKycStatus?: "not-verified" | "provider-claims-no-credit-check" | "provider-states-no-kyc";
};

export function getCardFaqs(card: CardListing) {
  const question = card.referralUrl ? `Why is ${card.name} featured in this directory?` : `What should I verify before choosing ${card.name}?`;
  const answer = card.referralUrl
    ? `${card.name} is featured because its published product model and current provider information give readers a useful starting point for assessing its stated audience, fees, funding route, and eligibility. This page also includes a clearly disclosed referral link; using it is optional and does not guarantee approval, pricing, rewards, security, availability, or suitability.`
    : `Check the provider’s current country eligibility, issuer, verification process, funding route, complete fee schedule, limits, and tax treatment before making your own decision. This profile is educational comparison content, not a personal recommendation.`;
  return [
    { question: `What does ${card.name} cost?`, answer: `${card.pricing} Provider fees and regional terms can change, so use the linked fee details before applying.` },
    { question: `How is ${card.name} funded?`, answer: card.funding },
    { question: `Where is ${card.name} available?`, answer: card.availability },
    { question, answer },
  ];
}

export const cardListings: CardListing[] = [
  {
    slug: "coinbase-card",
    name: "Coinbase Card",
    provider: "Coinbase",
    network: "Visa",
    categories: ["prepaid", "debit"],
    shortDescription: "A US-focused Visa prepaid debit card that converts crypto to USD when you spend.",
    editorialSummary: "Coinbase positions this card as a bridge between a Coinbase balance and everyday Visa purchases. The important detail is that crypto is converted to USD for spending; the reward rate is an optional, variable US offer rather than a permanent universal rate.",
    bestFor: "People who already use Coinbase and want a familiar cash-or-crypto spending rail.",
    availability: "United States; Coinbase says all states except Hawaii on the reviewed page.",
    regions: ["United States"],
    pricing: "No Coinbase transaction fees or annual fee are advertised on the reviewed page; a spread may apply when crypto is bought, sold, or traded.",
    rewards: "Optional crypto rewards for eligible US card users; the rate is variable and should be checked in the Coinbase app.",
    funding: "Coinbase balance, bank account funding, or eligible paycheck deposit; crypto is converted to USD for purchases and ATM withdrawals.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.coinbase.com/card",
    sourceLabel: "Coinbase Card product page",
    imageUrl: "https://images.ctfassets.net/o10es7wu5gm1/4AsEsKXTMmSVky9wG1MNqM/1ceaf6ca937f526948ea3b909edb2e71/landing_hero_white_bg.png",
    imageAlt: "Blue Coinbase Visa debit card on a white background",
    imageSourceNote: "Official Coinbase-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Eligibility, limits, rewards, and account verification requirements apply. This is not a credit card recommendation.",
  },
  {
    slug: "crypto-com-visa-card",
    name: "Crypto.com Visa Card",
    provider: "Crypto.com",
    network: "Visa",
    categories: ["prepaid"],
    shortDescription: "A prepaid Visa card with tiered CRO rewards, subscription options, or CRO lockup requirements.",
    editorialSummary: "Crypto.com publishes multiple card tiers rather than one flat product. The cost-and-benefit trade-off depends on the selected tier, CRO subscription or lockup route, reward caps, ATM allowance, and the country-specific cardholder agreement.",
    bestFor: "Users comparing a tiered prepaid card model and willing to read the current regional terms.",
    availability: "Jurisdiction-dependent; Crypto.com publishes separate regional disclosures.",
    regions: ["United States", "Europe", "Canada", "Australia", "Brazil", "Singapore", "United Kingdom"],
    pricing: "The reviewed USD table showed free Midnight Blue, $4.99/month or $49.90/year Ruby Steel, and $29.99/month or $299.90/year Jade Green; higher tiers use CRO lockup requirements. Terms vary by region.",
    rewards: "The reviewed USD table showed 0% to 5% CRO rewards on everyday spending by tier, with caps on some tiers; offers can change.",
    funding: "Crypto is converted to the applicable market currency before loading and spending; cardholders cannot load cryptocurrency directly onto the prepaid card.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://crypto.com/en/cards/",
    sourceLabel: "Crypto.com Cards page",
    imageUrl: "https://mkt-site-asset.crypto.com/assets/card-page/tiers/Midnight_2.webp",
    imageAlt: "Crypto.com Midnight Blue Visa prepaid card",
    imageSourceNote: "Official Crypto.com-hosted tier image",
    reviewedAt: "2026-08-27",
    caution: "Rewards, lockups, limits, fees, issuers, and availability vary by country and card tier. Verify the applicable cardholder agreement before applying.",
    referralUrl: "https://cryptocom.sjv.io/6yYRZV",
    referralLabel: "Check Crypto.com card options",
    feesUrl: "https://help.crypto.com/en/articles/5966563-crypto-com-prepaid-visa-card-fees-and-limits-united-states",
    updateUrl: "https://crypto.com/en/cards/",
    updateLabel: "Latest tier terms",
    updateNote: "Crypto.com maintains regional card pages and fee articles; the displayed tier, reward, and lockup terms should be rechecked before applying.",
    applicationMethod: "Create or sign in to a Crypto.com account, complete the applicable verification, and apply for the card tier shown in your region.",
    verification: "Account verification and regional eligibility apply.",
    galleryImages: [
      { url: "https://mkt-site-asset.crypto.com/assets/card-page/tiers/Ruby_2.webp", alt: "Crypto.com Ruby Steel Visa card", source: "Official Crypto.com card tier image" },
      { url: "https://mkt-site-asset.crypto.com/assets/card-page/tiers/Jade_2.webp", alt: "Crypto.com Jade Green Visa card", source: "Official Crypto.com card tier image" },
    ],
  },
  {
    slug: "wirex-one-card",
    name: "Wirex One Card",
    provider: "Wirex",
    network: "Visa or Mastercard",
    categories: ["debit", "prepaid"],
    shortDescription: "A virtual, physical, or metal card tied to the Wirex One spending platform.",
    editorialSummary: "Wirex One is presented as a multi-format spending product for crypto and fiat users. Wirex advertises zero FX fees and cashback by membership tier, but the headline reward range should be read alongside eligibility, tier rules, and jurisdictional availability.",
    bestFor: "People looking for a broad international card proposition with virtual, physical, and metal formats.",
    availability: "Wirex advertises availability in 150+ countries, subject to product and jurisdictional restrictions.",
    regions: ["150+ countries advertised; verify residence eligibility"],
    pricing: "The reviewed product page advertises no monthly or annual card fee; applicable terms and regional charges should be checked with Wirex.",
    rewards: "Wirex advertises 0.5% to 8% cashback in USD depending on membership tier.",
    funding: "Spend crypto and fiat through the Wirex One app; conversion and supported-asset details depend on the account and region.",
    cardFormats: ["Virtual", "Physical", "Visa Signature Metal"],
    sourceUrl: "https://www.wirexapp.com/stablecoin-and-crypto-card",
    sourceLabel: "Wirex One product page",
    imageUrl: "https://static.wixstatic.com/media/f627bc_55b10739e1a34d64a4e43c3dbfa09e3c~mv2.png",
    imageAlt: "Wirex physical crypto card",
    imageSourceNote: "Official Wirex-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Wirex states that availability and features are subject to jurisdictional limitations. Headline cashback is not a guaranteed rate for every user.",
  },
  {
    slug: "metamask-card",
    name: "MetaMask Card",
    provider: "MetaMask",
    network: "Mastercard",
    categories: ["debit", "self-custody"],
    shortDescription: "A crypto debit card connected to a MetaMask wallet, with Virtual and Metal options.",
    editorialSummary: "MetaMask emphasizes that users retain control of supported wallet assets until payment. The product has a free Virtual option and a paid Metal option, with supported networks, tokens, regions, and transaction fees that need to be checked before sign-up.",
    bestFor: "Self-custody users who want a wallet-linked spending experience instead of a conventional exchange balance.",
    availability: "Country and territory dependent; the reviewed page listed supported countries and noted temporarily closed US and UK signups.",
    regions: ["Selected countries in Europe and Latin America; verify current list"],
    pricing: "Virtual is listed as free; Metal is listed at $199/year. A minimal transaction fee may apply.",
    rewards: "The reviewed page lists 1% mUSD back for Virtual and 3% for Metal on the first $10,000 of spend, then 1% for Metal; terms apply.",
    funding: "Supported assets can be managed from MetaMask on Linea, Solana, Monad, and Base, with conversion at checkout.",
    cardFormats: ["Virtual", "Metal"],
    sourceUrl: "https://metamask.io/card",
    sourceLabel: "MetaMask Card product page",
    imageUrl: "https://images.ctfassets.net/clixtyxoaeas/5VagZ4WBPVakQ7kz8uqo23/6788ca0e712c6c8a5f87ea7d5a1fc187/card-hero.png?w=2048&q=75&fm=avif",
    imageAlt: "MetaMask Card product image",
    imageSourceNote: "Official MetaMask-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Self-custody does not remove smart-contract, wallet, conversion, tax, or payment-rail risk. Do not enter a seed phrase anywhere to obtain a card.",
  },
  {
    slug: "nexo-card",
    name: "Nexo Card",
    provider: "Nexo",
    network: "Mastercard",
    categories: ["dual-mode", "debit"],
    shortDescription: "A dual-mode card that can spend digital assets or access credit against collateral.",
    editorialSummary: "Nexo’s defining distinction is the switch between Debit Mode and Credit Mode. That flexibility also adds complexity: borrowing against crypto introduces collateral and liquidation considerations, while physical-card access and rewards depend on balance, loyalty tier, and region.",
    bestFor: "Eligible users who understand the difference between spending assets and borrowing against them.",
    availability: "Selected European countries including the EEA and UK, subject to identity verification and eligibility.",
    regions: ["EEA and United Kingdom, selected countries"],
    pricing: "Nexo states no monthly, annual, or inactivity card fees; FX charges and other terms vary by region, tier, and usage.",
    rewards: "Up to 2% crypto cashback in Credit Mode, with published tier and balance requirements.",
    funding: "Debit Mode spends eligible digital assets; Credit Mode borrows against collateral without selling the collateral asset.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://nexo.com/crypto-card",
    sourceLabel: "Nexo Card product page",
    imageUrl: "https://content.nexo.com/media/crypto_card-atf_full-card-d-row.jpg",
    imageAlt: "Nexo crypto card",
    imageSourceNote: "Official Nexo-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Credit Mode is borrowing, not free spending. Collateral, interest, liquidation, eligibility, and tax considerations require separate review.",
    referralUrl: "https://nexo.sjv.io/ZQz0gq",
    referralLabel: "Visit Nexo Card",
    feesUrl: "https://nexo.com/crypto-card",
    updateUrl: "https://nexo.com/crypto-card",
    updateLabel: "Latest Nexo Card terms",
    updateNote: "Nexo publishes the current mode, loyalty, FX, ATM, and regional terms on its Card page and related fee documents.",
    applicationMethod: "Create or sign in to a Nexo account, complete identity verification, and activate the virtual or physical card if eligible.",
    verification: "Nexo states selected European-country availability and identity verification requirements.",
    galleryImages: [
      { url: "https://content.nexo.com/media/crypto_card-usp_comparison-debit-UK-2.jpg", alt: "Nexo Card debit mode visual", source: "Official Nexo product image" },
      { url: "https://content.nexo.com/media/crypto_card-usp_comparison-credit-UK-2.jpg", alt: "Nexo Card credit mode visual", source: "Official Nexo product image" },
    ],
  },
  {
    slug: "ledger-cl-card",
    name: "CL Card, Ledger-compatible",
    provider: "Baanx, designed for Ledger",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A provider-issued crypto debit card designed to work with Ledger Wallet and Ledger signers.",
    editorialSummary: "Ledger’s card program is a partner marketplace rather than a Ledger-issued card. The CL Card page attributes the product to Baanx and explains that regional providers and account arrangements can differ, while Ledger Wallet provides the funding workflow.",
    bestFor: "Ledger users who want to connect hardware-wallet workflows with a card provider.",
    availability: "Country-dependent; the provider and underlying account arrangement vary by residence.",
    regions: ["Country-dependent; check the card flow in Ledger Wallet"],
    pricing: "The reviewed product page does not present one universal fee schedule; provider and country terms apply.",
    rewards: "1% cashback in BTC, USDC, or USDT depending on country of residence; no staking required is advertised.",
    funding: "Ledger Wallet can fund the card with BTC, ETH, SOL, stablecoins, and other supported assets; Apple Pay and Google Pay are listed.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://shop.ledger.com/pages/cl-card-crypto-card",
    sourceLabel: "Ledger CL Card product page",
    imageUrl: "https://ledger.com/cdn-cgi/image/width=3840,format=auto/https://images.ctfassets.net/ge894kijjvls/1LCkGVxczDIXQIfcXJJn5i/d33ec47a90536b2dc859a00f21b2f0b7/hero_cl_card_desktop__2_.webp",
    imageAlt: "Ledger-compatible CL Card with Ledger device",
    imageSourceNote: "Official Ledger-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Ledger is not the card issuer. Provider, fee, issuer, and country-specific terms must be verified before applying.",
  },
  {
    slug: "redotpay-card",
    name: "RedotPay Card",
    provider: "RedotPay",
    network: "Card networks vary by region",
    categories: ["prepaid", "debit"],
    shortDescription: "A stablecoin-based spending card with virtual and physical formats.",
    editorialSummary: "RedotPay combines a stablecoin spending card with a broader payments app. The official card page separates physical and virtual use cases, while the Help Center publishes the issuance and usage economics. That makes the card easier to compare when the one-time issuance cost is not confused with ongoing fees.",
    bestFor: "Stablecoin users who want a card plus app-based payment rails, subject to local availability.",
    availability: "Registration is unavailable in certain countries and regions; verify the current unsupported-country list.",
    regions: ["Global with country and region exclusions"],
    pricing: "The official Help Center lists a $10 virtual-card issuance fee and $100 physical-card issuance fee. RedotPay states there is no monthly or annual card-management fee; transaction, ATM, conversion, and other charges may still apply.",
    rewards: "No universal card reward rate is stated on the reviewed card page; separate RedotPay rewards or Earn features may have their own conditions.",
    funding: "Stablecoins and other supported assets are managed through the RedotPay app and converted for card spending or withdrawals.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.redotpay.com/card",
    sourceLabel: "RedotPay Card product page",
    imageUrl: "https://staticsource1.redotpay.com/web/img/card/cover-1.webp?t=1787044314761",
    imageAlt: "RedotPay physical stablecoin card",
    imageSourceNote: "Official RedotPay-hosted card image",
    reviewedAt: "2026-08-27",
    caution: "Card availability, supported assets, verification, fees, and unsupported regions can change. Read the current RedotPay Help Center and terms before funding an account.",
    referralUrl: "https://go.cryptosbeginner.com/RedotPay",
    referralLabel: "Check RedotPay card",
    feesUrl: "https://helpcenter.redotpay.com/en/articles/10339271-redotpay-card-limitations-fees",
    updateUrl: "https://www.redotpay.com/news",
    updateLabel: "RedotPay updates",
    updateNote: "RedotPay currently highlights Apple Pay support and maintains separate product, verification, terms, and Help Center pages.",
    applicationMethod: "Download the RedotPay app, complete the provider’s account and verification flow, and choose the virtual or physical card available in your region.",
    verification: "Account verification and regional restrictions apply; RedotPay links to a dedicated verification area.",
    galleryImages: [
      { url: "https://staticsource1.redotpay.com/web/img/card/cover-2.webp?t=1787044314761", alt: "RedotPay virtual card section visual", source: "Official RedotPay card page" },
    ],
  },
  {
    slug: "rizon-card",
    name: "Rizon Visa Card",
    provider: "Rizon",
    network: "Visa",
    categories: ["debit"],
    shortDescription: "A Rizon Visa card with virtual, plastic, and metal formats for eligible residents.",
    editorialSummary: "Rizon presents its card alongside USD and stablecoin payment rails, with virtual, plastic, metal, and Visa Platinum options. Its services-restriction notice is essential context: the product landing page is not a promise of universal global eligibility, even though it advertises broad merchant acceptance.",
    bestFor: "Eligible US or Latin American residents comparing a stablecoin-linked Visa with several physical formats.",
    availability: "The official services notice limits the intended audience to residents and domiciled individuals in the United States or certain Latin American countries, subject to licensing.",
    regions: ["United States and certain Latin American countries"],
    pricing: "Rizon directs users to its fees-and-limits page for current card, spending, withdrawal, and account costs rather than publishing one universal price on the card landing page.",
    rewards: "The official Rizon product materials advertise cashback, with the applicable amount and conditions dependent on card type, account, and current terms.",
    funding: "Rizon describes stablecoin and USD services connected to its app; virtual, plastic, and metal card funding and conversion rules should be confirmed in the account flow.",
    cardFormats: ["Virtual", "Plastic", "Metal", "Visa Platinum"],
    sourceUrl: "https://www.getrizon.com/card",
    sourceLabel: "Rizon Visa Card page",
    imageUrl: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/67ffab826b4e439a79e46e2e_hero.webp",
    imageAlt: "Rizon Visa card held in a hand",
    imageSourceNote: "Official Rizon-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Rizon’s services restriction and country eligibility notice override broad merchant-count marketing. Confirm residence eligibility and current fees before applying.",
    referralUrl: "https://getrizon.sng.link/Eshdf/1cro/dfwn?ref=UZ6Q9CI&_forward_params=2",
    referralLabel: "Check Rizon Card",
    feesUrl: "https://www.getrizon.com/fees-and-limits",
    updateUrl: "https://www.getrizon.com/blog",
    updateLabel: "Rizon updates",
    updateNote: "Rizon maintains a product blog, fee-and-limit page, and Terms of Service; features and country access can change as licensing expands.",
    applicationMethod: "Download the Rizon app, create an account, complete the applicable verification, and request the card format offered for your residence.",
    verification: "The page displays a services-restriction notice and country-dependent onboarding; verification and eligibility apply.",
    galleryImages: [
      { url: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/69391318bfc66e4655cf23d8_card-1-img.avif", alt: "Rizon card option one", source: "Official Rizon card page" },
      { url: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/693913c0bb8a2900a6e1cf93_card-2-img.avif", alt: "Rizon card option two", source: "Official Rizon card page" },
      { url: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/693914286e0894ff7d8e238e_card-3-img.avif", alt: "Rizon card option three", source: "Official Rizon card page" },
    ],
  },
  {
    slug: "bybit-card",
    name: "Bybit Card",
    provider: "Bybit",
    network: "Mastercard",
    categories: ["prepaid", "debit"],
    shortDescription: "A crypto spending card with a published cashback range and strict regional limitations.",
    editorialSummary: "Bybit’s card page leads with everyday spending and a 2%–10% cashback range, but its country notice is just as important as the reward headline. Bybit states that the product is not meant for European Economic Area customers, so the directory treats regional eligibility as a primary fact rather than a footnote.",
    bestFor: "Eligible non-EEA users who want a Bybit-linked payment card and are comfortable checking current reward terms.",
    availability: "Certain countries only; the reviewed official notice explicitly excludes European Economic Area customers.",
    regions: ["Selected countries outside the EEA"],
    pricing: "Bybit’s card page does not publish one universal fee table in the visible overview; card, conversion, ATM, and regional fees should be checked in the application flow and terms.",
    rewards: "Bybit advertises 2%–10% cashback on everyday spending and a welcome package with up to 110 USDT cashback in the first 30 days; terms and eligible categories apply.",
    funding: "Bybit describes flexible crypto-or-cash spending through its platform; the exact supported assets and top-up method depend on the eligible regional product.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.bybit.com/en/cards/",
    sourceLabel: "Bybit Card product page",
    imageUrl: "https://www.bybit.com/bycsi-root/common-static/fiat-static/cards/landing_next/bybit_card.png?format=webp&quality=75&resize=width%2F480",
    imageAlt: "Bybit Card Mastercard product image",
    imageSourceNote: "Official Bybit-hosted Card product image",
    reviewedAt: "2026-08-27",
    caution: "The Bybit page explicitly excludes EEA customers. Cashback, fees, merchant categories, and eligibility are not universal and may change.",
    referralUrl: "https://go.cryptosbeginner.com/ByBitCard",
    referralLabel: "Check Bybit Card",
    feesUrl: "https://www.bybit.com/en/cards/",
    updateUrl: "https://www.bybit.com/en/cards/",
    updateLabel: "Latest Bybit Card terms",
    updateNote: "Bybit publishes current eligibility and fee FAQs within its Card flow; the visible region notice should be checked before sign-up.",
    applicationMethod: "Apply through an eligible Bybit account, complete identity verification, and follow the regional virtual or physical card onboarding flow.",
    verification: "Identity verification and country eligibility apply; EEA customers are explicitly excluded on the reviewed page.",
    galleryImages: [
      { url: "https://www.bybit.com/bycsi-root/common-static/fiat-static/cards/landing_next/card_designs/default.png?format=avif&quality=75&resize=width%2F2880", alt: "Bybit Card default design", source: "Official Bybit Card page" },
      { url: "https://www.bybit.com/bycsi-root/common-static/fiat-static/cards/landing_next/card_designs/tmrland.png?format=avif&quality=75&resize=width%2F2880", alt: "Bybit Card limited design", source: "Official Bybit Card page" },
    ],
  },
  {
    slug: "bitget-wallet-card",
    name: "Bitget Wallet Card",
    provider: "Bitget Wallet",
    network: "Visa or Mastercard",
    categories: ["debit", "prepaid"],
    shortDescription: "A wallet-linked spending card with selectable assetback rewards.",
    editorialSummary: "Bitget Wallet frames the card around assetback: eligible users can choose reward assets such as BTC, gold-linked assets, stocks, or USDC. The product page also emphasizes familiar payment rails and no opening or annual fee, while the regional fee page remains the authority for activation and other charges.",
    bestFor: "Users who want a wallet-based card and prefer choosing the asset in which rewards are paid.",
    availability: "Region-dependent; eligibility and card availability should be checked in the current application flow.",
    regions: ["Selected regions; verify in application"],
    pricing: "The official regional fee page states no monthly or annual fee and no top-up fee, with a $0.10 activation fee shown for that region; other regional charges may differ.",
    rewards: "The product page advertises up to 3% assetback, with reward assets, eligible purchases, and settlement conditions applying.",
    funding: "Apply online, complete identity verification, activate and top up the card, then spend through Visa/Mastercard rails and collect assetback.",
    cardFormats: ["Virtual", "Physical availability varies"],
    sourceUrl: "https://web3.bitget.com/card",
    sourceLabel: "Bitget Wallet Card product page",
    imageUrl: "https://web3.bitget.com/bgwactivity-static/_next/static/media/cardHeroPhoneEn.305uvu1oe992v.png",
    imageAlt: "Bitget Wallet Card in the Bitget Wallet app",
    imageSourceNote: "Official Bitget Wallet-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "“Up to 3%” is a provider headline, not a guaranteed rate. Confirm eligible purchases, reward assets, regional fees, and settlement timing.",
    referralUrl: "https://web3.bitget.com/share/h0Nk8?inviteCode=pC8Hzp",
    referralLabel: "Check Bitget Wallet Card",
    feesUrl: "https://web3.bitget.com/helpCenter/283",
    updateUrl: "https://web3.bitget.com/en/academy/how-to-use-a-crypto-card-a-beginners-guide-to-spending-bitcoin-and-stablecoins",
    updateLabel: "Bitget Card guide",
    updateNote: "Bitget Wallet maintains a fee center and Academy guides; the exact card flow, region, rewards, and fee schedule can change.",
    applicationMethod: "Apply online through Bitget Wallet, complete identity verification, activate the card, and top up before spending.",
    verification: "The official setup flow begins with online application and identity verification.",
    galleryImages: [
      { url: "https://web3.bitget.com/bgwactivity-static/_next/static/media/cardBadgeBtc.3g1m7-4fir6z_.png", alt: "Bitget Wallet Card BTC reward badge", source: "Official Bitget Wallet product image" },
      { url: "https://web3.bitget.com/bgwactivity-static/_next/static/media/cardBadgeNvda.0l31qjsw_sbzf.png", alt: "Bitget Wallet Card stock reward badge", source: "Official Bitget Wallet product image" },
    ],
  },
  {
    slug: "kardpay-card",
    name: "KardPay Card",
    provider: "KardPay",
    network: "Visa or Mastercard",
    categories: ["prepaid", "debit"],
    shortDescription: "A tiered crypto spending card with one-time pricing and published top-up fees.",
    editorialSummary: "KardPay publishes a useful tier table: Core, Pro, and Elite differ in one-time price, annual or monthly limits, top-up percentage, support, and physical-card availability. That structure is more informative than calling the product simply ‘cashback’ or ‘low fee.’",
    bestFor: "Users comparing explicit one-time card tiers and willing to price the top-up cost against their actual spending pattern.",
    availability: "The official page advertises 180+ countries; eligibility and card issuance remain subject to the account flow and provider terms.",
    regions: ["180+ countries advertised; verify residence"],
    pricing: "Core is listed at $29 one-time with 5% top-up fees; Pro at $99 one-time with 4% top-up fees; Elite at $299 one-time with 3% top-up fees. Physical Elite is listed at $299 one-time with a 4% top-up fee and pre-orders soon.",
    rewards: "The KardPay site advertises up to 2% cashback; the applicable tier, asset, limits, and reward conditions should be confirmed in current terms.",
    funding: "The official hero describes spending USDT, USDC, and other crypto anywhere Visa or Mastercard is accepted, with instant top-up messaging.",
    cardFormats: ["Virtual", "Physical Elite pre-order"],
    sourceUrl: "https://kardpay.app/?lang=en",
    sourceLabel: "KardPay official product page",
    imageUrl: "https://kardpay.app/__l5e/assets-v1/6a06e87f-dc13-439a-8660-ba94c3ff8569/visa-card-green.svg",
    imageAlt: "KardPay Core green Visa/Mastercard card",
    imageSourceNote: "Official KardPay-hosted card asset",
    reviewedAt: "2026-08-27",
    caution: "Top-up percentages and tier limits materially affect total cost. Physical Elite was marked pre-orders soon on the reviewed page.",
    referralUrl: "https://app.kardpay.app/auth?ref=420E7DF6",
    referralLabel: "Check KardPay tiers",
    feesUrl: "https://kardpay.app/?lang=en#pricing",
    updateUrl: "https://kardpay.app/?lang=en",
    updateLabel: "Latest KardPay pricing",
    updateNote: "KardPay publishes tier prices, limits, top-up fees, and card availability on its official pricing page; confirm the current table before funding.",
    applicationMethod: "Open the KardPay application, choose an available tier, complete the provider’s onboarding, and fund the card with supported assets.",
    verification: "Eligibility and any account verification requirements apply through the KardPay application flow.",
    galleryImages: [
      { url: "https://kardpay.app/__l5e/assets-v1/824e75cd-8519-481e-a68f-8f5c24fff77c/visa-card-white.svg", alt: "KardPay Pro white card", source: "Official KardPay product asset" },
      { url: "https://kardpay.app/__l5e/assets-v1/c47b6b86-7bc9-4ac8-aa88-9e42f618d3c4/visa-card-black.svg", alt: "KardPay Elite black card", source: "Official KardPay product asset" },
    ],
  },
  {
    slug: "tria-card",
    name: "Tria Card",
    provider: "Tria",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A self-custodial Visa card with virtual, Signature, and Premium formats.",
    editorialSummary: "Tria places card spending inside a broader self-custodial app for moving, trading, and earning across chains. The official page advertises 150+ countries, 1,000+ supported assets, Apple Pay and Google Pay, and tiered cashback figures; card eligibility, rewards, and app terms remain provider-controlled.",
    bestFor: "Self-custody users comparing a multi-chain card with several advertised benefit tiers.",
    availability: "Tria advertises card spending in 150+ countries; confirm current country eligibility in the application flow.",
    regions: ["150+ countries advertised; verify current eligibility"],
    pricing: "The official page describes a free and instant Virtual Card but does not present one complete public fee table for every tier. Review the current application and legal terms for issuance, conversion, FX, ATM, and premium-card costs.",
    rewards: "Tria advertises 1.5% cashback for Virtual, 4.5% for Signature, and 6% for Premium; these are provider-stated tier figures and conditions apply.",
    funding: "Tria says its Visa card can be loaded with 1,000+ assets from its self-custodial app; conversion and supported-asset rules depend on the current product flow.",
    cardFormats: ["Virtual", "Signature", "Premium metal"],
    sourceUrl: "https://www.tria.so/",
    sourceLabel: "Tria official card page",
    imageUrl: "https://framerusercontent.com/images/QptcGHvZKlMxf5HgeDk5jy8lVRA.png?width=1082&height=687",
    imageAlt: "Tria Virtual Card official product visual",
    imageSourceNote: "Official Tria-hosted Framer product image",
    reviewedAt: "2026-08-27",
    caution: "Self-custody does not eliminate wallet, smart-contract, conversion, tax, or card-issuer risk. Provider cashback and benefit figures are not guaranteed rates for every user.",
    feesUrl: "https://www.tria.so/",
    updateUrl: "https://www.tria.so/en/blogs",
    updateLabel: "Tria product updates",
    updateNote: "Tria publishes product and legal information across its card page, app flow, blog, privacy policy, and legal pages; tier benefits and regional access can change.",
    applicationMethod: "Open the Tria app flow, review the card tier available for your country, complete the provider onboarding, and confirm current terms before funding.",
    verification: "Provider onboarding and country eligibility apply; check the current application flow for the exact verification requirements.",
    galleryImages: [
      { url: "https://framerusercontent.com/images/aO2V4nyxCyYmj17weGDoUO6xjE0.png?width=1088&height=687", alt: "Tria Signature Card official product visual", source: "Official Tria-hosted product image" },
      { url: "https://framerusercontent.com/images/VU0ldHlxZnTfwwqp5BJKkursHXI.png?width=1085&height=683", alt: "Tria Premium Card official product visual", source: "Official Tria-hosted product image" },
    ],
    featureTags: ["Self-custody", "Visa", "1,000+ assets advertised", "150+ countries advertised"],
    pros: ["The provider documents a self-custodial wallet model", "Virtual, Signature, and Premium formats are shown", "Apple Pay and Google Pay are listed"],
    cons: ["The public page does not provide one complete fee table for every tier", "Cashback and benefit figures are conditional provider marketing", "Country and issuer terms must be checked in the app flow"],
  },
  {
    slug: "wallbit-card",
    name: "Wallbit Card",
    provider: "Wallbit",
    network: "Visa",
    categories: ["debit"],
    shortDescription: "A US-issued Platinum Visa card connected to Wallbit’s dollar account and international spending platform.",
    editorialSummary: "Wallbit positions this product around dollar-denominated spending, travel, and a broader global account rather than a crypto-only card. The official page lists a one-time activation fee, no monthly fee, Apple Pay and Google Pay, and broad country marketing; account eligibility and merchant restrictions still matter.",
    bestFor: "Travelers and international users comparing a dollar account with a Visa spending card.",
    availability: "Wallbit advertises use in 180+ countries; country, merchant, billing-address, and account restrictions apply.",
    regions: ["180+ countries advertised; verify current eligibility"],
    pricing: "The reviewed official page lists a one-time $5 activation fee, no maintenance fee, and no commission for spending in dollars. FX, ATM, funding, and account terms should be checked before use.",
    rewards: "No universal card cashback rate is stated on the reviewed card page.",
    funding: "The card spends from Wallbit’s US dollar account and can be linked to Apple Pay or Google Pay; it is not presented as a crypto-only funding rail on the reviewed page.",
    cardFormats: ["Physical Platinum Visa"],
    sourceUrl: "https://www.wallbit.io/en/card",
    sourceLabel: "Wallbit International Visa card page",
    imageUrl: "https://cdn.prod.website-files.com/67aca5c7e0a415189908624c/67db000d3cea6114cf368522_hero-card-phone.avif",
    imageAlt: "Wallbit international Visa card shown with the Wallbit app",
    imageSourceNote: "Official Wallbit-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Wallbit’s card is part of a broader dollar account and payment service. The provider states that declines can result from balance, limits, billing address, or geography.",
    feesUrl: "https://www.wallbit.io/en/card",
    updateUrl: "https://help.wallbit.io/",
    updateLabel: "Wallbit help center",
    updateNote: "Wallbit maintains product, help, privacy, and terms pages; activation fees, account features, and country access can change.",
    applicationMethod: "Open the Wallbit account flow, complete the provider onboarding, review the card terms, and activate the card if it is offered for your residence.",
    verification: "Account onboarding and country eligibility apply; confirm the current requirements in Wallbit’s application flow.",
    galleryImages: [
      { url: "https://cdn.prod.website-files.com/67aca5c7e0a415189908624c/67d88f49fef87f8e58a46b80_passport-second-section-card.avif", alt: "Wallbit card and account visual", source: "Official Wallbit-hosted product image" },
    ],
    featureTags: ["US dollar account", "Visa Platinum", "Apple Pay", "180+ countries advertised"],
    pros: ["The provider publishes a clear $5 activation figure", "Apple Pay and Google Pay support are described", "The broader dollar-account context is visible"],
    cons: ["This is not presented as a crypto-only card", "Country, merchant, billing-address, and account restrictions can affect use", "The reviewed page does not state a universal rewards rate"],
  },
  {
    slug: "winity-card",
    name: "Winity Card",
    provider: "Winity Life",
    network: "Visa",
    categories: ["debit", "prepaid"],
    shortDescription: "A digital-asset-linked Visa with Exclusive virtual, Exclusive physical, and Executive metal tiers.",
    editorialSummary: "Winity combines a Visa card with an app-based digital-asset wallet and loyalty programme. Its official page describes KYC approval, stablecoin loading, card tiers, points, and international use, while also stating that card services are issued in Hong Kong and availability varies by jurisdiction.",
    bestFor: "Users comparing a digital-asset-linked Visa with published card tiers and points rather than a simple cashback table.",
    availability: "Winity advertises 180+ countries, but says services are issued in Hong Kong and availability may vary by jurisdiction.",
    regions: ["180+ countries advertised; jurisdiction-dependent"],
    pricing: "The reviewed page shows the Exclusive virtual card as free to start and lists $20/year in its feature table, with physical-card and limited-issuance conditions requiring confirmation in the current terms.",
    rewards: "Winity shows 1 point per $10 spent for the Exclusive tier; points redemption, eligible transactions, and Executive benefits are subject to the loyalty programme terms.",
    funding: "The provider describes zero-fee USDT and USDC loading, plus ETH, SOL, POL, TRX, WCO, and other assets that convert to USD inside the platform; non-stable assets are shown with a 5% conversion figure on the reviewed page.",
    cardFormats: ["Virtual", "Physical", "Executive metal"],
    sourceUrl: "https://www.winity.life/",
    sourceLabel: "Winity Life official card page",
    imageUrl: "https://www.winity.life/card_exclusive_physical.webp",
    imageAlt: "Winity Exclusive physical Visa card",
    imageSourceNote: "Official Winity Life-hosted card image",
    reviewedAt: "2026-08-27",
    caution: "Winity states that KYC approval is required and that services are issued in Hong Kong. Points, conversion figures, card fees, and jurisdictional access should be confirmed in the current terms.",
    feesUrl: "https://www.winity.life/exclusive",
    updateUrl: "https://www.winity.life/blog",
    updateLabel: "Winity product updates",
    updateNote: "Winity publishes card-tier, loyalty, legal, and risk-disclosure pages; issuance, rewards, conversion, and availability terms can change.",
    applicationMethod: "Download the Winity Life app, complete identity verification, choose an available tier, load supported assets, and confirm the current card terms before spending.",
    verification: "The official page states that the Exclusive virtual card is issued upon KYC approval; jurisdictional eligibility also applies.",
    galleryImages: [
      { url: "https://www.winity.life/card_exclusive_virtual.webp", alt: "Winity Exclusive virtual card", source: "Official Winity Life card image" },
      { url: "https://www.winity.life/card_executive_metal.webp", alt: "Winity Executive metal card", source: "Official Winity Life card image" },
      { url: "https://www.winity.life/hero_phone.webp", alt: "Winity Life app with card interface", source: "Official Winity Life app image" },
    ],
    featureTags: ["KYC approval", "Visa", "USDT/USDC loading", "180+ countries advertised"],
    pros: ["The provider publishes multiple card formats and a points model", "Stablecoin loading and supported-asset details are shown", "Official legal and risk-disclosure links are easy to locate"],
    cons: ["KYC approval and jurisdictional access are required", "The $20/year figure needs current tier and issuance confirmation", "Points are not the same as guaranteed cashback"],
  },
  {
    slug: "oppiwallet-card",
    name: "OppiWallet Card",
    provider: "OppiWallet",
    network: "Mastercard",
    categories: ["debit", "self-custody"],
    shortDescription: "A self-custody wallet-linked virtual Mastercard for spending supported crypto assets.",
    editorialSummary: "OppiWallet describes a virtual Mastercard that lets users top up from a self-custody wallet while keeping private keys on the device until the card is funded. Its dedicated card page publishes an activation rebate, foreign-exchange range, supported assets, Apple Pay and Google Pay support, and country caveats.",
    bestFor: "Readers comparing a self-custody virtual card with clearly stated activation and FX costs.",
    availability: "Oppi advertises availability in 210+ countries, subject to local regulatory and provider restrictions.",
    regions: ["210+ countries advertised; verify current eligibility"],
    pricing: "The dedicated card page lists a $10 virtual-card activation fee with $5 credited back, an effective setup cost of $5, no monthly or annual fee, and a 2%–2.5% FX charge for non-USD purchases. Physical-card pricing is listed separately.",
    rewards: "No universal cashback rate is stated on the reviewed dedicated card page.",
    funding: "BTC, ETH, USDT, USDC, and other supported assets can be topped up from the Oppi self-custody wallet and converted into a spendable card balance.",
    cardFormats: ["Virtual Mastercard", "Physical availability varies"],
    sourceUrl: "https://oppiwallet.com/en/virtual-crypto-card",
    sourceLabel: "OppiWallet virtual card page",
    imageUrl: "https://oppiwallet.com/assets/images/card-activation-steps/card-activation-success-virtualcard.png",
    imageAlt: "OppiWallet virtual card activation screen",
    imageSourceNote: "Official OppiWallet-hosted card visual",
    reviewedAt: "2026-08-27",
    caution: "Oppi states that KYC is required to enable card features. Self-custody before top-up does not remove card, conversion, issuer, merchant, or regulatory risk.",
    feesUrl: "https://oppiwallet.com/en/virtual-crypto-card",
    updateUrl: "https://oppiwallet.com/en",
    updateLabel: "OppiWallet product page",
    updateNote: "Oppi publishes card, wallet, AML, privacy, and terms pages; activation, FX, physical-card, supported-asset, and country terms should be rechecked before funding.",
    applicationMethod: "Download OppiWallet, create the self-custody wallet, complete the provider’s identity-verification flow, activate the virtual card, and top up only what you plan to spend.",
    verification: "Oppi’s dedicated card page states that KYC is required to enable card features; country eligibility also applies.",
    galleryImages: [
      { url: "https://oppiwallet.com/assets/images/card-activation-steps/selection-card-virtualcard.png", alt: "OppiWallet virtual card selection screen", source: "Official OppiWallet card visual" },
      { url: "https://oppiwallet.com/og-store-image.png", alt: "OppiWallet official product visual", source: "Official OppiWallet product image" },
    ],
    featureTags: ["Self-custody", "Mastercard", "$5 effective activation cost", "BTC/ETH/USDT/USDC"],
    pros: ["The provider publishes an activation rebate and FX range", "Supported assets and self-custody top-up model are described", "Apple Pay and Google Pay support are listed"],
    cons: ["KYC is required for card features", "A 2%–2.5% FX charge applies to non-USD purchases on the reviewed page", "Country and physical-card availability can vary"],
  },
  {
    slug: "wavecard",
    name: "wavecard",
    provider: "wave.space",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "An EEA Bitcoin debit card that can connect to a Lightning wallet.",
    editorialSummary: "wavecard is a Bitcoin-only spending product that links card payments to Bitcoin funding and, according to the provider, can connect to a self-custodial Lightning wallet. Its advertised 0% FX fee should be read alongside the separate Bitcoin conversion fee and exchange spread.",
    bestFor: "EEA residents who specifically want Bitcoin and Lightning-wallet spending rather than a multi-asset card.",
    availability: "The official FAQ states that residents aged 18+ in the European Economic Area can apply.",
    regions: ["European Economic Area"],
    pricing: "The official FAQ lists a €2.99 virtual-card opening fee and €29.99 physical-card opening fee, plus a 1% Bitcoin conversion fee and approximately 0.5% exchange spread.",
    rewards: "No universal cashback rate is stated on the reviewed product page.",
    funding: "On-chain Bitcoin, Lightning invoices or addresses, EUR to a personal vIBAN, or a self-custodial Lightning connection through NWC are described by the provider.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.wave.space/card",
    sourceLabel: "wavecard official product page",
    imageUrl: "https://cdn.prod.website-files.com/667823d9b944eb95404be544/69d83484ba0790b4b318abbf_Card%20Frozen.avif",
    imageAlt: "wavecard official Bitcoin card visual",
    imageSourceNote: "Official wave.space-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Verification is required for the personal vIBAN and Visa Bitcoin debit card. Bitcoin conversion and spread costs remain relevant even where FX is advertised at zero.",
    feesUrl: "https://www.wave.space/card",
    updateUrl: "https://www.wave.space/blog",
    updateLabel: "wave.space product updates",
    updateNote: "The provider page links current product posts about passkeys, MiCA, and Bitcoin spending; terms and EEA availability should be checked before applying.",
    applicationMethod: "Create a verified wave.space account, deposit or connect Bitcoin, and request the virtual or physical card offered in the EEA flow.",
    verification: "The provider states that verification is required to issue the personal vIBAN and Visa Bitcoin debit card.",
    featureTags: ["Bitcoin-only", "Lightning", "EEA", "Self-custody option"],
    pros: ["Bitcoin-only funding makes the product scope easy to understand", "Lightning and NWC wallet connections are documented", "Virtual and physical formats are listed"],
    cons: ["EEA-only eligibility is a major regional constraint", "Conversion fee and spread sit alongside the 0% FX headline", "Verification is required for the card and vIBAN"],
    noKycStatus: "not-verified",
  },
  {
    slug: "kripicard",
    name: "Kripicard",
    provider: "Kripicard",
    network: "Visa or Mastercard",
    categories: ["prepaid", "debit"],
    shortDescription: "Instant virtual Visa or Mastercard products funded with crypto, with no credit-check claim.",
    editorialSummary: "Kripicard markets virtual cards for online spending and says it does not require a credit check. Its compliance section separately describes identity verification, sanctions screening, and AML/CFT monitoring, so this is not a verified no-KYC product and should not be presented as anonymous.",
    bestFor: "Users comparing virtual crypto cards who need to distinguish no-credit-check marketing from identity and AML compliance.",
    availability: "The official site advertises 190+ countries, but country-specific eligibility and card BIN availability should be checked in the current onboarding flow.",
    regions: ["190+ countries advertised; verify current eligibility"],
    pricing: "Kripicard links a published fee schedule and fee calculator; the reviewed homepage emphasizes transparent fees but does not establish one universal price for every BIN or card route.",
    rewards: "No universal rewards rate is stated on the reviewed homepage.",
    funding: "USDT, USDC, BTC, ETH, and other supported assets are described as deposit options that convert into a spendable virtual-card balance.",
    cardFormats: ["Virtual Visa", "Virtual Mastercard"],
    sourceUrl: "https://home.kripicard.com/",
    sourceLabel: "Kripicard official homepage",
    imageUrl: "https://home.kripicard.com/kripicard-virtual-card-high-quality.png",
    imageAlt: "Kripicard black virtual card",
    imageSourceNote: "Official Kripicard-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "No credit check is not the same as no KYC. The provider describes identity verification, sanctions screening, and AML/CFT monitoring with regulated partners.",
    feesUrl: "https://home.kripicard.com/fees",
    updateUrl: "https://home.kripicard.com/news",
    updateLabel: "Kripicard updates",
    updateNote: "Kripicard maintains fee, supported-country, security, and resource pages; card BINs and regional access can change.",
    applicationMethod: "Create an account, review the provider’s fee and supported-country pages, complete the applicable onboarding, and issue a virtual card through the provider flow.",
    verification: "The site states no credit check but separately lists KYC/KYB, AML/CFT monitoring, and sanctions screening with regulated partners.",
    featureTags: ["Virtual", "USDT-funded", "No credit check", "Visa/Mastercard"],
    pros: ["Virtual card issuance is positioned as fast", "The site publishes a fee center and supported-country resource", "Multiple crypto deposit assets are described"],
    cons: ["The no-credit-check claim must not be confused with no KYC", "BIN, merchant, and regional eligibility can vary", "Virtual-only use cases may not suit in-person spending"],
    noKycStatus: "provider-claims-no-credit-check",
  },
  {
    slug: "bingcard",
    name: "BingCard",
    provider: "BingCard",
    network: "Visa or Mastercard",
    categories: ["prepaid", "debit"],
    shortDescription: "A virtual and physical crypto debit-card service whose official page states no photo ID or verified address for the stated flow.",
    editorialSummary: "BingCard is one of the few products in this research set whose official homepage explicitly states no photo ID and no verified proof of address for its stated onboarding flow. The same page adds an AML and regulatory caveat, so the no-KYC label must remain scoped to the provider’s wording and product route.",
    bestFor: "Readers researching privacy-oriented virtual card onboarding while accepting lower limits, compliance caveats, and provider risk.",
    availability: "The official page advertises international use and 190+ country coverage; confirm the current supported-country list and card route before funding.",
    regions: ["International; 190+ countries advertised"],
    pricing: "The official homepage advertises a 1% transaction fee. Card-tier issuance, top-up, ATM, and renewal terms should be confirmed in the provider’s Pricing and Terms pages.",
    rewards: "No universal cashback rate is stated on the reviewed homepage.",
    funding: "BTC, USDT, ETH, and USDC are listed as recharge assets for the virtual and physical card products.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.bingcard.com/",
    sourceLabel: "BingCard official homepage",
    imageUrl: "https://www.bingcard.com/_nuxt/virtual-crypto-card-header.CrOLq_o7.png",
    imageAlt: "BingCard virtual and physical crypto card products",
    imageSourceNote: "Official BingCard-hosted card product image",
    reviewedAt: "2026-08-27",
    caution: "The no-photo-ID and no-proof-of-address claims are explicitly subject to AML and regulatory requirements. Do not assume every card tier or transaction is verification-free.",
    feesUrl: "https://www.bingcard.com/pricing",
    updateUrl: "https://www.bingcard.com/faq",
    updateLabel: "BingCard pricing and FAQ",
    updateNote: "The provider maintains separate Pricing, FAQ, Terms, and Privacy pages; its onboarding claims and supported assets should be rechecked before use.",
    applicationMethod: "Open an account through the provider site, review the applicable AML/regulatory conditions, and select the virtual or physical product available to you.",
    verification: "The homepage states no photo ID and no verified proof of address for the stated flow, subject to AML and regulatory requirements.",
    featureTags: ["No photo ID stated", "No proof of address stated", "BTC/USDT/ETH/USDC", "Virtual + physical"],
    pros: ["The provider makes a specific privacy-oriented onboarding claim", "BTC, USDT, ETH, and USDC recharge options are shown", "Virtual and physical tiers are presented"],
    cons: ["AML and regulatory requirements still apply", "The homepage does not replace full fee and terms review", "International marketing does not guarantee eligibility in a particular country"],
    noKycStatus: "provider-states-no-kyc",
  },
  {
    slug: "kite-card",
    name: "Kite Card",
    provider: "Kite",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A non-custodial stablecoin Visa with instant virtual provisioning and app-based spending controls.",
    editorialSummary: "Kite presents its card as a stablecoin-to-fiat spending rail: USDC or USDT is converted at checkout and the purchase settles in USD. The official page lists a free virtual card, a 1.8% FX fee, a 0.53% top-up conversion fee, and physical cards as coming soon.",
    bestFor: "Users comparing a stablecoin-funded virtual card with a clearly stated conversion-cost structure.",
    availability: "Kite advertises use in 180+ countries; the exact application-country list and issuing-partner terms should be checked in the current flow.",
    regions: ["180+ countries advertised; verify country eligibility"],
    pricing: "The official page lists $0 annual, virtual-card, and replacement fees, with a 1.8% FX fee and 0.53% top-up conversion fee. A physical card is marked coming soon.",
    rewards: "No universal cashback rate is stated on the reviewed official card page.",
    funding: "USDC or USDT is deposited to the Kite wallet and auto-converted at checkout; the provider describes the wallet software as non-custodial.",
    cardFormats: ["Virtual", "Physical coming soon"],
    sourceUrl: "https://www.kiteapp.xyz/spend",
    sourceLabel: "Kite Spend product page",
    imageUrl: "https://www.kiteapp.xyz/og-image.png?v=2",
    imageAlt: "Kite stablecoin card official product visual",
    imageSourceNote: "Official Kite-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Kite says card issuance is provided by licensed third-party partners. Confirm country, issuer, limits, conversion, and verification terms before funding.",
    feesUrl: "https://www.kiteapp.xyz/spend",
    updateUrl: "https://www.kiteapp.xyz/spend",
    updateLabel: "Kite card terms",
    updateNote: "The official Spend page publishes the current fee summary and card-format status; supported countries and issuing terms can change.",
    applicationMethod: "Download the Kite app, complete verification, review the available card route for your country, and fund the wallet with supported stablecoins.",
    verification: "Kite states that the virtual card is provisioned after verification; country and provider onboarding requirements apply.",
    featureTags: ["Non-custodial wallet", "USDC/USDT", "1.8% FX listed", "Virtual"],
    pros: ["The official page separates FX and top-up conversion fees", "Virtual-card provisioning and spending controls are described", "The provider frames the wallet as non-custodial"],
    cons: ["Physical card is not yet available on the reviewed page", "FX and top-up fees remain part of the spending cost", "Issuer and country terms are partner- and jurisdiction-dependent"],
  },
  {
    slug: "defi-com-card",
    name: "DeFi.com Card",
    provider: "DeFi.com",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A pre-launch Visa card concept connected to DeFi.com’s self-custodial account and waitlist.",
    editorialSummary: "DeFi.com describes a private account for holding, sending, spending, and growing money, with virtual and physical card plans. The official page is still an early-access and waitlist experience, so fees, issuer details, limits, and final availability should not be treated as settled product terms.",
    bestFor: "Readers tracking an upcoming self-custody card rather than applying to a fully documented live product.",
    availability: "The official page markets global use but says products and features may be region-dependent; the card is presented through an early-access flow.",
    regions: ["Global marketing; pre-launch and region-dependent"],
    pricing: "No complete issuance, monthly, FX, ATM, or conversion fee schedule is published on the reviewed official page.",
    rewards: "The site discusses earning and yields, but no universal card-reward schedule is published.",
    funding: "DeFi.com describes a self-custodial account that can move between fiat and crypto before spending; the final card funding mechanics remain subject to launch terms.",
    cardFormats: ["Virtual planned", "Physical planned"],
    sourceUrl: "https://defi.com/",
    sourceLabel: "DeFi.com official homepage",
    imageUrl: "https://defi.com/og-image.jpg",
    imageAlt: "DeFi.com Visa card and account dashboard official visual",
    imageSourceNote: "Official DeFi.com-hosted social product image",
    reviewedAt: "2026-08-27",
    caution: "This is a pre-launch listing. Do not assume that advertised privacy, yields, fees, issuer arrangements, availability, or card benefits are final.",
    feesUrl: "https://defi.com/",
    updateUrl: "https://defi.com/",
    updateLabel: "DeFi.com early-access page",
    updateNote: "The official page is the current public source for the waitlist and planned card model; product terms may change before launch.",
    applicationMethod: "Join the official early-access flow and wait for the provider to publish the final eligibility, verification, pricing, and card terms.",
    verification: "The final verification process is not fully published; regional eligibility and onboarding requirements will apply if the card launches.",
    featureTags: ["Pre-launch", "Self-custody", "Visa", "Virtual + physical planned"],
    pros: ["The official site clearly labels the product as early access", "Virtual and physical card plans are described", "Self-custody and privacy infrastructure are central to the product concept"],
    cons: ["No complete public fee schedule", "Issuer, limits, and country list are not fully disclosed", "Final card features and availability may change before launch"],
  },
  {
    slug: "western-union-stablecard",
    name: "Western Union Stablecard",
    provider: "Western Union",
    network: "Visa",
    categories: ["debit"],
    shortDescription: "A Visa spending card secured by USDPT collateral and managed through the Stablecard mobile app.",
    editorialSummary: "Western Union’s Stablecard connects a USDPT digital dollar wallet with Visa spending and cash access. The official page says it is not a bank account or prepaid card, and identifies Rain as the card issuer/program manager and Anchorage Digital Bank as the USDPT issuer.",
    bestFor: "Readers comparing a stablecoin-collateralized Visa product from a large remittance brand.",
    availability: "The provider says availability is subject to geographic, regulatory, and eligibility requirements and is accessed through the mobile app.",
    regions: ["Geographic and regulatory eligibility applies"],
    pricing: "The official page describes no credit check, no minimum balance, and no hidden fees, but does not publish one complete card fee schedule in the reviewed material.",
    rewards: "No universal cashback or card-reward rate is stated on the reviewed official page.",
    funding: "Deposit USDPT into the non-custodial digital-asset wallet associated with the card; available spending is limited to the collateral value.",
    cardFormats: ["Virtual"],
    sourceUrl: "https://www.westernunion.com/global/en/digital-assets-stablecard.html",
    sourceLabel: "Western Union Stablecard product page",
    imageUrl: "https://www.westernunion.com/content/dam/wu/logo/logo.wu.big.svg",
    imageAlt: "Western Union official logo for Stablecard listing",
    imageSourceNote: "Official Western Union-hosted logo; public product page did not expose a separate card artwork URL",
    reviewedAt: "2026-08-27",
    caution: "This is a collateralized spending product, not a bank account or FDIC-insured deposit account. Confirm the app’s current fees, issuer terms, and eligibility.",
    feesUrl: "https://www.westernunion.com/global/en/digital-assets-stablecard.html",
    updateUrl: "https://www.westernunion.com/global/en/digital-assets-stablecard.html",
    updateLabel: "Stablecard official FAQs",
    updateNote: "Western Union publishes the current product explanation and FAQs on its digital-assets page; USDPT, issuer, and market-access details can change.",
    applicationMethod: "Download the Stablecard app, review the country and eligibility prompts, complete onboarding, and deposit the supported USDPT collateral.",
    verification: "App onboarding, geographic eligibility, and regulatory requirements apply; the official page does not promise a verification-free route.",
    featureTags: ["USDPT collateral", "Visa", "Rain issuer", "Solana"],
    pros: ["The provider explains the collateral model and issuer relationships", "The card combines spending with Western Union cash-access messaging", "USDPT and Visa use cases are described on an official page"],
    cons: ["Spending is limited by deposited collateral", "The product is not a bank account or prepaid card", "A complete public fee and limits table was not visible"],
  },
  {
    slug: "privacy-gateway-card",
    name: "Privacy Gateway Card",
    provider: "Privacy Gateway",
    network: "Visa",
    categories: ["prepaid", "debit"],
    shortDescription: "A virtual Visa card marketed around name-and-email onboarding, crypto reloads, and Google Pay.",
    editorialSummary: "Privacy Gateway’s official page presents a virtual Visa card with a $5 monthly promotional price, 3.5% reload fee, Google Pay support, and a one-way crypto-to-card-balance conversion model. Its access-hash recovery model and compliance caveats are as important as the no-ID marketing claim.",
    bestFor: "Readers researching a virtual card with provider-stated minimal onboarding and explicit reload-cost trade-offs.",
    availability: "The provider markets worldwide Visa use but states that individual merchants and country rules can still decline transactions.",
    regions: ["Global marketing; merchant and country restrictions apply"],
    pricing: "$5/month promotional pricing is shown for 2026, with a 3.5% fee on reloads; other card, ATM, and subscription terms should be checked in the current page.",
    rewards: "No cashback, yield, or rewards programme is stated on the reviewed official page.",
    funding: "The provider lists BTC, LTC, SOL, ZANO, USDT, USDC, and other crypto reload routes; conversion into the card balance is described as one-way.",
    cardFormats: ["Virtual"],
    sourceUrl: "https://privacygateway.io/",
    sourceLabel: "Privacy Gateway official card page",
    imageUrl: "https://privacygateway.io/favicon.ico",
    imageAlt: "Privacy Gateway official card-service logo",
    imageSourceNote: "Official Privacy Gateway-hosted logo asset; the product page supplies the card presentation",
    reviewedAt: "2026-08-27",
    caution: "The provider’s no-ID claim is not a promise of anonymity or permanent exemption from AML, sanctions, regulatory, merchant, or transaction controls. The access hash may be unrecoverable if lost.",
    feesUrl: "https://privacygateway.io/",
    updateUrl: "https://privacygateway.io/",
    updateLabel: "Privacy Gateway card terms",
    updateNote: "The provider page publishes the current promotional subscription, reload fee, card behavior, and merchant examples; terms can change.",
    applicationMethod: "Review the provider’s terms and onboarding disclosure, create the required account identifier, and fund only after understanding the one-way conversion and recovery model.",
    verification: "The provider states that name and email are the minimum for its advertised route; AML and regulatory requirements can still apply.",
    featureTags: ["Provider states no ID", "Google Pay", "3.5% reload fee", "Virtual Visa"],
    pros: ["The provider publishes specific reload and subscription figures", "Google Pay and 3DS flows are described", "Multiple crypto funding options are listed"],
    cons: ["Reload fees can materially increase total spending cost", "Conversion into the card balance is described as one-way", "Access-hash loss may mean permanent loss of account access"],
    noKycStatus: "provider-states-no-kyc",
  },
  {
    slug: "peanut-card",
    name: "Peanut Card",
    provider: "Peanut",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A beta Visa card connected to Peanut’s non-custodial smart-account and stablecoin payment ecosystem.",
    editorialSummary: "Peanut separates its no-mandatory-KYC core wallet functions from its card programme. The official site says cardholders must verify, the card is rolling out through a beta/waitlist, and the broader app connects crypto rails with local payment partners.",
    bestFor: "Readers comparing a cross-border wallet ecosystem with a card that is still in gradual beta rollout.",
    availability: "Peanut advertises 140+ countries and a gradual card rollout; exact card eligibility, issuer, and country availability require a current waitlist check.",
    regions: ["140+ countries advertised; beta and country rollout apply"],
    pricing: "The official site states no monthly or annual card fee and says standard fees and limits apply under cardholder terms.",
    rewards: "The provider describes a possible $10 welcome programme after verification and $100 of card spend; eligibility and terms apply.",
    funding: "The card is described as stablecoin-funded through the non-custodial Peanut wallet; supported routes include EVM networks, Solana, Tron, and selected bank/local payment rails.",
    cardFormats: ["Virtual beta"],
    sourceUrl: "https://peanut.me/",
    sourceLabel: "Peanut official homepage",
    imageUrl: "https://peanut.me/metadata-img.png",
    imageAlt: "Peanut Card official product visual",
    imageSourceNote: "Official Peanut-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Peanut’s core wallet can have different onboarding from the card programme. The card requires verification and is in beta; issuer and cardholder terms should be confirmed.",
    feesUrl: "https://peanut.me/",
    updateUrl: "https://peanut.me/",
    updateLabel: "Peanut card and waitlist",
    updateNote: "Peanut’s homepage currently separates core wallet functionality from the beta card programme; rollout, welcome rewards, and supported rails can change.",
    applicationMethod: "Open the Peanut card flow, confirm whether the beta programme is available to your country, complete verification, and review cardholder terms before funding.",
    verification: "The official site states verification is required for all cardholders; separate core wallet functions may have different onboarding.",
    featureTags: ["Beta programme", "Non-custodial", "Stablecoin funding", "140+ countries advertised"],
    pros: ["The provider clearly distinguishes wallet and card onboarding", "Non-custodial smart-account architecture is described", "Cross-border payment rails and local partners are visible"],
    cons: ["The card is a gradual beta rollout", "Issuer and complete cardholder terms were not visible on the reviewed page", "The welcome programme is conditional and not a universal cashback rate"],
  },
  {
    slug: "paybis-card",
    name: "Paybis Card",
    provider: "Paybis",
    network: "Not disclosed",
    categories: ["debit"],
    shortDescription: "A planned Paybis card and IBAN feature currently shown as coming soon alongside the Paybis crypto platform.",
    editorialSummary: "Paybis is an established crypto on-ramp and wallet brand, but the official homepage still presents its card and IBAN features as coming soon. This profile keeps the future product visible for research while separating current exchange functionality from unlaunched card terms.",
    bestFor: "Readers monitoring a forthcoming card from a familiar crypto on-ramp rather than seeking a currently documented card product.",
    availability: "The official page markets Paybis services across 180+ countries, but the card itself is shown as coming soon and may have separate regional eligibility.",
    regions: ["Paybis platform advertises 180+ countries; card rollout not yet established"],
    pricing: "Card issuance, subscription, FX, ATM, and conversion fees are not published for the coming-soon card.",
    rewards: "Card rewards are not published; cashback is shown as to be announced on the reviewed directory source.",
    funding: "The current Paybis platform supports card, bank, and wallet crypto purchases; the future card’s funding route is not yet fully specified.",
    cardFormats: ["Virtual coming soon", "Physical coming soon"],
    sourceUrl: "https://paybis.com/",
    sourceLabel: "Paybis official homepage",
    imageUrl: "https://paybis.com/resources/social-preview.v2.png",
    imageAlt: "Paybis official product and wallet visual",
    imageSourceNote: "Official Paybis-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "The card is not presented as live on the reviewed official page. The supplied partner link may lead to Paybis’s current crypto-buy flow rather than a card application.",
    referralUrl: "https://buy.paybis.com/click?pid=193&offer_id=1&l=1718367827",
    referralLabel: "Explore Paybis",
    feesUrl: "https://paybis.com/",
    updateUrl: "https://paybis.com/",
    updateLabel: "Paybis product updates",
    updateNote: "Paybis currently labels the card and IBAN feature as coming soon; use the official page to distinguish current exchange fees from future card pricing.",
    applicationMethod: "Review the current Paybis platform and card announcement, then wait for the provider to publish the card’s final eligibility, verification, pricing, and application route.",
    verification: "Paybis describes account verification for its current platform; final card verification requirements are not yet fully published.",
    featureTags: ["Coming soon", "Paybis wallet", "180+ countries platform", "Card terms pending"],
    pros: ["The provider clearly labels the card as forthcoming", "Paybis already publishes wallet and crypto purchase infrastructure", "The official page links current compliance and fee resources"],
    cons: ["The card is not yet documented as live", "No card fee, limit, issuer, or reward table", "The supplied affiliate CTA may not be a card-specific route"],
  },
  {
    slug: "blofin-card",
    name: "BloFin Wallet Card",
    provider: "BloFin Wallet",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A Visa card inside BloFin Wallet that can use USDT or USDC from a self-custodial wallet.",
    editorialSummary: "BloFin separates its self-custody wallet from its exchange and places the card inside the wallet app. The official page describes USDT/USDC funding, Apple Pay and Google Pay, region restrictions, fees shown before confirmation, and physical cards coming soon.",
    bestFor: "Self-custody users comparing an in-app Visa with explicit separation between wallet and exchange custody.",
    availability: "The official page says Visa cards are available in certain countries and regions; exact country access is shown in the app.",
    regions: ["Selected countries and regions; verify in the app"],
    pricing: "BloFin says card-deposit service fees are shown before confirmation; no single universal issuance or monthly schedule is published on the reviewed page.",
    rewards: "No universal cashback rate is stated on the reviewed official wallet page.",
    funding: "Fund the card with USDT or USDC from BloFin Wallet; supported networks, deposits, and on-chain gas costs remain route-dependent.",
    cardFormats: ["Virtual", "Physical coming soon"],
    sourceUrl: "https://wallet.blofin.com/en",
    sourceLabel: "BloFin Wallet official card page",
    imageUrl: "https://wallet.blofin.com/images/home/features/card-new.webp",
    imageAlt: "BloFin Wallet official product visual",
    imageSourceNote: "Official BloFin Wallet-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "BloFin Wallet is separate from BloFin Exchange. Self-custody does not remove card issuer, network, conversion, region, or loss-of-access risks.",
    referralUrl: "https://blofin.com/register?referral_code=dPCaMa",
    referralLabel: "Explore BloFin Wallet",
    feesUrl: "https://wallet.blofin.com/en",
    updateUrl: "https://wallet.blofin.com/en",
    updateLabel: "BloFin Wallet card details",
    updateNote: "The official wallet page states that card fees appear before confirmation and that card availability is region-restricted; physical-card timing can change.",
    applicationMethod: "Install BloFin Wallet, create or import the self-custody wallet, check card availability in the app, complete onboarding, and fund with a supported stablecoin.",
    verification: "The provider says card features are region-restricted and onboarding requirements apply; the exact in-app verification flow should be checked.",
    featureTags: ["Self-custody wallet", "USDT/USDC", "Apple Pay", "Physical coming soon"],
    pros: ["The provider documents wallet-versus-exchange custody differences", "USDT and USDC card funding are clearly stated", "Apple Pay and Google Pay are listed"],
    cons: ["The card is region-restricted", "Physical card availability is still coming soon", "Exact card fees and limits are shown contextually rather than in one public table"],
  },
  {
    slug: "whop-card",
    name: "Whop Business Card",
    provider: "Whop",
    network: "Visa",
    categories: ["dual-mode"],
    shortDescription: "A secured business Visa card that uses crypto collateral and has category-specific cashback terms.",
    editorialSummary: "Whop’s product is not a conventional debit card: its terms describe a secured credit card for business spending, with crypto collateral and liquidation risk. The provider advertises 0% APR currently and up to 5% cashback only for selected Whop Ads, Content Rewards, and Uber categories.",
    bestFor: "Business users who understand collateral-backed credit and want to compare Whop-specific spending rewards.",
    availability: "Whop markets the product broadly, but business eligibility, KYC, collateral, issuer, and regional terms apply.",
    regions: ["Global marketing; business and regional eligibility apply"],
    pricing: "The provider does not disclose a universal issuance fee in the reviewed public page; non-USD spending may involve FX and cross-border costs.",
    rewards: "Up to 5% cashback is described for selected business categories, with a $50,000 monthly cap in the reviewed product material; other spending may earn 0%.",
    funding: "Provide supported crypto collateral, then spend through the secured Visa card; crypto is not simply a debit balance and may be liquidated under the card terms.",
    cardFormats: ["Business secured credit"],
    sourceUrl: "https://whop.com/network/products/business-cards/",
    sourceLabel: "Whop Business Card product page",
    imageUrl: "https://whop.com/_static/network/business-cards/og.png",
    imageAlt: "Whop Business Card official product visual",
    imageSourceNote: "Official Whop-hosted card product image",
    reviewedAt: "2026-08-27",
    caution: "This is a secured credit product. Crypto collateral can be liquidated under the terms, and 0% APR or cashback figures are conditional and changeable.",
    feesUrl: "https://whop.com/network/products/business-cards/",
    updateUrl: "https://whop.com/network/products/business-cards/",
    updateLabel: "Whop card terms",
    updateNote: "Whop’s business-card page and terms distinguish credit, collateral, category rewards, FX, and issuer conditions; review the current agreement before use.",
    applicationMethod: "Create or sign in to an eligible Whop business account, complete KYC, review the secured-card agreement, and provide the required collateral.",
    verification: "Whop requires KYC and sufficient crypto collateral for the secured business card; final approval and terms apply.",
    featureTags: ["Secured credit", "Crypto collateral", "Visa", "Up to 5% selected categories"],
    pros: ["The provider distinguishes the product from a debit card", "Category-specific cashback and cap language is visible", "The card is designed for business spending"],
    cons: ["Collateral can be liquidated", "Selected categories do not represent universal cashback", "FX, limits, and issuer terms need careful agreement review"],
  },
  {
    slug: "mexc-card",
    name: "MEXC Card",
    provider: "MEXC",
    network: "Visa",
    categories: ["prepaid", "debit"],
    shortDescription: "A region-specific MEXC Visa spending product with Advanced KYC, deposit activation, and tiered cashback marketing.",
    editorialSummary: "MEXC presents several card routes and regional variants rather than one universal product. Its current official page shows an issuance-fee display, Google Pay, Advanced KYC, deposit activation, and cashback marketing of up to 10%, while the country selector and terms control who can actually apply.",
    bestFor: "MEXC users comparing a region-specific crypto spending route with published reward tiers.",
    availability: "The official page visibly lists the Philippines, Taiwan, Vietnam, and other country routes; exact product availability depends on the selected region.",
    regions: ["Selected countries including Philippines, Taiwan, and Vietnam; verify route"],
    pricing: "The current page displays a card-issuance figure of 20 USD crossed out to 0 USD for the shown route; spending, conversion, FX, and physical-card fees require regional confirmation.",
    rewards: "MEXC advertises up to 10% cashback, with tier, spending, cap, and eligible-transaction conditions.",
    funding: "Apply, complete Advanced KYC, deposit to activate, and add the card to Apple or Google Wallet; supported assets and regional funding routes vary.",
    cardFormats: ["Virtual", "Physical availability varies"],
    sourceUrl: "https://www.mexc.com/buy-crypto/mexc-card",
    sourceLabel: "MEXC Card official product page",
    imageUrl: "https://static.mocortech.com/otc/static-assets/mexc-card-v2/banner-poster-pc-start.png",
    imageAlt: "MEXC Visa Card official product banner",
    imageSourceNote: "Official MEXC-hosted card banner",
    reviewedAt: "2026-08-27",
    caution: "MEXC presents multiple regional card variants. Do not combine the Taiwan route and other MEXC or Ether.fi routes into one universal fee, reward, or eligibility claim.",
    referralUrl: "https://www.mexc.com/register?inviteCode=mexc-1EoKR",
    referralLabel: "Explore MEXC Card",
    feesUrl: "https://www.mexc.com/support/fiat/card",
    updateUrl: "https://www.mexc.com/buy-crypto/mexc-card",
    updateLabel: "Latest MEXC Card terms",
    updateNote: "MEXC publishes country selection, card application, cashback, and support information on its card page; regional terms can change.",
    applicationMethod: "Open the MEXC card flow, select the available country route, complete Advanced KYC, deposit as instructed, and verify the current card terms.",
    verification: "Advanced KYC is required on the official application flow; country and account eligibility apply.",
    featureTags: ["Advanced KYC", "Google Pay", "Up to 10% advertised", "Region-specific"],
    pros: ["The official flow shows a clear application sequence", "Google Pay support is documented", "Regional product variants and cashback conditions are visible"],
    cons: ["Country selection materially changes the product", "Reward rates are tiered and conditional", "Fees beyond the displayed issuance promotion need regional review"],
  },
  {
    slug: "swissborg-card",
    name: "SwissBorg Card",
    provider: "SwissBorg",
    network: "Mastercard",
    categories: ["debit"],
    shortDescription: "A virtual Mastercard that converts supported crypto to local currency at payment and pays BORG rewards by loyalty rank.",
    editorialSummary: "SwissBorg connects a virtual Mastercard to its app and crypto wallets. The official page lists 30+ regions, including the EEA, UK, and Switzerland, and describes real-time conversion, wallet-only funding, Apple Pay, Google Pay, Curve, and BORG rewards tied to loyalty rank.",
    bestFor: "European users comparing a crypto-wallet Mastercard with in-app conversion and loyalty-linked rewards.",
    availability: "The official page says the card is available for residents in 30+ regions, including the EEA, United Kingdom, and Switzerland; exact country access applies.",
    regions: ["EEA, United Kingdom, Switzerland, and other selected regions"],
    pricing: "SwissBorg says there are no service or annual fees, but crypto-to-fiat conversion fees apply; the current pricing policy controls the details.",
    rewards: "BORG rewards are described as cashback based on loyalty rank; the rate and eligible assets are not a universal guaranteed return.",
    funding: "Hold supported crypto in the SwissBorg wallet, choose a primary and backup spending asset, and allow real-time conversion into EUR, CHF, or GBP.",
    cardFormats: ["Virtual"],
    sourceUrl: "https://swissborg.com/crypto-debit-card",
    sourceLabel: "SwissBorg Card official page",
    imageUrl: "https://cdn.sanity.io/images/bor5n0ip/production/4165f0cfd8923e4820b6aeb78c7b1f1acec765a7-2400x1260.png?w=1200&h=630&fm=jpg&q=85&fit=crop&auto=format",
    imageAlt: "SwissBorg crypto debit card official product visual",
    imageSourceNote: "Official SwissBorg-hosted Sanity product image",
    reviewedAt: "2026-08-27",
    caution: "The card is virtual on the reviewed page, conversion fees apply, and BORG rewards depend on loyalty rank. Confirm the current country, fee, and supported-asset terms.",
    feesUrl: "https://swissborg.com/fees",
    updateUrl: "https://swissborg.com/crypto-debit-card",
    updateLabel: "SwissBorg card updates",
    updateNote: "SwissBorg maintains card FAQs, fees, supported-currency, and regional information; physical-card plans and card access can change.",
    applicationMethod: "Create or sign in to an eligible SwissBorg retail account, complete Level 2 identity verification, and activate the card in the app if your country is supported.",
    verification: "The official FAQ states that a retail account, KYC Level 2, verified photo ID and address, and eligible residence are required.",
    featureTags: ["Mastercard", "EEA/UK/Switzerland", "Real-time conversion", "BORG rewards"],
    pros: ["The provider documents primary and backup spending assets", "Apple Pay, Google Pay, and Curve support are listed", "The official page clearly separates conversion fees from annual fees"],
    cons: ["Virtual-only on the reviewed page", "Rewards depend on loyalty rank and are paid in BORG", "Card access and supported currencies vary by residence"],
  },
  {
    slug: "dogpay-card",
    name: "DogPay Card",
    provider: "DogPay",
    network: "Visa",
    categories: ["debit", "prepaid"],
    shortDescription: "Virtual and physical Visa card options funded with stablecoins and managed through the DogPay app.",
    editorialSummary: "DogPay’s official card page separates virtual online spending from physical-card POS and supported ATM use. It describes USDT-network funding, mobile wallets, card controls, identity checks, and region-dependent availability, while the public page does not expose a complete universal price table.",
    bestFor: "Users comparing a stablecoin-funded card with both online and physical spending paths.",
    availability: "DogPay describes global payment scenarios, but individual availability depends on region, identity verification, account review, and the issuing partner.",
    regions: ["Global marketing; provider, issuer, and regional eligibility apply"],
    pricing: "The reviewed official card page does not show a complete issuance, monthly, FX, ATM, or top-up fee table; confirm the current plan and card terms in the application.",
    rewards: "No universal cashback rate is stated on the reviewed official card page.",
    funding: "Use a supported USDT network, convert and fund the card in the DogPay app, then spend online, at POS, or at supported ATMs.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://dogpay.com/us/cards",
    sourceLabel: "DogPay official card page",
    imageUrl: "https://dogpay.com/images/cards/hero/hero-visual.webp",
    imageAlt: "DogPay virtual and physical card official product visual",
    imageSourceNote: "Official DogPay-hosted card visual",
    reviewedAt: "2026-08-27",
    caution: "DogPay is custodial for card funding on the reviewed product model. KYC, issuer rules, balance, limits, merchants, and region can affect use.",
    feesUrl: "https://dogpay.com/us/cards",
    updateUrl: "https://dogpay.com/us/card-program-terms",
    updateLabel: "DogPay card terms",
    updateNote: "DogPay publishes separate card, help-center, and programme-terms pages; plan prices, top-up fees, limits, and availability should be rechecked.",
    applicationMethod: "Open the DogPay account flow, complete identity verification and account review, check card availability, and fund with a supported USDT route.",
    verification: "The official page states that identity checks and risk controls apply; region and issuing-partner approval also matter.",
    featureTags: ["Virtual + physical", "USDT funding", "Apple/Google Pay", "Supported ATMs"],
    pros: ["The official page explains online, POS, mobile-wallet, and ATM scenarios", "USDT funding steps are visible", "Card controls and transaction history are described"],
    cons: ["A complete public fee table was not visible", "Custodial card funding adds platform and account risk", "Physical and ATM access depend on region and issuer"],
  },
  {
    slug: "tevau-card",
    name: "Tevau Card",
    provider: "Tevau",
    network: "Visa",
    categories: ["debit", "prepaid"],
    shortDescription: "Virtual and physical Visa cards that auto-convert digital assets into local currency for spending and withdrawals.",
    editorialSummary: "Tevau positions its card around digital-asset funding, Visa spending, ATM access, and Apple Pay or Google Pay. The official page explains virtual versus physical use and verification, while the exact card fees, limits, and country rollout remain terms-and-application questions.",
    bestFor: "Users comparing a crypto-funded Visa with both virtual subscription spending and physical ATM use.",
    availability: "The provider markets global Visa use, but card availability and services depend on the applicable Tevau entity, country, verification, and local restrictions.",
    regions: ["Global marketing; entity and country eligibility apply"],
    pricing: "The reviewed official card page does not publish a complete universal issuance, monthly, FX, ATM, or conversion fee schedule.",
    rewards: "No universal cashback or reward rate is stated on the reviewed official card page.",
    funding: "Deposit digital assets to the Tevau wallet; the provider says funds are available instantly and auto-converted to local currency at the point of sale or withdrawal.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://tevau.io/en/card/",
    sourceLabel: "Tevau official card page",
    imageUrl: "https://tevau.io/og-card.png",
    imageAlt: "Tevau Visa card official product visual",
    imageSourceNote: "Official Tevau-hosted card image",
    reviewedAt: "2026-08-27",
    caution: "Tevau lists different legal entities and regulated-service descriptions. Confirm the applicable entity, country access, fee schedule, verification, and cardholder terms.",
    referralUrl: "https://tevau.io/invite_registration/#/?inviteCode=307920",
    referralLabel: "Explore Tevau Card",
    feesUrl: "https://tevau.io/en/terms_conditions",
    updateUrl: "https://tevau.io/en/card/",
    updateLabel: "Tevau card details",
    updateNote: "Tevau’s official card page separates virtual and physical features and links privacy and terms pages; pricing and rollout can change by entity and country.",
    applicationMethod: "Open the Tevau application, complete verification, choose the virtual or physical route available to your address, and review the current terms before funding.",
    verification: "The official flow begins with sign-up and verification; entity, country, and card eligibility requirements apply.",
    featureTags: ["Visa", "Virtual + physical", "Auto-conversion", "ATM access advertised"],
    pros: ["Virtual and physical use cases are clearly separated", "Apple Pay and Google Pay are listed", "The provider explains point-of-sale auto-conversion"],
    cons: ["A complete public fee schedule was not visible", "Global marketing does not guarantee country eligibility", "Applicable entity and issuer terms require review"],
  },
  {
    slug: "bydfi-card",
    name: "BYDFi Card",
    provider: "BYDFi",
    network: "Visa",
    categories: ["debit", "prepaid"],
    shortDescription: "A virtual Visa debit card with USDT funding, a $1 monthly fee, and no ATM support for the virtual product.",
    editorialSummary: "BYDFi publishes an unusually specific card FAQ: issuance is listed at 0 USDT, the monthly fee at $1 unless waived under stated VIP conditions, crypto conversion at 1%, and non-USD FX at 1%. The virtual card accepts USDT transfers and works with payment services such as Google Pay and PayPal.",
    bestFor: "Readers who want a virtual Visa with a public fee and limits FAQ to inspect before applying.",
    availability: "BYDFi card access depends on account level, country exclusions, verification, and provider approval; the official FAQ links a current unsupported-country list.",
    regions: ["Country-dependent; consult BYDFi’s unsupported-country list"],
    pricing: "The official FAQ lists 0 USDT issuance, a $1 monthly fee per card, 1% crypto conversion in, 1% non-USD FX, and a 50 USDT refund-handling fee.",
    rewards: "No universal cashback rate is stated in the reviewed official card FAQ.",
    funding: "Only USDT transfers to the card account are currently described; convert crypto to USDT first, then move it into the card wallet.",
    cardFormats: ["Virtual"],
    sourceUrl: "https://www.bydfi.com/en/support/PRODUCT_DESCRIPTION/articles/eey3ixlsr6pq",
    sourceLabel: "BYDFi Card official FAQ",
    imageUrl: "https://uploads.bydfi.in/events/cms/BYD.1762759775093.image.png",
    imageAlt: "BYDFi Card official product visual",
    imageSourceNote: "Official BYDFi-hosted card image",
    reviewedAt: "2026-08-27",
    caution: "The monthly fee can continue while a card is frozen, and virtual cards do not support ATM withdrawals. Verify country, VIP, balance, 3DS, billing-address, and limit rules.",
    referralUrl: "https://partner.bydfi.com/j/jO7nayOF",
    referralLabel: "Explore BYDFi Card",
    feesUrl: "https://www.bydfi.com/en/support/PRODUCT_DESCRIPTION/articles/eey3ixlsr6pq",
    updateUrl: "https://www.bydfi.com/en/support/PRODUCT_DESCRIPTION/articles/grvjerzcc8bu?title=BYDFi+Card+Terms+of+Use",
    updateLabel: "BYDFi Card terms",
    updateNote: "BYDFi maintains a detailed card FAQ, terms of use, transaction FAQ, and unsupported-country list; fees and eligibility can change.",
    applicationMethod: "Create or sign in to BYDFi, complete the applicable verification and account checks, review country support, then activate the virtual card and transfer USDT.",
    verification: "Account, country, billing-address, 3DS, VIP, and provider eligibility conditions apply; the official FAQ does not describe a verification-free route.",
    featureTags: ["Virtual Visa", "$1 monthly fee", "1% conversion", "USDT funding"],
    pros: ["The official FAQ gives a concrete fee breakdown", "Virtual activation is described as instant", "Google Pay, PayPal, and POS compatibility are listed"],
    cons: ["Only USDT card-account transfers are described", "Virtual cards cannot be used at ATMs", "Monthly fees and cancellation rules require ongoing balance and account review"],
  },
];

export function getCardBySlug(slug: string) {
  return cardListings.find((card) => card.slug === slug);
}

export const cardCategories: { value: "all" | CardCategory; label: string }[] = [
  { value: "all", label: "All approaches" },
  { value: "prepaid", label: "Prepaid" },
  { value: "debit", label: "Debit" },
  { value: "dual-mode", label: "Dual-mode" },
  { value: "self-custody", label: "Self-custody" },
];
