export type CardCategory = "prepaid" | "debit" | "dual-mode" | "self-custody";

export type CardListing = {
  slug: string;
  name: string;
  provider: string;
  network: string;
  categories: CardCategory[];
  shortDescription: string;
  editorialSummary: string;
  bestFor: string;
  availability: string;
  regions: string[];
  pricing: string;
  rewards: string;
  funding: string;
  cardFormats: string[];
  sourceUrl: string;
  sourceLabel: string;
  imageUrl: string;
  imageAlt: string;
  imageSourceNote: string;
  reviewedAt: string;
  caution: string;
  referralUrl?: string;
  referralLabel?: string;
  feesUrl?: string;
  updateUrl?: string;
  updateLabel?: string;
  updateNote?: string;
  applicationMethod?: string;
  verification?: string;
  galleryImages?: { url: string; alt: string; source: string }[];
};

export const cardListings: CardListing[] = [
  {
    slug: "coinbase-card",
    name: "Coinbase Card",
    provider: "Coinbase",
    network: "Visa",
    categories: ["prepaid", "debit"],
    shortDescription: "A US-focused Visa prepaid debit card that converts crypto to USD when you spend.",
    editorialSummary: "Coinbase positions this card as a bridge between a Coinbase balance and everyday Visa purchases. The important detail is that crypto is converted to USD for spending; the reward rate is an optional, variable US offer rather than a permanent universal rate.",
    bestFor: "People who already use Coinbase and want a familiar cash-or-crypto spending rail.",
    availability: "United States; Coinbase says all states except Hawaii on the reviewed page.",
    regions: ["United States"],
    pricing: "No Coinbase transaction fees or annual fee are advertised on the reviewed page; a spread may apply when crypto is bought, sold, or traded.",
    rewards: "Optional crypto rewards for eligible US card users; the rate is variable and should be checked in the Coinbase app.",
    funding: "Coinbase balance, bank account funding, or eligible paycheck deposit; crypto is converted to USD for purchases and ATM withdrawals.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.coinbase.com/card",
    sourceLabel: "Coinbase Card product page",
    imageUrl: "https://images.ctfassets.net/o10es7wu5gm1/4AsEsKXTMmSVky9wG1MNqM/1ceaf6ca937f526948ea3b909edb2e71/landing_hero_white_bg.png",
    imageAlt: "Blue Coinbase Visa debit card on a white background",
    imageSourceNote: "Official Coinbase-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Eligibility, limits, rewards, and account verification requirements apply. This is not a credit card recommendation.",
  },
  {
    slug: "crypto-com-visa-card",
    name: "Crypto.com Visa Card",
    provider: "Crypto.com",
    network: "Visa",
    categories: ["prepaid"],
    shortDescription: "A prepaid Visa card with tiered CRO rewards, subscription options, or CRO lockup requirements.",
    editorialSummary: "Crypto.com publishes multiple card tiers rather than one flat product. The cost-and-benefit trade-off depends on the selected tier, CRO subscription or lockup route, reward caps, ATM allowance, and the country-specific cardholder agreement.",
    bestFor: "Users comparing a tiered prepaid card model and willing to read the current regional terms.",
    availability: "Jurisdiction-dependent; Crypto.com publishes separate regional disclosures.",
    regions: ["United States", "Europe", "Canada", "Australia", "Brazil", "Singapore", "United Kingdom"],
    pricing: "The reviewed USD table showed free Midnight Blue, $4.99/month or $49.90/year Ruby Steel, and $29.99/month or $299.90/year Jade Green; higher tiers use CRO lockup requirements. Terms vary by region.",
    rewards: "The reviewed USD table showed 0% to 5% CRO rewards on everyday spending by tier, with caps on some tiers; offers can change.",
    funding: "Crypto is converted to the applicable market currency before loading and spending; cardholders cannot load cryptocurrency directly onto the prepaid card.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://crypto.com/en/cards/",
    sourceLabel: "Crypto.com Cards page",
    imageUrl: "https://mkt-site-asset.crypto.com/assets/card-page/tiers/Midnight_2.webp",
    imageAlt: "Crypto.com Midnight Blue Visa prepaid card",
    imageSourceNote: "Official Crypto.com-hosted tier image",
    reviewedAt: "2026-08-27",
    caution: "Rewards, lockups, limits, fees, issuers, and availability vary by country and card tier. Verify the applicable cardholder agreement before applying.",
    referralUrl: "https://cryptocom.sjv.io/6yYRZV",
    referralLabel: "Check Crypto.com card options",
    feesUrl: "https://help.crypto.com/en/articles/5966563-crypto-com-prepaid-visa-card-fees-and-limits-united-states",
    updateUrl: "https://crypto.com/en/cards/",
    updateLabel: "Latest tier terms",
    updateNote: "Crypto.com maintains regional card pages and fee articles; the displayed tier, reward, and lockup terms should be rechecked before applying.",
    applicationMethod: "Create or sign in to a Crypto.com account, complete the applicable verification, and apply for the card tier shown in your region.",
    verification: "Account verification and regional eligibility apply.",
    galleryImages: [
      { url: "https://mkt-site-asset.crypto.com/assets/card-page/tiers/Ruby_2.webp", alt: "Crypto.com Ruby Steel Visa card", source: "Official Crypto.com card tier image" },
      { url: "https://mkt-site-asset.crypto.com/assets/card-page/tiers/Jade_2.webp", alt: "Crypto.com Jade Green Visa card", source: "Official Crypto.com card tier image" },
    ],
  },
  {
    slug: "wirex-one-card",
    name: "Wirex One Card",
    provider: "Wirex",
    network: "Visa or Mastercard",
    categories: ["debit", "prepaid"],
    shortDescription: "A virtual, physical, or metal card tied to the Wirex One spending platform.",
    editorialSummary: "Wirex One is presented as a multi-format spending product for crypto and fiat users. Wirex advertises zero FX fees and cashback by membership tier, but the headline reward range should be read alongside eligibility, tier rules, and jurisdictional availability.",
    bestFor: "People looking for a broad international card proposition with virtual, physical, and metal formats.",
    availability: "Wirex advertises availability in 150+ countries, subject to product and jurisdictional restrictions.",
    regions: ["150+ countries advertised; verify residence eligibility"],
    pricing: "The reviewed product page advertises no monthly or annual card fee; applicable terms and regional charges should be checked with Wirex.",
    rewards: "Wirex advertises 0.5% to 8% cashback in USD depending on membership tier.",
    funding: "Spend crypto and fiat through the Wirex One app; conversion and supported-asset details depend on the account and region.",
    cardFormats: ["Virtual", "Physical", "Visa Signature Metal"],
    sourceUrl: "https://www.wirexapp.com/stablecoin-and-crypto-card",
    sourceLabel: "Wirex One product page",
    imageUrl: "https://static.wixstatic.com/media/f627bc_55b10739e1a34d64a4e43c3dbfa09e3c~mv2.png",
    imageAlt: "Wirex physical crypto card",
    imageSourceNote: "Official Wirex-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Wirex states that availability and features are subject to jurisdictional limitations. Headline cashback is not a guaranteed rate for every user.",
  },
  {
    slug: "metamask-card",
    name: "MetaMask Card",
    provider: "MetaMask",
    network: "Mastercard",
    categories: ["debit", "self-custody"],
    shortDescription: "A crypto debit card connected to a MetaMask wallet, with Virtual and Metal options.",
    editorialSummary: "MetaMask emphasizes that users retain control of supported wallet assets until payment. The product has a free Virtual option and a paid Metal option, with supported networks, tokens, regions, and transaction fees that need to be checked before sign-up.",
    bestFor: "Self-custody users who want a wallet-linked spending experience instead of a conventional exchange balance.",
    availability: "Country and territory dependent; the reviewed page listed supported countries and noted temporarily closed US and UK signups.",
    regions: ["Selected countries in Europe and Latin America; verify current list"],
    pricing: "Virtual is listed as free; Metal is listed at $199/year. A minimal transaction fee may apply.",
    rewards: "The reviewed page lists 1% mUSD back for Virtual and 3% for Metal on the first $10,000 of spend, then 1% for Metal; terms apply.",
    funding: "Supported assets can be managed from MetaMask on Linea, Solana, Monad, and Base, with conversion at checkout.",
    cardFormats: ["Virtual", "Metal"],
    sourceUrl: "https://metamask.io/card",
    sourceLabel: "MetaMask Card product page",
    imageUrl: "https://images.ctfassets.net/clixtyxoaeas/5VagZ4WBPVakQ7kz8uqo23/6788ca0e712c6c8a5f87ea7d5a1fc187/card-hero.png?w=2048&q=75&fm=avif",
    imageAlt: "MetaMask Card product image",
    imageSourceNote: "Official MetaMask-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Self-custody does not remove smart-contract, wallet, conversion, tax, or payment-rail risk. Do not enter a seed phrase anywhere to obtain a card.",
  },
  {
    slug: "nexo-card",
    name: "Nexo Card",
    provider: "Nexo",
    network: "Mastercard",
    categories: ["dual-mode", "debit"],
    shortDescription: "A dual-mode card that can spend digital assets or access credit against collateral.",
    editorialSummary: "Nexo’s defining distinction is the switch between Debit Mode and Credit Mode. That flexibility also adds complexity: borrowing against crypto introduces collateral and liquidation considerations, while physical-card access and rewards depend on balance, loyalty tier, and region.",
    bestFor: "Eligible users who understand the difference between spending assets and borrowing against them.",
    availability: "Selected European countries including the EEA and UK, subject to identity verification and eligibility.",
    regions: ["EEA and United Kingdom, selected countries"],
    pricing: "Nexo states no monthly, annual, or inactivity card fees; FX charges and other terms vary by region, tier, and usage.",
    rewards: "Up to 2% crypto cashback in Credit Mode, with published tier and balance requirements.",
    funding: "Debit Mode spends eligible digital assets; Credit Mode borrows against collateral without selling the collateral asset.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://nexo.com/crypto-card",
    sourceLabel: "Nexo Card product page",
    imageUrl: "https://content.nexo.com/media/crypto_card-atf_full-card-d-row.jpg",
    imageAlt: "Nexo crypto card",
    imageSourceNote: "Official Nexo-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Credit Mode is borrowing, not free spending. Collateral, interest, liquidation, eligibility, and tax considerations require separate review.",
    referralUrl: "https://nexo.sjv.io/ZQz0gq",
    referralLabel: "Visit Nexo Card",
    feesUrl: "https://nexo.com/crypto-card",
    updateUrl: "https://nexo.com/crypto-card",
    updateLabel: "Latest Nexo Card terms",
    updateNote: "Nexo publishes the current mode, loyalty, FX, ATM, and regional terms on its Card page and related fee documents.",
    applicationMethod: "Create or sign in to a Nexo account, complete identity verification, and activate the virtual or physical card if eligible.",
    verification: "Nexo states selected European-country availability and identity verification requirements.",
    galleryImages: [
      { url: "https://content.nexo.com/media/crypto_card-usp_comparison-debit-UK-2.jpg", alt: "Nexo Card debit mode visual", source: "Official Nexo product image" },
      { url: "https://content.nexo.com/media/crypto_card-usp_comparison-credit-UK-2.jpg", alt: "Nexo Card credit mode visual", source: "Official Nexo product image" },
    ],
  },
  {
    slug: "ledger-cl-card",
    name: "CL Card, Ledger-compatible",
    provider: "Baanx, designed for Ledger",
    network: "Visa",
    categories: ["debit", "self-custody"],
    shortDescription: "A provider-issued crypto debit card designed to work with Ledger Wallet and Ledger signers.",
    editorialSummary: "Ledger’s card program is a partner marketplace rather than a Ledger-issued card. The CL Card page attributes the product to Baanx and explains that regional providers and account arrangements can differ, while Ledger Wallet provides the funding workflow.",
    bestFor: "Ledger users who want to connect hardware-wallet workflows with a card provider.",
    availability: "Country-dependent; the provider and underlying account arrangement vary by residence.",
    regions: ["Country-dependent; check the card flow in Ledger Wallet"],
    pricing: "The reviewed product page does not present one universal fee schedule; provider and country terms apply.",
    rewards: "1% cashback in BTC, USDC, or USDT depending on country of residence; no staking required is advertised.",
    funding: "Ledger Wallet can fund the card with BTC, ETH, SOL, stablecoins, and other supported assets; Apple Pay and Google Pay are listed.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://shop.ledger.com/pages/cl-card-crypto-card",
    sourceLabel: "Ledger CL Card product page",
    imageUrl: "https://ledger.com/cdn-cgi/image/width=3840,format=auto/https://images.ctfassets.net/ge894kijjvls/1LCkGVxczDIXQIfcXJJn5i/d33ec47a90536b2dc859a00f21b2f0b7/hero_cl_card_desktop__2_.webp",
    imageAlt: "Ledger-compatible CL Card with Ledger device",
    imageSourceNote: "Official Ledger-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Ledger is not the card issuer. Provider, fee, issuer, and country-specific terms must be verified before applying.",
  },
  {
    slug: "redotpay-card",
    name: "RedotPay Card",
    provider: "RedotPay",
    network: "Card networks vary by region",
    categories: ["prepaid", "debit"],
    shortDescription: "A stablecoin-based spending card with virtual and physical formats.",
    editorialSummary: "RedotPay combines a stablecoin spending card with a broader payments app. The official card page separates physical and virtual use cases, while the Help Center publishes the issuance and usage economics. That makes the card easier to compare when the one-time issuance cost is not confused with ongoing fees.",
    bestFor: "Stablecoin users who want a card plus app-based payment rails, subject to local availability.",
    availability: "Registration is unavailable in certain countries and regions; verify the current unsupported-country list.",
    regions: ["Global with country and region exclusions"],
    pricing: "The official Help Center lists a $10 virtual-card issuance fee and $100 physical-card issuance fee. RedotPay states there is no monthly or annual card-management fee; transaction, ATM, conversion, and other charges may still apply.",
    rewards: "No universal card reward rate is stated on the reviewed card page; separate RedotPay rewards or Earn features may have their own conditions.",
    funding: "Stablecoins and other supported assets are managed through the RedotPay app and converted for card spending or withdrawals.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.redotpay.com/card",
    sourceLabel: "RedotPay Card product page",
    imageUrl: "https://staticsource1.redotpay.com/web/img/card/cover-1.webp?t=1787044314761",
    imageAlt: "RedotPay physical stablecoin card",
    imageSourceNote: "Official RedotPay-hosted card image",
    reviewedAt: "2026-08-27",
    caution: "Card availability, supported assets, verification, fees, and unsupported regions can change. Read the current RedotPay Help Center and terms before funding an account.",
    referralUrl: "https://go.cryptosbeginner.com/RedotPay",
    referralLabel: "Check RedotPay card",
    feesUrl: "https://helpcenter.redotpay.com/en/articles/10339271-redotpay-card-limitations-fees",
    updateUrl: "https://www.redotpay.com/news",
    updateLabel: "RedotPay updates",
    updateNote: "RedotPay currently highlights Apple Pay support and maintains separate product, verification, terms, and Help Center pages.",
    applicationMethod: "Download the RedotPay app, complete the provider’s account and verification flow, and choose the virtual or physical card available in your region.",
    verification: "Account verification and regional restrictions apply; RedotPay links to a dedicated verification area.",
    galleryImages: [
      { url: "https://staticsource1.redotpay.com/web/img/card/cover-2.webp?t=1787044314761", alt: "RedotPay virtual card section visual", source: "Official RedotPay card page" },
    ],
  },
  {
    slug: "rizon-card",
    name: "Rizon Visa Card",
    provider: "Rizon",
    network: "Visa",
    categories: ["debit"],
    shortDescription: "A Rizon Visa card with virtual, plastic, and metal formats for eligible residents.",
    editorialSummary: "Rizon presents its card alongside USD and stablecoin payment rails, with virtual, plastic, metal, and Visa Platinum options. Its services-restriction notice is essential context: the product landing page is not a promise of universal global eligibility, even though it advertises broad merchant acceptance.",
    bestFor: "Eligible US or Latin American residents comparing a stablecoin-linked Visa with several physical formats.",
    availability: "The official services notice limits the intended audience to residents and domiciled individuals in the United States or certain Latin American countries, subject to licensing.",
    regions: ["United States and certain Latin American countries"],
    pricing: "Rizon directs users to its fees-and-limits page for current card, spending, withdrawal, and account costs rather than publishing one universal price on the card landing page.",
    rewards: "The official Rizon product materials advertise cashback, with the applicable amount and conditions dependent on card type, account, and current terms.",
    funding: "Rizon describes stablecoin and USD services connected to its app; virtual, plastic, and metal card funding and conversion rules should be confirmed in the account flow.",
    cardFormats: ["Virtual", "Plastic", "Metal", "Visa Platinum"],
    sourceUrl: "https://www.getrizon.com/card",
    sourceLabel: "Rizon Visa Card page",
    imageUrl: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/67ffab826b4e439a79e46e2e_hero.webp",
    imageAlt: "Rizon Visa card held in a hand",
    imageSourceNote: "Official Rizon-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "Rizon’s services restriction and country eligibility notice override broad merchant-count marketing. Confirm residence eligibility and current fees before applying.",
    referralUrl: "https://getrizon.sng.link/Eshdf/1cro/dfwn?ref=UZ6Q9CI&_forward_params=2",
    referralLabel: "Check Rizon Card",
    feesUrl: "https://www.getrizon.com/fees-and-limits",
    updateUrl: "https://www.getrizon.com/blog",
    updateLabel: "Rizon updates",
    updateNote: "Rizon maintains a product blog, fee-and-limit page, and Terms of Service; features and country access can change as licensing expands.",
    applicationMethod: "Download the Rizon app, create an account, complete the applicable verification, and request the card format offered for your residence.",
    verification: "The page displays a services-restriction notice and country-dependent onboarding; verification and eligibility apply.",
    galleryImages: [
      { url: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/69391318bfc66e4655cf23d8_card-1-img.avif", alt: "Rizon card option one", source: "Official Rizon card page" },
      { url: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/693913c0bb8a2900a6e1cf93_card-2-img.avif", alt: "Rizon card option two", source: "Official Rizon card page" },
      { url: "https://cdn.prod.website-files.com/67ef7f45861719f51a47c19c/693914286e0894ff7d8e238e_card-3-img.avif", alt: "Rizon card option three", source: "Official Rizon card page" },
    ],
  },
  {
    slug: "bybit-card",
    name: "Bybit Card",
    provider: "Bybit",
    network: "Mastercard",
    categories: ["prepaid", "debit"],
    shortDescription: "A crypto spending card with a published cashback range and strict regional limitations.",
    editorialSummary: "Bybit’s card page leads with everyday spending and a 2%–10% cashback range, but its country notice is just as important as the reward headline. Bybit states that the product is not meant for European Economic Area customers, so the directory treats regional eligibility as a primary fact rather than a footnote.",
    bestFor: "Eligible non-EEA users who want a Bybit-linked payment card and are comfortable checking current reward terms.",
    availability: "Certain countries only; the reviewed official notice explicitly excludes European Economic Area customers.",
    regions: ["Selected countries outside the EEA"],
    pricing: "Bybit’s card page does not publish one universal fee table in the visible overview; card, conversion, ATM, and regional fees should be checked in the application flow and terms.",
    rewards: "Bybit advertises 2%–10% cashback on everyday spending and a welcome package with up to 110 USDT cashback in the first 30 days; terms and eligible categories apply.",
    funding: "Bybit describes flexible crypto-or-cash spending through its platform; the exact supported assets and top-up method depend on the eligible regional product.",
    cardFormats: ["Virtual", "Physical"],
    sourceUrl: "https://www.bybit.com/en/cards/",
    sourceLabel: "Bybit Card product page",
    imageUrl: "https://www.bybit.com/bycsi-root/common-static/fiat-static/cards/landing_next/bybit_card.png?format=webp&quality=75&resize=width%2F480",
    imageAlt: "Bybit Card Mastercard product image",
    imageSourceNote: "Official Bybit-hosted Card product image",
    reviewedAt: "2026-08-27",
    caution: "The Bybit page explicitly excludes EEA customers. Cashback, fees, merchant categories, and eligibility are not universal and may change.",
    referralUrl: "https://go.cryptosbeginner.com/ByBitCard",
    referralLabel: "Check Bybit Card",
    feesUrl: "https://www.bybit.com/en/cards/",
    updateUrl: "https://www.bybit.com/en/cards/",
    updateLabel: "Latest Bybit Card terms",
    updateNote: "Bybit publishes current eligibility and fee FAQs within its Card flow; the visible region notice should be checked before sign-up.",
    applicationMethod: "Apply through an eligible Bybit account, complete identity verification, and follow the regional virtual or physical card onboarding flow.",
    verification: "Identity verification and country eligibility apply; EEA customers are explicitly excluded on the reviewed page.",
    galleryImages: [
      { url: "https://www.bybit.com/bycsi-root/common-static/fiat-static/cards/landing_next/card_designs/default.png?format=avif&quality=75&resize=width%2F2880", alt: "Bybit Card default design", source: "Official Bybit Card page" },
      { url: "https://www.bybit.com/bycsi-root/common-static/fiat-static/cards/landing_next/card_designs/tmrland.png?format=avif&quality=75&resize=width%2F2880", alt: "Bybit Card limited design", source: "Official Bybit Card page" },
    ],
  },
  {
    slug: "bitget-wallet-card",
    name: "Bitget Wallet Card",
    provider: "Bitget Wallet",
    network: "Visa or Mastercard",
    categories: ["debit", "prepaid"],
    shortDescription: "A wallet-linked spending card with selectable assetback rewards.",
    editorialSummary: "Bitget Wallet frames the card around assetback: eligible users can choose reward assets such as BTC, gold-linked assets, stocks, or USDC. The product page also emphasizes familiar payment rails and no opening or annual fee, while the regional fee page remains the authority for activation and other charges.",
    bestFor: "Users who want a wallet-based card and prefer choosing the asset in which rewards are paid.",
    availability: "Region-dependent; eligibility and card availability should be checked in the current application flow.",
    regions: ["Selected regions; verify in application"],
    pricing: "The official regional fee page states no monthly or annual fee and no top-up fee, with a $0.10 activation fee shown for that region; other regional charges may differ.",
    rewards: "The product page advertises up to 3% assetback, with reward assets, eligible purchases, and settlement conditions applying.",
    funding: "Apply online, complete identity verification, activate and top up the card, then spend through Visa/Mastercard rails and collect assetback.",
    cardFormats: ["Virtual", "Physical availability varies"],
    sourceUrl: "https://web3.bitget.com/card",
    sourceLabel: "Bitget Wallet Card product page",
    imageUrl: "https://web3.bitget.com/bgwactivity-static/_next/static/media/cardHeroPhoneEn.305uvu1oe992v.png",
    imageAlt: "Bitget Wallet Card in the Bitget Wallet app",
    imageSourceNote: "Official Bitget Wallet-hosted product image",
    reviewedAt: "2026-08-27",
    caution: "“Up to 3%” is a provider headline, not a guaranteed rate. Confirm eligible purchases, reward assets, regional fees, and settlement timing.",
    referralUrl: "https://web3.bitget.com/share/h0Nk8?inviteCode=pC8Hzp",
    referralLabel: "Check Bitget Wallet Card",
    feesUrl: "https://web3.bitget.com/helpCenter/283",
    updateUrl: "https://web3.bitget.com/en/academy/how-to-use-a-crypto-card-a-beginners-guide-to-spending-bitcoin-and-stablecoins",
    updateLabel: "Bitget Card guide",
    updateNote: "Bitget Wallet maintains a fee center and Academy guides; the exact card flow, region, rewards, and fee schedule can change.",
    applicationMethod: "Apply online through Bitget Wallet, complete identity verification, activate the card, and top up before spending.",
    verification: "The official setup flow begins with online application and identity verification.",
    galleryImages: [
      { url: "https://web3.bitget.com/bgwactivity-static/_next/static/media/cardBadgeBtc.3g1m7-4fir6z_.png", alt: "Bitget Wallet Card BTC reward badge", source: "Official Bitget Wallet product image" },
      { url: "https://web3.bitget.com/bgwactivity-static/_next/static/media/cardBadgeNvda.0l31qjsw_sbzf.png", alt: "Bitget Wallet Card stock reward badge", source: "Official Bitget Wallet product image" },
    ],
  },
  {
    slug: "kardpay-card",
    name: "KardPay Card",
    provider: "KardPay",
    network: "Visa or Mastercard",
    categories: ["prepaid", "debit"],
    shortDescription: "A tiered crypto spending card with one-time pricing and published top-up fees.",
    editorialSummary: "KardPay publishes a useful tier table: Core, Pro, and Elite differ in one-time price, annual or monthly limits, top-up percentage, support, and physical-card availability. That structure is more informative than calling the product simply ‘cashback’ or ‘low fee.’",
    bestFor: "Users comparing explicit one-time card tiers and willing to price the top-up cost against their actual spending pattern.",
    availability: "The official page advertises 180+ countries; eligibility and card issuance remain subject to the account flow and provider terms.",
    regions: ["180+ countries advertised; verify residence"],
    pricing: "Core is listed at $29 one-time with 5% top-up fees; Pro at $99 one-time with 4% top-up fees; Elite at $299 one-time with 3% top-up fees. Physical Elite is listed at $299 one-time with a 4% top-up fee and pre-orders soon.",
    rewards: "The KardPay site advertises up to 2% cashback; the applicable tier, asset, limits, and reward conditions should be confirmed in current terms.",
    funding: "The official hero describes spending USDT, USDC, and other crypto anywhere Visa or Mastercard is accepted, with instant top-up messaging.",
    cardFormats: ["Virtual", "Physical Elite pre-order"],
    sourceUrl: "https://kardpay.app/?lang=en",
    sourceLabel: "KardPay official product page",
    imageUrl: "https://kardpay.app/__l5e/assets-v1/6a06e87f-dc13-439a-8660-ba94c3ff8569/visa-card-green.svg",
    imageAlt: "KardPay Core green Visa/Mastercard card",
    imageSourceNote: "Official KardPay-hosted card asset",
    reviewedAt: "2026-08-27",
    caution: "Top-up percentages and tier limits materially affect total cost. Physical Elite was marked pre-orders soon on the reviewed page.",
    referralUrl: "https://app.kardpay.app/auth?ref=420E7DF6",
    referralLabel: "Check KardPay tiers",
    feesUrl: "https://kardpay.app/?lang=en#pricing",
    updateUrl: "https://kardpay.app/?lang=en",
    updateLabel: "Latest KardPay pricing",
    updateNote: "KardPay publishes tier prices, limits, top-up fees, and card availability on its official pricing page; confirm the current table before funding.",
    applicationMethod: "Open the KardPay application, choose an available tier, complete the provider’s onboarding, and fund the card with supported assets.",
    verification: "Eligibility and any account verification requirements apply through the KardPay application flow.",
    galleryImages: [
      { url: "https://kardpay.app/__l5e/assets-v1/824e75cd-8519-481e-a68f-8f5c24fff77c/visa-card-white.svg", alt: "KardPay Pro white card", source: "Official KardPay product asset" },
      { url: "https://kardpay.app/__l5e/assets-v1/c47b6b86-7bc9-4ac8-aa88-9e42f618d3c4/visa-card-black.svg", alt: "KardPay Elite black card", source: "Official KardPay product asset" },
    ],
  },
];

export function getCardBySlug(slug: string) {
  return cardListings.find((card) => card.slug === slug);
}

export const cardCategories: { value: "all" | CardCategory; label: string }[] = [
  { value: "all", label: "All approaches" },
  { value: "prepaid", label: "Prepaid" },
  { value: "debit", label: "Debit" },
  { value: "dual-mode", label: "Dual-mode" },
  { value: "self-custody", label: "Self-custody" },
];
