import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const SITE_URL = "https://www.cryptosbeginner.com";
const PAGE_URL = `${SITE_URL}/exchanges/primexbt/rewards-center`;
const REVIEW_URL = `${SITE_URL}/exchanges/primexbt-review`;

const UPDATED = "8 October 2026";
const UPDATED_ISO = "2026-10-08";

const AFFILIATE = "https://go.prmx.co/visit/?bta=36112&nci=7605";
const PRIME_XBT_HOME = "https://primexbt.com/";

export const metadata: Metadata = {
  title: "PrimeXBT Rewards Center 2026: Bonuses, Promo Codes & Referrals",
  description:
    "PrimeXBT Rewards Center explained: welcome bonuses, promo codes, volume milestones, referral earnings, and bonus terms. Check the live page for current amounts. Reviewed October 2026.",
  alternates: {
    canonical: PAGE_URL,
  },
  openGraph: {
    title: "PrimeXBT Rewards Center 2026: Bonuses, Promo Codes & Referrals",
    description:
      "How the Rewards Center works: bonus types, promo codes, volume milestones, referrals, and the terms that decide whether a bonus is actually useful.",
    url: PAGE_URL,
    type: "article",
    images: [
      {
        url: `${SITE_URL}/images/primexbt-academy-banner.png`,
        width: 1024,
        height: 512,
        alt: "PrimeXBT platform banner for the Rewards Center guide",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "PrimeXBT Rewards Center 2026: Bonuses, Promo Codes & Referrals",
    description:
      "Bonuses, promo codes, volume milestones, and referrals, with the terms beginners must read first.",
    images: [`${SITE_URL}/images/primexbt-academy-banner.png`],
  },
};

const faqItems = [
  {
    question: "What is the PrimeXBT Rewards Center?",
    answer:
      "It is PrimeXBT's bonus hub: a dashboard section where you complete tasks, claim promo codes, and unlock bonuses such as welcome offers, volume milestones, and referral rewards. Each reward has its own terms and expiry.",
  },
  {
    question: "Can I withdraw bonus money from PrimeXBT?",
    answer:
      "Bonuses are generally tradable credit, not cash you can withdraw directly. Profits earned while trading with bonus funds may be withdrawable once you meet the stated conditions. Read each bonus's terms before counting on it.",
  },
  {
    question: "How do PrimeXBT promo codes work?",
    answer:
      "Promo codes are alphanumeric vouchers you enter in your account to unlock a perk, such as a deposit bonus or reduced fees. Codes come from PrimeXBT's own promotions or authorised partners, and each has an expiry date and conditions.",
  },
  {
    question: "What are the volume milestone rewards?",
    answer:
      "PrimeXBT has historically offered tiered bonuses for reaching trading volume milestones, with higher volumes unlocking larger bonuses. The exact tiers and amounts change, so check the live Rewards Center for the current structure.",
  },
  {
    question: "How does the PrimeXBT referral program work?",
    answer:
      "You share a personal referral link, and you earn a share of the trading fees generated by people who sign up through it. The Rewards Center includes an estimator that projects potential earnings based on how many users you refer and how much they trade.",
  },
  {
    question: "Are PrimeXBT bonuses worth it for beginners?",
    answer:
      "A small welcome bonus can make your first trades cheaper, which is genuinely useful. But bonuses never make trading safe, and chasing volume milestones encourages overtrading. Take the free perks, ignore the pressure to trade more.",
  },
] as const;

function PrimaryAffiliateButton({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <a
      href={AFFILIATE}
      target="_blank"
      rel="sponsored noopener noreferrer"
      style={{
        color: "#ffffff",
        textDecoration: "none",
      }}
      className={`inline-flex min-h-11 items-center justify-center rounded-lg bg-emerald-600 px-5 py-3 text-center text-sm font-bold transition hover:bg-emerald-700 ${className}`}
    >
      {children}
    </a>
  );
}

function Section({
  id,
  children,
}: {
  id?: string;
  children: React.ReactNode;
}) {
  return (
    <section
      id={id}
      className="mx-auto max-w-4xl scroll-mt-24 px-4 pb-12"
    >
      {children}
    </section>
  );
}

export default function PrimeXBTRewardsCenterPage() {
  const articleLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: "PrimeXBT Rewards Center 2026: Bonuses, Promo Codes & Referrals",
    description:
      "An educational guide to the PrimeXBT Rewards Center: welcome bonuses, promo codes, volume milestones, referral earnings, and the bonus terms beginners must read before relying on them.",
    datePublished: "2026-10-08",
    dateModified: UPDATED_ISO,
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": PAGE_URL,
    },
    author: {
      "@type": "Organization",
      name: "CryptosBeginner editorial team",
    },
    publisher: {
      "@type": "Organization",
      name: "CryptosBeginner",
      url: SITE_URL,
    },
    image: [`${SITE_URL}/images/primexbt-academy-banner.png`],
    inLanguage: "en",
  };

  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: SITE_URL,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Exchanges",
        item: `${SITE_URL}/exchanges`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: "PrimeXBT Review",
        item: REVIEW_URL,
      },
      {
        "@type": "ListItem",
        position: 4,
        name: "PrimeXBT Rewards Center",
        item: PAGE_URL,
      },
    ],
  };

  const faqLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqItems.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };

  return (
    <>
      <Header />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }}
      />

      <main className="min-w-0 overflow-x-hidden bg-white text-slate-900">
        <section className="border-b border-slate-200 bg-slate-50">
          <div className="mx-auto max-w-4xl px-4 py-12 sm:py-16">
            <p className="text-sm font-bold text-indigo-700">
              Updated {UPDATED} · By Alex Rivera · Reviewed for CryptosBeginner
            </p>

            <h1 className="mt-3 text-4xl font-black leading-tight tracking-tight text-slate-950 sm:text-5xl">
              PrimeXBT Rewards Center 2026: Bonuses, Promo Codes &amp; Referrals
            </h1>

            <p className="mt-5 max-w-3xl text-lg leading-8 text-slate-800">
              The Rewards Center is PrimeXBT&apos;s bonus hub: welcome offers,
              promo codes, volume milestones, and referral rewards. This guide
              explains how each one works, and the terms that decide whether a
              bonus is actually useful to you.
            </p>

            <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap">
              <PrimaryAffiliateButton className="w-full sm:w-auto">
                Open a PrimeXBT account and check live rewards
              </PrimaryAffiliateButton>

              <Link
                href="/exchanges/primexbt-review"
                className="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-bold text-slate-800 no-underline transition hover:bg-slate-100 sm:w-auto"
              >
                Back to the full PrimeXBT review
              </Link>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-4xl px-4 pt-8">
          <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-4 text-sm leading-6 text-slate-800">
            <strong>Affiliate disclosure:</strong> Some links on this page are
            affiliate links, including PrimeXBT links. CryptosBeginner may earn
            a commission if you register through one. This does not change our
            assessment criteria or conclusions. This page is educational
            content, not financial advice.
          </div>
        </section>

        <section className="mx-auto max-w-4xl px-4 py-8">
          <figure>
            <Image
              src="/images/primexbt-academy-banner.png"
              alt="PrimeXBT platform banner for the Rewards Center guide"
              width={1024}
              height={512}
              className="h-auto w-full rounded-2xl border border-slate-200 shadow-sm"
              priority
            />

            <figcaption className="mt-3 text-center text-sm leading-6 text-slate-500">
              The Rewards Center gathers PrimeXBT&apos;s bonuses and promo
              offers in one place. Amounts and conditions change, so confirm
              the live terms.
            </figcaption>
          </figure>
        </section>

        <section className="mx-auto max-w-4xl px-4 pb-10">
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 sm:p-7">
            <h2 className="text-2xl font-black text-emerald-950">
              TL;DR: the short version
            </h2>

            <ul className="mt-4 space-y-3 leading-7 text-slate-800">
              <li>
                <strong>The Rewards Center</strong> is where you claim
                bonuses, enter promo codes, and track milestone progress.
              </li>
              <li>
                <strong>Welcome bonuses</strong> typically reward your first
                deposit. Amounts and conditions change, so check the live
                offer.
              </li>
              <li>
                <strong>Promo codes</strong> unlock perks like deposit
                bonuses. Use codes from PrimeXBT or trusted partners only.
              </li>
              <li>
                <strong>Volume milestones</strong> pay larger bonuses for
                higher trading volume. Chasing them encourages overtrading,
                so be careful.
              </li>
              <li>
                <strong>Read the terms first.</strong> Bonuses have expiry
                dates and conditions. A bonus you cannot use is worth nothing.
              </li>
            </ul>
          </div>
        </section>

        <section className="mx-auto max-w-4xl px-4 pb-10">
          <div className="rounded-2xl border border-slate-200 bg-white p-6">
            <h2 className="text-lg font-black text-slate-950">On this page</h2>

            <ol className="mt-4 grid gap-2 text-sm font-bold text-indigo-700 sm:grid-cols-2">
              <li>
                <a href="#what-it-is" className="underline underline-offset-4">
                  What the Rewards Center is
                </a>
              </li>
              <li>
                <a href="#welcome" className="underline underline-offset-4">
                  Welcome bonus and promo codes
                </a>
              </li>
              <li>
                <a href="#milestones" className="underline underline-offset-4">
                  Volume milestones
                </a>
              </li>
              <li>
                <a href="#referrals" className="underline underline-offset-4">
                  Referrals and the earnings estimator
                </a>
              </li>
              <li>
                <a href="#terms" className="underline underline-offset-4">
                  Bonus terms and withdrawals
                </a>
              </li>
              <li>
                <a href="#faq" className="underline underline-offset-4">
                  FAQ
                </a>
              </li>
            </ol>
          </div>
        </section>

        <Section id="what-it-is">
          <h2 className="text-3xl font-black tracking-tight text-slate-950">
            What the Rewards Center is
          </h2>

          <p className="mt-4 leading-8 text-slate-800">
            The Rewards Center is a section of your PrimeXBT dashboard that
            collects the platform&apos;s incentive programs in one place.
            Instead of hunting through emails and announcements, you complete
            tasks, claim codes, and track your progress toward milestone
            rewards from a single screen. Typical categories include account
            verification rewards, deposit bonuses, promo codes, trading volume
            milestones, and the referral program.
          </p>

          <p className="mt-4 leading-8 text-slate-800">
            Think of it as a loyalty program for a trading platform. The
            rewards are real, but every one of them is designed to make you
            trade more. That is worth remembering before you start chasing
            milestones.
          </p>
        </Section>

        <Section id="welcome">
          <h2 className="text-3xl font-black tracking-tight text-slate-950">
            Welcome bonus and promo codes
          </h2>

          <h3 className="mt-6 text-2xl font-black text-slate-950">
            Welcome bonus
          </h3>

          <p className="mt-3 leading-8 text-slate-800">
            New users have historically been offered a welcome bonus tied to
            their first deposit, for example a percentage of the deposit up
            to a cap, claimable from the Rewards Center after funding a
            margin account. The exact percentage, cap, and claiming steps
            change with each promotion, so treat any specific figure you see
            online as a past example. Open the live Rewards Center to see the
            current offer and its countdown, if one applies.
          </p>

          <h3 className="mt-6 text-2xl font-black text-slate-950">
            Promo codes
          </h3>

          <p className="mt-3 leading-8 text-slate-800">
            Promo codes are alphanumeric vouchers you enter in your account
            to unlock a perk, such as a deposit bonus or reduced fees. Codes
            appear in PrimeXBT&apos;s own promotions and through authorised
            partners. Before using one, check three things: the expiry date,
            the conditions attached, and that the source is legitimate. A
            code from a random forum post may be expired, fake, or tied to
            terms you would not accept.
          </p>
        </Section>

        <Section id="milestones">
          <h2 className="text-3xl font-black tracking-tight text-slate-950">
            Volume milestones
          </h2>

          <p className="mt-4 leading-8 text-slate-800">
            Volume milestones reward you for reaching cumulative trading
            volume thresholds. Past structures used tiers such as a small
            bonus for modest volume, a mid-tier bonus around the
            hundred-thousand-dollar volume mark, and a large bonus for very
            high volume. The current tiers and amounts are published in the
            live Rewards Center, and they can change, so confirm them there
            rather than relying on old figures.
          </p>

          <div className="mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 sm:p-6">
            <p className="leading-7 text-slate-900">
              <strong>Honest warning:</strong> milestones are engineered to
              make you trade more. Extra volume means extra fees, extra
              funding costs, and extra chances to make mistakes. Never
              increase your trading just to unlock a bonus. The bonus is
              almost always smaller than the costs of the volume required to
              earn it.
            </p>
          </div>
        </Section>

        <Section id="referrals">
          <h2 className="text-3xl font-black tracking-tight text-slate-950">
            Referrals and the earnings estimator
          </h2>

          <p className="mt-4 leading-8 text-slate-800">
            The referral program gives you a personal link to share. When
            people register through it and trade, you earn a share of the
            trading fees they generate. The Rewards Center includes a monthly
            income estimator: you enter how many users you expect to refer
            and how much they might trade, and it projects potential
            earnings.
          </p>

          <p className="mt-4 leading-8 text-slate-800">
            Treat the estimator as a rough illustration, not a forecast.
            Actual earnings depend on whether your referrals stay active and
            how much they really trade, which is usually far less than
            optimistic projections assume. Referring friends to a leveraged
            trading platform also carries a responsibility: only recommend it
            to people who understand the risks, and be honest that you earn
            from their activity.
          </p>
        </Section>

        <Section id="terms">
          <h2 className="text-3xl font-black tracking-tight text-slate-950">
            Bonus terms and withdrawals
          </h2>

          <p className="mt-4 leading-8 text-slate-800">
            Every bonus comes with conditions, and the conditions are what
            actually matter. Before claiming anything, check the expiry date,
            which activities qualify, whether the bonus itself can ever be
            withdrawn or only profits earned with it, and any verification
            steps required. Some past offers, for example, required
            completing identity verification and a minimum deposit before the
            bonus could be claimed.
          </p>

          <p className="mt-4 leading-8 text-slate-800">
            Withdrawing is straightforward once conditions are met: choose the
            asset, the network, and the destination address carefully, as
            always. If a bonus is still locked by unmet conditions, sort
            those out first. And remember that a bonus never changes the
            fundamental math of leveraged trading: it can reduce your costs,
            but it cannot make a losing strategy profitable.
          </p>
        </Section>

        <Section id="faq">
          <h2 className="text-3xl font-black tracking-tight text-slate-950">
            Frequently asked questions
          </h2>

          <div className="mt-7 grid gap-4">
            {faqItems.map((item) => (
              <article
                key={item.question}
                className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
              >
                <h3 className="text-xl font-black text-slate-950">
                  {item.question}
                </h3>

                <p className="mt-3 leading-8 text-slate-800">{item.answer}</p>
              </article>
            ))}
          </div>
        </Section>

        <section className="mx-auto max-w-4xl px-4 pb-12">
          <div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-6 sm:p-7">
            <h2 className="text-xl font-black text-indigo-950">
              Continue with the full review
            </h2>

            <p className="mt-3 leading-7 text-slate-800">
              Bonuses are one piece. The full review covers fees, leverage,
              regulation, restricted countries, and who should skip PrimeXBT
              entirely.
            </p>

            <Link
              href="/exchanges/primexbt-review"
              className="mt-4 inline-flex min-h-11 items-center justify-center rounded-lg bg-indigo-700 px-5 py-3 text-sm font-bold text-white no-underline transition hover:bg-indigo-800"
            >
              Read the PrimeXBT review
            </Link>
          </div>
        </section>

        <section className="border-t border-slate-200 bg-slate-50">
          <div className="mx-auto max-w-4xl px-4 py-12">
            <h2 className="text-2xl font-black tracking-tight text-slate-950">
              Sources and verification
            </h2>

            <p className="mt-4 max-w-3xl leading-8 text-slate-800">
              This page was reviewed on {UPDATED}. Bonus amounts, promo
              codes, volume tiers, and referral terms change frequently.
              Confirm the current offers and their conditions in the live
              Rewards Center before acting on them.
            </p>

            <ul className="mt-6 list-disc space-y-3 pl-6 leading-7 text-slate-800">
              <li>
                <a
                  href={PRIME_XBT_HOME}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-bold text-indigo-700 underline underline-offset-4"
                >
                  PrimeXBT official website
                </a>{" "}
                for current rewards, bonus terms, and legal links.
              </li>
              <li>
                <a
                  href={REVIEW_URL}
                  className="font-bold text-indigo-700 underline underline-offset-4"
                >
                  CryptosBeginner PrimeXBT review
                </a>{" "}
                for the broader assessment this guide supports.
              </li>
            </ul>
          </div>
        </section>

        <section className="border-t border-slate-200 bg-white">
          <div className="mx-auto max-w-4xl px-4 py-8 text-sm leading-7 text-slate-600">
            <p>
              <strong>Disclaimer:</strong> Educational content only. This page
              is not financial, investment, legal, or tax advice.
              Cryptocurrency, CFDs, futures, and leveraged products can result
              in rapid or total loss of capital. Availability depends on your
              jurisdiction. Some links are affiliate links. Verify live terms,
              fees, legal disclosures, restrictions, and product conditions on
              PrimeXBT&apos;s official website before depositing funds.
            </p>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
