import type { MetadataRoute } from "next";
import { glossaryTerms } from "./learn/crypto-glossary/glossary-data";
import { cardListings } from "./crypto-cards/cards-data";
import { editorialPages } from "./crypto-cards/editorial-data";
import { dexServices } from "./dexes/dex-data";
import { predictionPlatforms } from "./prediction-markets/prediction-data";
import { popularWallets } from "./wallets/popular/wallet-data";

const SITE_URL = "https://www.cryptosbeginner.com";
const DEFAULT_MODIFIED = new Date("2026-08-27");
const RECENT_MODIFIED = new Date("2026-10-09");

// Routes refreshed or published in October 2026.
const recentRoutes = new Set([
  "/",
  "/exchanges/primexbt-review",
  "/exchanges/primexbt/fees",
  "/exchanges/primexbt/deposit-guide",
  "/exchanges/primexbt/withdrawal-guide",
  "/exchanges/primexbt/kyc-guide",
  "/exchanges/primexbt/copy-trading",
  "/exchanges/primexbt/registration-guide",
  "/exchanges/primexbt/login-guide",
  "/exchanges/primexbt/demo-account",
  "/exchanges/primexbt/promo-code",
  "/exchanges/primexbt/trading-guide",
  "/exchanges/primexbt/global-markets-trading",
  "/exchanges/primexbt/buy-crypto",
  "/exchanges/primexbt/app",
  "/exchanges/primexbt/academy",
  "/exchanges/primexbt/contests",
  "/exchanges/primexbt/customer-support-guide",
  "/exchanges/primexbt/rewards-center",
  "/exchanges/primexbt/registration-guide",
  "/exchanges/primexbt/login-guide",
  "/exchanges/primexbt/demo-account",
  "/exchanges/primexbt/promo-code",
  "/exchanges/primexbt/trading-guide",
  "/exchanges/primexbt/global-markets-trading",
  "/exchanges/primexbt/buy-crypto",
  "/exchanges/primexbt/app",
  "/exchanges/primexbt/academy",
  "/exchanges/primexbt/contests",
  "/exchanges/primexbt/customer-support-guide",
  "/exchanges/primexbt/rewards-center",
  "/exchanges/bybit-review",
  "/public-wallets/meme-traders",
  "/tools/paper-trading",
  "/tools/coinstats-review",
  "/tools/odinbot-review",
  "/wallets/prokey-review",
]);

const regionRoutes = [
  "/regions/argentina",
  "/regions/australia",
  "/regions/australia/how-to-buy-bitcoin",
  "/regions/austria",
  "/regions/bahrain",
  "/regions/bangladesh",
  "/regions/brazil",
  "/regions/canada",
  "/regions/canada/british-columbia",
  "/regions/canada/ontario",
  "/regions/canada/quebec",
  "/regions/denmark",
  "/regions/egypt",
  "/regions/ethiopia",
  "/regions/france",
  "/regions/germany",
  "/regions/ghana",
  "/regions/hong-kong",
  "/regions/india",
  "/regions/indonesia",
  "/regions/ireland",
  "/regions/italy",
  "/regions/japan",
  "/regions/kenya",
  "/regions/malaysia",
  "/regions/mexico",
  "/regions/netherlands",
  "/regions/nigeria",
  "/regions/norway",
  "/regions/oman",
  "/regions/pakistan",
  "/regions/pakistan/how-to-buy-bitcoin",
  "/regions/philippines",
  "/regions/poland",
  "/regions/saudi-arabia",
  "/regions/singapore",
  "/regions/south-africa",
  "/regions/south-korea",
  "/regions/spain",
  "/regions/sweden",
  "/regions/switzerland",
  "/regions/thailand",
  "/regions/turkey",
  "/regions/uae",
  "/regions/united-kingdom",
  "/regions/united-states",
  "/regions/vietnam",
];

// Localised region guides (German and French) omitted from the original list.
const localizedRegionRoutes = [
  "/de/regionen/deutschland",
  "/de/regionen/oesterreich",
  "/de/regionen/schweiz",
  "/fr/regions/canada/quebec",
  "/fr/regions/france",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const coreRoutes = [
    "/",
    "/about",
    "/contact",
    "/disclaimer",
    "/privacy-policy",
    "/methodology",
    "/learn",
    "/learn/crypto-glossary",
    "/learn/gmgn-ai-agent",
    "/learn/what-are-bitcoin-forks",
    "/tools/bitcoin-halving",
    "/tools/exchange-finder",
    "/tools/fee-calculator",
    "/tools/paper-trading",
    "/tools/coinstats-review",
    "/tools/odinbot-review",
    "/crypto-research",
    "/crypto-prices",
    "/crypto-screener",
    "/wallet-tracker",
    "/public-wallets",
  "/public-wallets/meme-traders",
    "/wallets/popular",
    "/wallet-alerts",
    "/meme-coin-research",
    "/crypto-cards",
    "/learn/bitcoin-forks",
    "/learn/bitcoin-classic-hard-fork",
    "/learn/seed-phrase-security",
    "/learn/what-is-proof-of-reserves",
    "/learn/how-to-check-exchange-proof-of-reserves",
    "/learn/crypto-exchange-security-checklist",
    "/learn/how-p2p-escrow-works",
    "/exchanges",
    "/exchanges/best-crypto-exchanges-2026",
  "/exchanges/bybit-review",
    "/exchanges/no-kyc",
    "/exchanges/primexbt-review",
    "/exchanges/primexbt/fees",
    "/exchanges/primexbt/deposit-guide",
    "/exchanges/primexbt/withdrawal-guide",
    "/exchanges/primexbt/kyc-guide",
    "/exchanges/primexbt/copy-trading",
    "/wallets/best-crypto-wallets-2026",
    "/wallets/prokey-review",
    "/dexes",
    "/prediction-markets",
    "/meme-coins",
    "/meme-coins/guides",
    "/meme-coins/tutorials",
    "/regions",
  ];
  const routes = [
    ...coreRoutes,
    ...regionRoutes,
    ...localizedRegionRoutes,
    ...cardListings.map((card) => `/crypto-cards/${card.slug}`),
    ...editorialPages.map((page) => `/crypto-cards/${page.slug}`),
    ...dexServices.filter((service) => service.isDex).map((service) => `/dexes/${service.slug}`),
    ...predictionPlatforms.map((platform) => `/prediction-markets/${platform.slug}`),
    "/meme-coins/reviews/axiom-trade",
    "/meme-coins/reviews/gmgn-ai",
    "/meme-coins/reviews/pump-fun",
    "/meme-coins/reviews/padre-terminal",
    "/meme-coins/reviews/fomo-photon",
    "/meme-coins/reviews/bags-fm",
    "/meme-coins/reviews/four-meme",
    "/meme-coins/reviews/sunpump",
    "/meme-coins/guides/slippage-mev",
    "/meme-coins/guides/presets",
    "/meme-coins/tutorials/gmgn-beginners",
    "/meme-coins/tutorials/fomo-beginners",
    ...popularWallets.map((wallet) => `/wallets/popular/${wallet.slug}`),
    ...dexServices.filter((service) => !service.isDex && (service.isNoKycCandidate || service.isKycConditional)).map((service) => `/exchanges/no-kyc/${service.slug}`),
    ...glossaryTerms.map((term) => `/learn/crypto-glossary/${term.slug}`),
  ];
  return routes.map((route) => ({
    url: `${SITE_URL}${route}`,
    lastModified: recentRoutes.has(route) ? RECENT_MODIFIED : DEFAULT_MODIFIED,
    changeFrequency: route.includes("crypto-glossary") ? "monthly" : "weekly",
    priority: ["/learn/crypto-glossary", "/crypto-research", "/crypto-cards", "/dexes", "/prediction-markets", "/exchanges/no-kyc", "/exchanges/primexbt-review"].includes(route) ? 0.8 : route.startsWith("/learn/crypto-glossary/") ? 0.6 : route.startsWith("/crypto-cards/") ? (editorialPages.some((page) => `/crypto-cards/${page.slug}` === route) ? 0.8 : 0.75) : route.startsWith("/dexes/") || route.startsWith("/prediction-markets/") || route.startsWith("/exchanges/no-kyc/") ? 0.7 : ["/crypto-prices", "/crypto-screener", "/wallet-tracker"].includes(route) ? 0.75 : 0.7,
  }));
}
