import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import DexDirectory from "@/app/dexes/DexDirectory";
import { noKycDirectoryServices } from "@/app/dexes/dex-data";

const siteUrl = "https://www.cryptosbeginner.com";
const faqs = [
  { question: "What does no-KYC mean here?", answer: "It describes a provider-stated or observed access path that does not start with the conventional identity-document workflow. It does not guarantee anonymity, permanent access, zero monitoring, or exemption from local law." },
  { question: "Are DEXes and no-KYC exchanges the same?", answer: "No. A DEX usually uses a wallet and smart contracts, while a no-KYC exchange can also mean a P2P market, an instant-swap service, or a limited account tier. Their custody, settlement, liquidity, and counterparty risks differ." },
  { question: "Can a no-KYC service ask for documents later?", answer: "Yes. A provider, payment counterparty, asset route, jurisdiction, volume threshold, refund, or AML review can trigger additional information requests. Check the current terms before depositing or sending funds." },
  { question: "Do no-KYC services remove tax or legal obligations?", answer: "No. KYC status does not determine whether a transaction is taxable, lawful, reportable, or suitable for your situation. Keep records and follow the rules that apply where you live." },
];

export const metadata: Metadata = {
  title: { absolute: "No-KYC Exchange Directory: Access, Fees & Risks | CryptosBeginner" },
  description: "Compare DEXes, P2P markets, instant swaps, and KYC-conditional services by access model, fees, networks, verification, trade-offs, and official sources.",
  alternates: { canonical: `${siteUrl}/exchanges/no-kyc` },
  openGraph: { title: "No-KYC Exchange Directory: Access, Fees & Risks | CryptosBeginner", description: "A source-backed no-KYC exchange directory with transparent access labels, fee context, risk notes, and official provider links.", url: `${siteUrl}/exchanges/no-kyc`, type: "website" },
};

export default function NoKycExchangesPage() {
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "CollectionPage", "@id": `${siteUrl}/exchanges/no-kyc#webpage`, url: `${siteUrl}/exchanges/no-kyc`, name: "No-KYC Exchange Directory: Access, Fees & Risks", description: metadata.description, isPartOf: { "@id": `${siteUrl}/#website` } },
    { "@type": "ItemList", "@id": `${siteUrl}/exchanges/no-kyc#list`, name: "No-KYC exchange and service directory", numberOfItems: noKycDirectoryServices.length, itemListElement: noKycDirectoryServices.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, url: `${siteUrl}/${item.isDex ? "dexes" : "exchanges/no-kyc"}/${item.slug}` })) },
    { "@type": "BreadcrumbList", "@id": `${siteUrl}/exchanges/no-kyc#breadcrumbs`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "No-KYC Exchanges", item: `${siteUrl}/exchanges/no-kyc` }] },
    { "@type": "FAQPage", "@id": `${siteUrl}/exchanges/no-kyc#faq`, mainEntity: faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
  ] };

  return <><Header /><main className="bg-white">
    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.24em] text-lime-300">Privacy-aware comparison · source-backed directory</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">No-KYC does not mean no questions.</h1><p className="mt-5 text-lg leading-8 text-slate-300">Compare wallet-first DEXes, P2P markets, atomic-swap protocols, and instant-swap services by what their public information actually says about access, verification, fees, and settlement.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#directory" className="rounded-full bg-lime-300 px-5 py-3 text-sm font-black text-slate-950 transition hover:bg-lime-200">Browse {noKycDirectoryServices.length} services</a><Link href="/crypto-cards" className="rounded-full border border-white/20 px-5 py-3 text-sm font-black text-white transition hover:border-lime-300 hover:text-lime-300">Compare prepaid cards</Link></div></div></div></section>

    <section className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8"><div className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-800">Important boundary</p><p className="mt-3 text-base leading-8 text-amber-950">This directory does not certify anonymity, legality, safety, or permanent no-KYC access. “No account,” “no ID in the reviewed flow,” “provider-stated no verification,” and “KYC may apply” are different labels. Providers can change policies or respond to transaction-specific risks.</p></div></section>

    <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">How to compare</p><h2 className="mt-3 text-3xl font-black text-slate-950">Four access models, four different risk profiles.</h2></div><div className="mt-8 grid gap-5 md:grid-cols-4"><article className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black text-slate-950">Wallet-first DEX</h3><p className="mt-3 text-sm leading-7 text-slate-600">Smart contracts and a connected wallet replace a standard account, but you control approvals and transaction signing.</p></article><article className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black text-slate-950">P2P market</h3><p className="mt-3 text-sm leading-7 text-slate-600">Offers, payment methods, escrow, and counterparties determine the practical experience.</p></article><article className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black text-slate-950">Instant swap</h3><p className="mt-3 text-sm leading-7 text-slate-600">A deposit address and quote simplify the flow; the provider can still run policy or AML checks.</p></article><article className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black text-slate-950">Conditional access</h3><p className="mt-3 text-sm leading-7 text-slate-600">Some routes begin without documents but can require information for limits, refunds, or compliance review.</p></article></div></div></section>

    <section id="directory" className="scroll-mt-20"><DexDirectory services={noKycDirectoryServices} mode="no-kyc" /></section>

    <section className="mx-auto max-w-4xl px-4 pb-14 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">Before using one</p><h2 className="mt-3 text-3xl font-black text-slate-950">A practical pre-trade checklist</h2><ol className="mt-6 grid gap-4 sm:grid-cols-2"><li className="rounded-2xl border border-slate-200 p-5 text-sm leading-7 text-slate-600"><b className="text-slate-950">1. Check the real domain.</b> Use the provider’s official link and verify the network before connecting a wallet.</li><li className="rounded-2xl border border-slate-200 p-5 text-sm leading-7 text-slate-600"><b className="text-slate-950">2. Compare the final amount.</b> Include service, pool, route, spread, gas, slippage, and payment-rail costs.</li><li className="rounded-2xl border border-slate-200 p-5 text-sm leading-7 text-slate-600"><b className="text-slate-950">3. Understand custody.</b> Determine whether you sign from your own wallet, fund escrow, or send to a provider-controlled address.</li><li className="rounded-2xl border border-slate-200 p-5 text-sm leading-7 text-slate-600"><b className="text-slate-950">4. Keep records.</b> Save quotes, transaction hashes, counterparties, and the provider terms in force at the time.</li></ol></section>

    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-4xl px-4 py-14 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-lime-300">FAQ</p><h2 className="mt-3 text-3xl font-black">No-KYC questions, answered carefully</h2><div className="mt-6 divide-y divide-white/10 rounded-3xl border border-white/10 bg-white/5">{faqs.map((item) => <details key={item.question} className="group p-5"><summary className="cursor-pointer list-none pr-8 font-bold text-white">{item.question}<span className="float-right text-lime-300 transition group-open:rotate-45">＋</span></summary><p className="mt-3 text-sm leading-7 text-slate-300">{item.answer}</p></details>)}</div></div></section>

    <section className="border-t border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm leading-6 text-slate-600">Educational comparison only. KYC, AML, limits, fees, availability, taxes, and legal obligations vary by provider, asset, transaction, and jurisdiction.</p></div></section>
  </main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Footer /></>;
}
