import Image from "next/image";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { reviewedDate, relatedLinks, type Platform } from "./content";
import { ArticleJsonLd } from "./SeoJsonLd";

export function AffiliateCTA({ href, label }: { href: string; label: string }) {
  return <div className="mt-8 rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Disclosed partner link</p><p className="mt-2 text-sm leading-6 text-slate-700">CryptosBeginner may earn a commission if you use this link. It does not change the editorial assessment, comparison order, fees, or risk discussion.</p><a href={href} target="_blank" rel="sponsored nofollow noreferrer" className="mt-4 inline-flex rounded-full bg-indigo-600 px-5 py-3 text-sm font-black text-white hover:bg-indigo-700">{label} ↗</a></div>;
}

export function Figure({ src, alt, caption }: { src: string; alt: string; caption: string }) {
  return <figure className="my-8"><Image src={src} alt={alt} width={1912} height={900} className="h-auto w-full rounded-xl border border-slate-200 bg-slate-950" /><figcaption className="mt-2 text-xs leading-5 text-slate-500">{caption}</figcaption></figure>;
}

export function ArticleShell({ kicker, title, description, path = "/meme-coins", children }: { kicker: string; title: string; description: string; path?: string; children: React.ReactNode }) {
  return <><ArticleJsonLd title={title} description={description} path={path} /><Header /><header className="border-b border-slate-200 bg-slate-50"><div className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><p className="text-sm font-bold text-indigo-700">{kicker}</p><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-5xl">{title}</h1><p className="mt-4 text-lg leading-8 text-slate-700">{description}</p><div className="mt-5 flex flex-wrap gap-3 text-xs font-bold text-slate-500"><span>CryptosBeginner editorial team</span><span>•</span><span>Last reviewed {reviewedDate}</span></div></div></header><main className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><article className="prose prose-slate max-w-none prose-headings:scroll-mt-24 prose-a:text-indigo-700">{children}</article></main><Footer /></>;
}

export function RelatedPages() { return <section className="mt-12 border-t border-slate-200 pt-8"><h2>Related CryptosBeginner pages</h2><p>Continue with the surrounding research and safety resources:</p><div className="grid gap-2 sm:grid-cols-2">{relatedLinks.map(([href, label]) => <Link key={href} href={href} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-indigo-700 hover:bg-indigo-50">{label} →</Link>)}</div></section>; }

export function PlatformProfile({ platform, children }: { platform: Platform; children: React.ReactNode }) { return <ArticleShell path={`/meme-coins/reviews/${platform.slug}`} kicker={`Meme coins · Platform review · ${reviewedDate}`} title={`${platform.name}: features, fees and risk checks`} description={platform.summary}><div className="not-prose mb-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-800">Editorial position</p><p className="mt-2 text-sm leading-6 text-slate-700">This profile describes the platform’s visible features and current public documentation. It is not an endorsement, safety score, or prediction of results.</p></div><h2>TL;DR</h2><p>{platform.summary} {platform.caution}</p><h2>At a glance</h2><div className="not-prose grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-black uppercase text-slate-500">Role</p><p className="mt-1 font-bold text-slate-900">{platform.role}</p></div><div className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-black uppercase text-slate-500">Fee note</p><p className="mt-1 text-sm leading-6 text-slate-700">{platform.fee}</p></div></div>{platform.images.slice(0, 1).map((image) => <Figure key={image.src} {...image} />)}{children}{platform.affiliate && <AffiliateCTA {...platform.affiliate} />}{platform.images.slice(1).map((image) => <Figure key={image.src} {...image} />)}<h2>Official sources and verification</h2><p>These sources support the platform description and fee or terms notes above. Conditions, availability, and pricing can change, so check the provider before connecting a wallet or signing a transaction.</p><ul>{platform.sources.map((source) => <li key={source.href}><a href={source.href} target="_blank" rel="noopener noreferrer">{source.label} ↗</a></li>)}</ul><RelatedPages /></ArticleShell>; }

export function VideoReference({ url, platform, note }: { url: string; platform: string; note: string }) { return <div className="not-prose my-8 overflow-hidden rounded-2xl border border-slate-200 bg-slate-50"><div className="aspect-video bg-slate-900"><iframe className="h-full w-full" src={url.replace("watch?v=", "embed/")} title={`${platform} video reference`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" /></div><div className="p-5"><p className="text-sm font-black text-slate-900">Video reference: {platform}</p><p className="mt-2 text-sm leading-6 text-slate-600">{note}</p><a href={url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-sm font-black text-indigo-700">Open the original video on YouTube ↗</a></div></div>; }
