import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const SITE_URL = "https://www.cryptosbeginner.com";
const PAGE_URL = `${SITE_URL}/wallets`;

const UPDATED = "9 October 2026";
const UPDATED_ISO = "2026-10-09";

export const metadata: Metadata = {
  title: "Crypto Wallets Explained 2026: Types, Safety, and Which to Choose",
  description:
    "Beginner-friendly guide to crypto wallets: hot vs cold, hardware vs software, custodial vs self-custody, plus honest reviews of the SafePal S1, Prokey Optimum, and SecuX Nifty.",
  alternates: {
    canonical: PAGE_URL,
  },
  openGraph: {
    title: "Crypto Wallets Explained 2026: Types, Safety, and Which to Choose",
    description:
      "Wallets store keys, not coins. Learn hot vs cold, hardware vs software, and compare our hands-on hardware wallet reviews.",
    url: PAGE_URL,
    type: "article",
    images: [
      {
        url: `${SITE_URL}/images/wallets-hero.png`,
        width: 1200,
        height: 630,
        alt: "Illustration of hardware, mobile and browser crypto wallets",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Crypto Wallets Explained 2026: Types, Safety, and Which to Choose",
    description:
      "Hot vs cold, hardware vs software, custodial vs self-custody, plus honest hardware wallet reviews.",
    images: [`${SITE_URL}/images/wallets-hero.png`],
  },
};

const faqItems = [
  {
    question: "Do crypto wallets actually store coins?",
    answer:
      "No. A wallet stores your private keys and signs transactions. The coins themselves live on the blockchain as balances attached to addresses. Whoever holds the keys can move the coins, which is why the recovery phrase matters more than the device or app.",
  },
  {
    question: "What is the difference between a hot wallet and a cold wallet?",
    answer:
      "A hot wallet stays connected to the internet, like a phone app or browser extension: convenient for everyday use but exposed to more attack paths. A cold wallet keeps keys offline, typically on a hardware device: slower to use but much safer for long-term holdings.",
  },
  {
    question: "Do beginners need a hardware wallet?",
    answer:
      "Not on day one. A sensible pattern is a reputable exchange account for short-term trading, a mobile wallet for small everyday amounts, and a hardware wallet for savings you would not want to lose. The hardware wallet becomes worth it once your holdings exceed what you would comfortably lose.",
  },
  {
    question: "What is a recovery phrase, and how should I store it?",
    answer:
      "A recovery phrase is a list of 12 to 24 words generated by your wallet that can restore all your keys on any compatible device. Write it on paper or stamp it into metal, store it offline in a secure location, and never photograph it, type it into a website, or share it with anyone claiming to be support.",
  },
  {
    question: "Is it safe to buy a hardware wallet from a marketplace?",
    answer:
      "Buy only from the manufacturer's official store or an authorized reseller. Counterfeit hardware wallets with preinstalled backdoors are a documented threat, and a marketplace discount is never worth the risk. When the device arrives, run the official authenticity check before generating a wallet.",
  },
  {
    question: "What is the difference between custodial and self-custody?",
    answer:
      "Custodial means a company holds your keys, like an exchange account you access with email and password. Self-custody means you hold your own keys via a recovery phrase: nobody can freeze your funds, but nobody can recover them for you either. Most beginners start custodial and graduate to self-custody as their holdings grow.",
  },
] as const;

const reviews = [
  {
    slug: "/wallets/safepal-s1-review",
    image: "/images/safepal-s1-product.png",
    imageAlt: "Two SafePal S1 hardware wallets showing the coin list screen and QR code scanner",
    name: "SafePal S1",
    price: "$49.99",
    verdict:
      "The best value in air-gapped hardware wallets. True offline QR signing and an EAL6+ chip at a budget price, though the experience lives inside the SafePal app.",
    badge: "Best value",
  },
  {
    slug: "/wallets/prokey-review",
    image: "/images/prokey-optimum-device.png",
    imageAlt: "Prokey Optimum hardware wallet showing its secure element chip",
    name: "Prokey Optimum",
    price: "$59",
    verdict:
      "The budget open-source pick. $59, open firmware and hardware, browser-based workflow with no software installs, but Micro-B USB and a dated design.",
    badge: "Best open source",
  },
  {
    slug: "/wallets/secux-nifty-review",
    image: "/images/secux-nifty-box.png",
    imageAlt: "SecuX Nifty hardware wallet box with the device, cable, and recovery sheet",
    name: "SecuX Nifty",
    price: "$199",
    verdict:
      "The NFT-first hardware wallet. A 2.8-inch touchscreen shows your artwork and clear-signs every approval, but NFT support is limited to four chains.",
    badge: "Best for NFTs",
  },
] as const;

function Section({ children }: { children: React.ReactNode }) {
  return <section className="mx-auto max-w-4xl px-4 pb-10">{children}</section>;
}

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-2xl font-semibold text-slate-900">{children}</h2>;
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-4 leading-7 text-slate-700">{children}</p>;
}

export default function WalletsPage() {
  const faqLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqItems.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: { "@type": "Answer", text: item.answer },
    })),
  };

  const itemListLd = {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "Hardware wallet reviews",
    itemListElement: reviews.map((r, i) => ({
      "@type": "ListItem",
      position: i + 1,
      url: `${SITE_URL}${r.slug}`,
      name: `${r.name} review`,
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(itemListLd) }} />
      <Header />
      <main className="min-h-screen bg-white text-slate-950">
        {/* Hero */}
        <section className="border-b border-slate-200 bg-slate-50">
          <div className="mx-auto max-w-4xl px-4 py-12">
            <p className="mb-2 text-sm font-medium text-indigo-600">
              Wallets · Updated {UPDATED}
            </p>
            <h1 className="text-3xl font-extrabold leading-tight text-slate-900 md:text-4xl">
              Crypto Wallets: How They Work and Which Type to Use
            </h1>
            <p className="mt-4 text-lg text-slate-700">
              Wallets do not store coins, they store keys. A hot wallet on your phone is
              convenient for everyday use; a hardware wallet kept offline is safer for savings.
              Most people end up using both, plus an exchange account for trading. This guide
              explains the types, the trade-offs, and which hardware wallets we have reviewed.
            </p>
          </div>
        </section>

        {/* Hero image */}
        <section className="mx-auto max-w-4xl px-4 pt-6">
          <Image
            src="/images/wallets-hero.png"
            alt="Illustration of hardware, mobile and browser crypto wallets"
            width={1200}
            height={630}
            className="w-full rounded-xl border border-slate-200 bg-slate-50 object-cover"
            priority
          />
        </section>

        {/* What is a wallet */}
        <Section>
          <div className="pt-10">
            <H2>What is a crypto wallet really?</H2>
            <P>
              A wallet is a tool that manages your private keys and signs transactions. Coins
              themselves sit on blockchains as balances attached to addresses. When you "send"
              crypto, your wallet signs a transaction that tells the network to move value from
              one address to another.
            </P>
            <P>
              This is why losing a recovery phrase or exposing private keys is fatal. Anyone who
              gets those keys can sign transactions as if they were you and empty the wallet.
              Everything in wallet security flows from that one fact.
            </P>
          </div>
        </Section>

        {/* Types of wallets */}
        <Section>
          <H2>Main wallet types and how they differ</H2>
          <div className="mt-4 grid gap-6 md:grid-cols-2">
            <div>
              <h3 className="text-lg font-semibold text-slate-900">
                Custodial vs self custody
              </h3>
              <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-700">
                <li>
                  Custodial wallets are exchange accounts. The company holds the keys and you
                  log in with email and password.
                </li>
                <li>
                  Self custody wallets give you a recovery phrase or key file. You are
                  responsible for security and backups.
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-900">
                Hot vs cold storage
              </h3>
              <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-700">
                <li>
                  Hot wallets stay connected to the internet. They are convenient for everyday
                  use but exposed to more attack paths.
                </li>
                <li>
                  Cold wallets keep keys offline. They are slower to use but much safer for
                  long term holdings.
                </li>
              </ul>
            </div>
          </div>
        </Section>

        {/* Hardware and software wallets */}
        <Section>
          <H2>Hardware vs software wallets</H2>
          <div className="mt-4 grid gap-6 md:grid-cols-2">
            <div>
              <h3 className="text-lg font-semibold text-slate-900">
                Hardware wallets
              </h3>
              <P>
                Hardware wallets are dedicated devices that store keys in secure chips and sign
                transactions on the device. Long term holders use them to keep keys off phones
                and laptops.
              </P>
              <P>
                They are not perfect. Past incidents have shown data breaches and firmware bugs
                that affected users, which is why you should buy only from official sources and
                keep recovery phrases entirely offline. We have reviewed three hardware wallets
                in depth:
              </P>
              <ul className="mt-3 list-disc space-y-2 pl-5 text-sm font-bold text-indigo-700">
                <li>
                  <Link href="/wallets/safepal-s1-review" className="hover:text-indigo-900">
                    SafePal S1 review: $49.99 air-gapped signing
                  </Link>
                </li>
                <li>
                  <Link href="/wallets/prokey-review" className="hover:text-indigo-900">
                    Prokey Optimum review: $59 open-source wallet
                  </Link>
                </li>
                <li>
                  <Link href="/wallets/secux-nifty-review" className="hover:text-indigo-900">
                    SecuX Nifty review: $199 NFT hardware wallet
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-900">
                Software and mobile wallets
              </h3>
              <P>
                Software wallets run as apps on your phone or browser. Examples include
                MetaMask and mobile wallets such as SafePal. They are ideal for DeFi, NFTs and
                everyday on-chain activity but depend heavily on device security and app
                hygiene.
              </P>
              <P>
                For many people, a simple pattern works: mobile wallet for small spending,
                hardware wallet for savings and exchange account for short term trading.
              </P>
            </div>
          </div>

          {/* Types diagram */}
          <div className="mt-8">
            <Image
              src="/images/wallets-types-diagram.png"
              alt="Diagram comparing exchange accounts, hardware wallets, mobile app wallets and browser wallets"
              width={1200}
              height={800}
              className="w-full rounded-xl border border-slate-200 bg-slate-50 object-cover"
            />
          </div>
        </Section>

        {/* Hardware wallet reviews */}
        <Section>
          <H2>Our hardware wallet reviews</H2>
          <P>
            Research-led reviews, updated October 2026. No scores, no hype: what each device
            does well, where it falls short, and who it suits. For the full comparison, see
            our{" "}
            <Link href="/wallets/best-crypto-wallets-2026" className="font-bold text-indigo-700 hover:text-indigo-900">
              best crypto wallets 2026 guide
            </Link>
            .
          </P>
          <div className="mt-6 grid gap-5 md:grid-cols-3">
            {reviews.map((r) => (
              <article
                key={r.slug}
                className="flex flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"
              >
                <Link href={r.slug} className="block">
                  <Image
                    src={r.image}
                    alt={r.imageAlt}
                    width={800}
                    height={600}
                    className="h-44 w-full object-cover"
                  />
                </Link>
                <div className="flex flex-1 flex-col p-5">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">
                    {r.badge}
                  </p>
                  <h3 className="mt-2 text-lg font-black text-slate-950">
                    <Link href={r.slug} className="hover:text-indigo-700">
                      {r.name}
                    </Link>
                  </h3>
                  <p className="mt-1 text-sm font-bold text-slate-500">{r.price}</p>
                  <p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{r.verdict}</p>
                  <Link
                    href={r.slug}
                    className="mt-4 inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-700"
                  >
                    Read the full review
                  </Link>
                </div>
              </article>
            ))}
          </div>
        </Section>

        {/* Fun facts and incidents */}
        <Section>
          <H2>Fun facts and real incident lessons</H2>
          <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-7 text-slate-700">
            <li>
              Early exchange failures like Mt. Gox pushed many people toward self custody and
              hardware wallets.
            </li>
            <li>
              Data leaks at wallet companies have shown that even marketing databases are
              sensitive, because they reveal who owns hardware wallets.
            </li>
            <li>
              Firmware bugs can affect randomness or signing logic, reminding users that large
              holdings deserve defence in depth, not one device alone.
            </li>
          </ul>
          <P>
            You can explore individual incidents on our{" "}
            <Link href="/security/exchange-incidents" className="text-indigo-700">
              security incidents timeline
            </Link>{" "}
            to see how different wallet and exchange failures unfolded.
          </P>
        </Section>

        {/* CTA */}
        <Section>
          <div className="rounded-2xl border border-slate-200 bg-emerald-50 p-6">
            <h2 className="text-xl font-semibold text-slate-900">
              Simple wallet plan for beginners
            </h2>
            <p className="mt-2 text-sm text-slate-700">
              Trade on a reputable exchange with strong security, withdraw medium and long
              term holdings to a hardware wallet, and keep recovery phrases in offline
              backups.
            </p>
            <div className="mt-4 flex flex-wrap gap-3">
              <a
                href="https://go.cryptosbeginner.com/LedgerWallet"
                target="_blank"
                rel="noopener noreferrer sponsored"
                className="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-slate-800"
              >
                Ledger wallets
              </a>
              <a
                href="https://go.cryptosbeginner.com/TrezorSafe"
                target="_blank"
                rel="noopener noreferrer sponsored"
                className="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-slate-800"
              >
                Trezor wallets
              </a>
            </div>
            <p className="mt-3 text-xs leading-5 text-slate-500">
              Affiliate disclosure: these are affiliate links. We may earn a commission if
              you order through them, at no extra cost to you.
            </p>
          </div>
        </Section>

        {/* FAQ */}
        <Section>
          <p className="text-xs font-black uppercase tracking-[0.16em] text-slate-500">FAQ</p>
          <H2>Wallet questions, answered</H2>
          <div className="mt-6 space-y-3">
            {faqItems.map((item) => (
              <details key={item.question} className="rounded-2xl border border-slate-200 bg-white p-5">
                <summary className="cursor-pointer font-black text-slate-950">{item.question}</summary>
                <p className="mt-3 text-sm leading-7 text-slate-600">{item.answer}</p>
              </details>
            ))}
          </div>
        </Section>

        <section className="border-t border-slate-200 bg-slate-50">
          <div className="mx-auto max-w-4xl px-4 py-8 text-sm text-slate-600">
            <p>
              Educational content only. Not financial or security advice. Think carefully
              about where you keep keys and what would happen if a device or backup failed.
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
