export type ServiceKind = "dex" | "p2p" | "instant-swap" | "aggregator";
export type AccessLabel =
  | "Wallet-first"
  | "No account flow"
  | "Email account"
  | "KYC may apply";

export type DexService = {
  slug: string;
  name: string;
  provider: string;
  kind: ServiceKind;
  categories: string[];
  shortDescription: string;
  editorialSummary: string;
  bestFor: string;
  chains: string[];
  assets: string;
  access: AccessLabel;
  verification: string;
  availability: string;
  fees: string;
  feeSourceUrl?: string;
  sourceUrl: string;
  sourceLabel: string;
  imageUrl: string;
  imageAlt: string;
  logoUrl: string;
  imageSourceNote: string;
  reviewedAt: string;
  caution: string;
  isDex: boolean;
  isNoKycCandidate: boolean;
  isKycConditional?: boolean;
  pros: string[];
  cons: string[];
  faqs: { question: string; answer: string }[];
};

const faq = (service: DexService): DexService["faqs"] => [
  {
    question: `How does ${service.name} charge users?`,
    answer: service.fees,
  },
  {
    question: `Does ${service.name} require KYC?`,
    answer: service.verification,
  },
  {
    question: `Which networks or assets does ${service.name} support?`,
    answer: `${service.name} describes support for ${service.chains.join(", ")}. The current network and token list can change, so confirm the live interface before signing a transaction.`,
  },
  {
    question: `What should I check before using ${service.name}?`,
    answer: `${service.caution} Compare the route, slippage, network fee, contract address, and local obligations before using the service. This profile is educational comparison content, not a personal recommendation.`,
  },
];

const service = (entry: Omit<DexService, "faqs">): DexService => ({
  ...entry,
  faqs: [],
});

export const dexServices: DexService[] = [
  service({
    slug: "uniswap",
    name: "Uniswap",
    provider: "Uniswap Labs / Uniswap Protocol",
    kind: "dex",
    categories: ["AMM", "DEX", "multichain"],
    shortDescription: "A wallet-connected automated market maker for token swaps across major EVM networks.",
    editorialSummary: "Uniswap combines a widely used wallet interface with permissionless liquidity pools deployed across several networks. The interface, pool contracts, token permissions, and network all matter when comparing a route.",
    bestFor: "EVM users who want broad token-pool coverage and a familiar wallet-first swap flow.",
    chains: ["Ethereum", "Base", "Arbitrum", "Polygon", "Unichain"],
    assets: "ERC-20 and network-native assets available in the selected pools",
    access: "Wallet-first",
    verification: "The reviewed interface connects a wallet rather than creating a conventional exchange account; wallet, token, network, and legal obligations still apply.",
    availability: "Network and jurisdiction dependent; the protocol and interface are separate layers.",
    fees: "Pool fees, any applicable interface fee, price impact, and network gas depend on the route and network. Review the quote before signing.",
    feeSourceUrl: "https://support.uniswap.org/hc/en-us/articles/8376057376013-What-is-the-Uniswap-Labs-interface-fee",
    sourceUrl: "https://uniswap.org/",
    sourceLabel: "Uniswap official site",
    imageUrl: "https://app.uniswap.org/images/1200x630_Rich_Link_Preview_Image.png",
    imageAlt: "Uniswap official brand artwork",
    logoUrl: "https://app.uniswap.org/favicon.png",
    imageSourceNote: "Official Uniswap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A wallet connection does not make a token safe. Check the contract, pool liquidity, price impact, approvals, and the network selected.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Wallet-first workflow", "Broad EVM ecosystem", "Permissionless pool design"],
    cons: ["Network gas can vary", "Pool liquidity and token risk differ", "Quotes are not guaranteed until settlement"],
  }),
  service({
    slug: "jupiter",
    name: "Jupiter",
    provider: "Jupiter",
    kind: "aggregator",
    categories: ["DEX aggregator", "Solana", "on-chain finance"],
    shortDescription: "A Solana-focused on-chain finance interface with swap routing, perps, lending, and portfolio tools.",
    editorialSummary: "Jupiter began as a Solana swap aggregator and now presents a broader collection of on-chain products. Its key comparison point is route selection across liquidity sources rather than a single pool model.",
    bestFor: "Solana users comparing routed spot swaps and additional on-chain finance tools in one interface.",
    chains: ["Solana"],
    assets: "Solana tokens available through the live route and liquidity sources",
    access: "Wallet-first",
    verification: "The reviewed interface presents wallet connection and on-chain signing rather than a standard exchange account; product and jurisdiction terms can differ by feature.",
    availability: "Feature, network, and location dependent; verify the live interface before use.",
    fees: "Route, priority, liquidity-source, and Solana network costs vary. Inspect the quote and transaction settings before signing.",
    feeSourceUrl: "https://station.jup.ag/docs/apis/fees",
    sourceUrl: "https://jup.ag/",
    sourceLabel: "Jupiter official interface",
    imageUrl: "https://jup.ag/meta-og/jupiter-meta-main.webp",
    imageAlt: "Jupiter official brand artwork",
    logoUrl: "https://jup.ag/favicon.svg",
    imageSourceNote: "Official Jupiter-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Jupiter exposes several products beyond spot swaps. Read the feature-specific terms and verify token addresses before signing.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Solana-native routing", "Multiple on-chain products", "Wallet-connected workflow"],
    cons: ["Primarily Solana-focused", "Feature risk varies by product", "Network congestion can affect execution"],
  }),
  service({
    slug: "pancakeswap",
    name: "PancakeSwap",
    provider: "PancakeSwap",
    kind: "dex",
    categories: ["AMM", "DEX", "multichain"],
    shortDescription: "A multichain DEX with swaps, liquidity, bridging, perpetuals, and other on-chain features.",
    editorialSummary: "PancakeSwap positions itself as a multichain trading and liquidity venue. Its official site advertises 11-chain coverage and swap fees as low as 0.01% in a product context; the actual route, pool, and network costs must be checked live.",
    bestFor: "Users comparing multichain AMM access and a broader DeFi feature set.",
    chains: ["BNB Chain", "Ethereum", "Base", "Arbitrum", "Polygon"],
    assets: "Assets available through the selected chain, pool, and feature",
    access: "Wallet-first",
    verification: "The reviewed DEX interface uses wallet connection; products such as bridging or fiat purchase can have separate provider requirements.",
    availability: "Chain, feature, and jurisdiction dependent.",
    fees: "The provider advertises swap fees as low as 0.01% on its reviewed homepage. Pool fees, routing, price impact, and network gas vary by trade.",
    feeSourceUrl: "https://docs.pancakeswap.finance/products/pancakeswap-exchange/trade",
    sourceUrl: "https://pancakeswap.finance/",
    sourceLabel: "PancakeSwap official site",
    imageUrl: "https://assets.pancakeswap.finance/web/og/v2/hero.jpg",
    imageAlt: "PancakeSwap official brand artwork",
    logoUrl: "https://pancakeswap.finance/favicon.ico",
    imageSourceNote: "Official PancakeSwap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "“As low as” fee language is not a quote for every pool or transaction. Check the selected route, token contract, price impact, and gas.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Multichain coverage", "Swap and liquidity tools", "Wallet-first access"],
    cons: ["Costs vary by pool and chain", "Many product surfaces add complexity", "Permissionless tokens can be risky"],
  }),
  service({
    slug: "curve",
    name: "Curve",
    provider: "Curve Finance",
    kind: "dex",
    categories: ["AMM", "stablecoin swaps", "DEX"],
    shortDescription: "A pool-based DEX interface built around Curve’s deployed smart contracts and liquidity markets.",
    editorialSummary: "Curve’s interface connects users to a set of deployed smart-contract pools. Pool design and asset correlation are central to the comparison: a stablecoin pool behaves differently from a volatile-asset pool.",
    bestFor: "Users assessing stable-asset and specialized liquidity pools rather than a general exchange order book.",
    chains: ["Ethereum and supported Curve deployments"],
    assets: "Pool-specific assets shown in the live Curve interface",
    access: "Wallet-first",
    verification: "The frontend connects to deployed smart contracts through a wallet; no conventional exchange profile is needed for the reviewed flow.",
    availability: "Pool, network, interface, and jurisdiction dependent.",
    fees: "Pool fees and network gas vary by deployment and selected market. Use the live pool interface and transaction preview.",
    sourceUrl: "https://curve.fi/",
    sourceLabel: "Curve official interface",
    imageUrl: "https://cdn.jsdelivr.net/gh/curvefi/curve-assets/branding/logo.png",
    imageAlt: "Curve Finance official logo",
    logoUrl: "https://curve.fi/favicon-32x32.png",
    imageSourceNote: "Official Curve-hosted or project-maintained asset",
    reviewedAt: "2026-08-27",
    caution: "Stable-value pools can still experience depegs, smart-contract failures, liquidity changes, and price impact.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Specialized pool designs", "Wallet-connected swaps", "Deep DeFi composability"],
    cons: ["Pool risk differs materially", "Gas and pool fees vary", "Interface can be harder for first-time users"],
  }),
  service({
    slug: "1inch",
    name: "1inch",
    provider: "1inch Network",
    kind: "aggregator",
    categories: ["DEX aggregator", "cross-chain", "MEV tools"],
    shortDescription: "A DEX aggregator that searches liquidity across networks and routes swaps through multiple venues.",
    editorialSummary: "1inch is best understood as a routing layer rather than one liquidity pool. Its comparison value comes from route selection, cross-chain functionality, wallet tools, and security features, while the quote remains the source of truth for a specific trade.",
    bestFor: "Traders comparing routes across multiple decentralized venues and supported networks.",
    chains: ["13+ networks advertised, including Ethereum, Base, Arbitrum, Polygon, Solana"],
    assets: "Assets supported by the selected route and network",
    access: "Wallet-first",
    verification: "The reviewed product uses wallet and network connections; 1inch products and integrations may have feature-specific requirements.",
    availability: "Route, network, asset, interface, and jurisdiction dependent.",
    fees: "The total depends on route, gas, liquidity-source costs, and any applicable network or product fee. Review the final quote before signing.",
    feeSourceUrl: "https://help.1inch.io/en/articles/4585109-what-are-1inch-network-fees",
    sourceUrl: "https://1inch.io/",
    sourceLabel: "1inch official site",
    imageUrl: "https://1inch.com/assets/1inch-com-cover.png",
    imageAlt: "1inch official brand artwork",
    logoUrl: "https://1inch.com/favicon/favicon.svg",
    imageSourceNote: "Official 1inch-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A routed quote can change with market conditions and gas. Verify the destination token, spender approval, slippage, and network.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Aggregates multiple DEXes", "Cross-chain tooling", "Route comparison"],
    cons: ["Quote complexity can confuse beginners", "Route and gas costs vary", "Token and smart-contract risk remains"],
  }),
  service({
    slug: "cow-swap",
    name: "CoW Swap",
    provider: "CoW Protocol / CoW DAO",
    kind: "aggregator",
    categories: ["intent-based", "DEX aggregator", "MEV protection"],
    shortDescription: "An Ethereum-focused DEX interface and protocol built around intent-based order settlement and routing.",
    editorialSummary: "CoW Swap describes itself as a user-protective product built on the CoW Protocol, an open-source, permissionless DEX aggregation protocol. The distinctive comparison point is its intent and solver model rather than a traditional single-pool interface.",
    bestFor: "Ethereum users who want to compare intent-based execution and MEV-aware routing.",
    chains: ["Ethereum and supported CoW deployments"],
    assets: "Assets available through the current CoW Swap market and route",
    access: "Wallet-first",
    verification: "The reviewed product uses wallet-based trading; no conventional exchange account is presented for the swap flow.",
    availability: "Network, market, solver, and jurisdiction dependent.",
    fees: "The effective price reflects the route, solver execution, and network conditions. Read the order preview rather than assuming a universal fee.",
    sourceUrl: "https://cow.fi/",
    sourceLabel: "CoW DAO official site",
    imageUrl: "https://cow.fi/images/og-meta-cowdao.png",
    imageAlt: "CoW DAO official brand artwork",
    logoUrl: "https://cow.fi/favicon-light-mode.png",
    imageSourceNote: "Official CoW-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "MEV-aware execution does not remove token, approval, smart-contract, network, or price risk.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Intent-based execution", "Open-source protocol", "MEV-aware product focus"],
    cons: ["Ethereum gas can be material", "Execution model differs from a simple AMM", "Market and solver conditions vary"],
  }),
  service({
    slug: "raydium",
    name: "Raydium",
    provider: "Raydium",
    kind: "dex",
    categories: ["AMM", "Solana", "DEX"],
    shortDescription: "A Solana-native DEX interface for token swaps and liquidity markets.",
    editorialSummary: "Raydium is a Solana-native liquidity venue. The most important comparison variables are the selected pool, token contract, pool depth, price impact, and Solana transaction conditions.",
    bestFor: "Solana users comparing token-pool liquidity and a native DEX interface.",
    chains: ["Solana"],
    assets: "Solana tokens available in the selected pool",
    access: "Wallet-first",
    verification: "The reviewed interface uses wallet connection and on-chain signing rather than a conventional exchange account.",
    availability: "Solana network, token, interface, and jurisdiction dependent.",
    fees: "Pool trading fees, routing, price impact, and Solana network costs vary by market. Inspect the live quote.",
    sourceUrl: "https://raydium.io/",
    sourceLabel: "Raydium official site",
    imageUrl: "https://img-v1.raydium.io/share/7be7ee6c-56b2-451e-a010-6c21e0db2ee5.png",
    imageAlt: "Raydium official brand artwork",
    logoUrl: "https://raydium.io/favicon.ico",
    imageSourceNote: "Official Raydium-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Solana meme-token markets can be thin or manipulated. Verify contracts and start with a small test transaction.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Solana-native experience", "Wallet-first trading", "Broad token-pool access"],
    cons: ["Token quality varies widely", "Pool depth can be thin", "Solana network conditions affect execution"],
  }),
  service({
    slug: "dydx",
    name: "dYdX",
    provider: "dYdX",
    kind: "dex",
    categories: ["perpetuals", "order book", "DEX"],
    shortDescription: "A decentralized trading platform focused on perpetual markets, order books, and margin mechanics.",
    editorialSummary: "dYdX is not a simple spot-swap directory entry: its official trading interface emphasizes perpetual markets, funding, leverage, open interest, and liquidation prices. It belongs in a DEX comparison, but users should understand the derivatives risk first.",
    bestFor: "Experienced users comparing decentralized perpetual trading rather than basic token swaps.",
    chains: ["dYdX Chain / supported dYdX markets"],
    assets: "Perpetual markets listed in the current dYdX interface",
    access: "Wallet-first",
    verification: "The trading interface uses wallet and account infrastructure specific to dYdX; product access and eligibility can vary by location and feature.",
    availability: "Market, jurisdiction, product, and account eligibility dependent.",
    fees: "Maker/taker fees, funding, spread, and liquidation conditions depend on the market, volume tier, and position. Use the live fee schedule.",
    feeSourceUrl: "https://docs.dydx.trade/fees",
    sourceUrl: "https://dydx.trade/",
    sourceLabel: "dYdX official trading interface",
    imageUrl: "https://dydx.trade//og-image.png",
    imageAlt: "dYdX official brand artwork",
    logoUrl: "https://dydx.trade/favicon.svg",
    imageSourceNote: "Official dYdX-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Leverage can magnify losses. Funding, margin, liquidation, oracle, and smart-contract risks are separate from spot-swap risk.",
    isDex: true,
    isNoKycCandidate: false,
    pros: ["Decentralized derivatives interface", "Order-book trading model", "Visible funding and margin fields"],
    cons: ["High derivatives complexity", "Liquidation risk", "Eligibility and market availability vary"],
  }),
  service({
    slug: "aerodrome",
    name: "Aerodrome",
    provider: "Aerodrome Finance",
    kind: "dex",
    categories: ["AMM", "Base", "DEX"],
    shortDescription: "A Base-focused liquidity hub for swaps, pools, and protocol-governed markets.",
    editorialSummary: "Aerodrome’s official description positions it as a central liquidity hub on Base. A useful comparison should focus on Base gas, pool selection, liquidity depth, and the difference between swapping and providing liquidity.",
    bestFor: "Base users comparing local liquidity pools and DeFi market incentives.",
    chains: ["Base"],
    assets: "Base assets and pools listed in the live Aerodrome interface",
    access: "Wallet-first",
    verification: "The reviewed interface uses wallet connection and on-chain signing; liquidity or governance features may have separate risks.",
    availability: "Base network, pool, interface, and jurisdiction dependent.",
    fees: "Pool, route, price-impact, and Base network costs vary. Check the live swap or liquidity transaction preview.",
    sourceUrl: "https://aerodrome.finance/",
    sourceLabel: "Aerodrome official site",
    imageUrl: "https://aerodrome.finance/images/aero-banner.png",
    imageAlt: "Aerodrome Finance official brand artwork",
    logoUrl: "https://aerodrome.finance/images/AERO/favicon.ico",
    imageSourceNote: "Official Aerodrome-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Liquidity incentives are not guaranteed returns. Assess pool composition, smart contracts, impermanent loss, and token risk separately.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Base-native liquidity focus", "Wallet-first access", "Swap and liquidity markets"],
    cons: ["Base-only scope", "Pool and token risk varies", "Liquidity incentives can change"],
  }),
  service({
    slug: "basicswap",
    name: "BasicSwap",
    provider: "BasicSwapDEX",
    kind: "p2p",
    categories: ["atomic swaps", "P2P", "DEX"],
    shortDescription: "An open protocol for peer-to-peer atomic swaps across Bitcoin, Monero, and other networks.",
    editorialSummary: "BasicSwap describes a distributed order book where traders meet directly and settle atomic swaps without a custodian or protocol fee. Its desktop/mobile installation model makes it different from a browser-only AMM.",
    bestFor: "Users who understand atomic swaps and want a non-custodial cross-chain P2P model.",
    chains: ["Bitcoin", "Monero", "Litecoin", "Firo", "Particl", "12+ networks advertised"],
    assets: "14 chains advertised on the reviewed official page; confirm the current live list",
    access: "No account flow",
    verification: "The provider states no signup or form is needed for the reviewed desktop/mobile flow; AML, legal, network, and counterparty considerations still apply.",
    availability: "Supported network, client, counterparty, and jurisdiction dependent.",
    fees: "BasicSwap states 0% protocol fee; users still pay underlying network costs and may face offer-spread or counterparty economics.",
    feeSourceUrl: "https://docs.basicswapdex.com/docs/intro",
    sourceUrl: "https://basicswapdex.com/",
    sourceLabel: "BasicSwap official site",
    imageUrl: "https://basicswapdex.com/images/og-home.png",
    imageAlt: "BasicSwap official brand artwork",
    logoUrl: "https://basicswapdex.com/images/favicon-32.png",
    imageSourceNote: "Official BasicSwap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Atomic swaps and P2P offers require technical and counterparty understanding. No protocol fee does not mean no transaction cost or risk.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Atomic-swap model", "Non-custodial design", "Provider states 0% protocol fee"],
    cons: ["More technical setup", "Offer liquidity can vary", "Counterparty and network risk remain"],
  }),
  service({
    slug: "bisq",
    name: "Bisq",
    provider: "Bisq Network",
    kind: "p2p",
    categories: ["P2P", "Bitcoin", "open source"],
    shortDescription: "An open-source desktop P2P network for buying and selling Bitcoin without a central order-matching account.",
    editorialSummary: "Bisq describes a peer-to-peer network using open-source desktop software, local data, Tor, and 2-of-2 multisig deposits. It is a P2P Bitcoin market, not a conventional instant-swap or custodial exchange.",
    bestFor: "Bitcoin users who value open-source desktop software and P2P offers over convenience.",
    chains: ["Bitcoin"],
    assets: "Bitcoin against national currencies or supported alternative cryptocurrencies",
    access: "No account flow",
    verification: "Bisq states no registration is required in the reviewed product description and presents a no-identity-verification feature; payment method, legal, and counterparty conditions still apply.",
    availability: "Offer, payment method, software, and jurisdiction dependent.",
    fees: "Trading, mining, and payment-rail costs apply according to the live Bisq fee documentation and selected offer; there is no universal one-line fee for every trade.",
    feeSourceUrl: "https://bisq.wiki/Trading_fees",
    sourceUrl: "https://bisq.network/",
    sourceLabel: "Bisq official site",
    imageUrl: "https://bisq.network/images/bisq-og.jpg",
    imageAlt: "Bisq official brand artwork",
    logoUrl: "https://bisq.network/images/bisq-fav.png",
    imageSourceNote: "Official Bisq-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "No registration is not the same as legal anonymity or zero risk. Read the offer, payment method, escrow, dispute, and fee documentation first.",
    isDex: false,
    isNoKycCandidate: true,
    pros: ["Open-source desktop software", "P2P and non-custodial design", "Tor and multisig features"],
    cons: ["Bitcoin-centric", "Offers and payment methods vary", "More setup than a web swap"],
  }),
  service({
    slug: "robosats",
    name: "RoboSats",
    provider: "RoboSats",
    kind: "p2p",
    categories: ["P2P", "Lightning", "Bitcoin"],
    shortDescription: "A Tor-oriented Lightning P2P market for exchanging Bitcoin with national currencies.",
    editorialSummary: "RoboSats presents a simple P2P workflow built around Lightning Hodl invoices, one-time robot identities, Tor access, and open-source code. The offer, payment method, and network conditions matter more than a single headline fee.",
    bestFor: "Bitcoin users who understand Lightning and want a P2P workflow with one-time identities.",
    chains: ["Bitcoin", "Lightning"],
    assets: "Bitcoin and national-currency payment methods listed in the live market",
    access: "No account flow",
    verification: "The provider describes the reviewed flow as simple and KYC-free with a random single-use Robot identity; laws, payment counterparties, and operational policies still apply.",
    availability: "Tor access, offer, payment method, and jurisdiction dependent.",
    fees: "Offer premiums, Lightning routing, bond/escrow mechanics, and payment-rail costs vary by trade; the provider does not present one universal transaction fee on the reviewed homepage.",
    sourceUrl: "https://learn.robosats.org/",
    sourceLabel: "RoboSats official learning site",
    imageUrl: "https://learn.robosats.org/assets/images/misc/feature-private.png",
    imageAlt: "RoboSats official privacy feature artwork",
    logoUrl: "https://learn.robosats.org/assets/images/misc/feature-private.png",
    imageSourceNote: "Official RoboSats-hosted product artwork",
    reviewedAt: "2026-08-27",
    caution: "Tor and a one-time identity do not remove payment, counterparty, Lightning, legal, or tax obligations.",
    isDex: false,
    isNoKycCandidate: true,
    pros: ["Lightning-focused P2P flow", "Open-source project", "One-time Robot identities"],
    cons: ["Bitcoin/Lightning scope", "Payment method risk varies", "Tor and Lightning add operational steps"],
  }),
  service({
    slug: "hodl-hodl",
    name: "Hodl Hodl",
    provider: "Hodlex Ltd",
    kind: "p2p",
    categories: ["P2P", "Bitcoin", "multisig escrow"],
    shortDescription: "A non-custodial Bitcoin P2P marketplace using multisig escrow and user-selected payment methods.",
    editorialSummary: "Hodl Hodl combines an account-based offer marketplace with multisig escrow. Its official site says no verification is required in the product section, while its FAQ says users sign up with email; that distinction matters when comparing privacy claims.",
    bestFor: "Bitcoin users comparing P2P offers, payment methods, and non-custodial escrow.",
    chains: ["Bitcoin", "Lightning / Arkade features where offered"],
    assets: "Bitcoin; payment methods and currencies vary by offer",
    access: "Email account",
    verification: "The provider says no verification is required in the reviewed product section, but the FAQ describes email sign-up. Individual offers, laws, and policy checks can differ.",
    availability: "Offer, payment method, account, and jurisdiction dependent.",
    fees: "The provider states that a trading fee is split between buyer and seller and deducted from the BTC amount; see the live fee FAQ for current details.",
    feeSourceUrl: "https://hodlhodl.com/faq#how_do_fees_work",
    sourceUrl: "https://hodlhodl.com/",
    sourceLabel: "Hodl Hodl official site",
    imageUrl: "https://hodlhodl.com/assets/link-preview-image.png",
    imageAlt: "Hodl Hodl official brand artwork",
    logoUrl: "https://hodlhodl.com/assets/favicon.ico",
    imageSourceNote: "Official Hodl Hodl-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "P2P payment methods can create fraud, chargeback, sanctions, and counterparty risks. Read the offer and escrow conditions carefully.",
    isDex: false,
    isNoKycCandidate: true,
    pros: ["Non-custodial multisig escrow", "Many payment methods", "Provider-published fee FAQ"],
    cons: ["Bitcoin-only core market", "Email account is still required", "Counterparty and payment risk vary"],
  }),
  service({
    slug: "sideshift",
    name: "SideShift.ai",
    provider: "SideShift.ai",
    kind: "instant-swap",
    categories: ["instant swap", "direct-to-wallet", "multichain"],
    shortDescription: "A direct-to-wallet crypto swap service covering BTC, ETH, SOL, and other assets across multiple networks.",
    editorialSummary: "SideShift’s reviewed interface is organized around choosing a pair, sending a deposit, and receiving the swapped asset directly in a wallet. It is closer to an instant swap service than a liquidity-pool DEX.",
    bestFor: "Users comparing direct-to-wallet swap workflows without a conventional trading screen.",
    chains: ["45+ networks advertised"],
    assets: "300+ coins advertised; route and network support vary",
    access: "No account flow",
    verification: "The reviewed page shows a direct-to-wallet flow without a visible standard account step; provider compliance checks or transaction reviews may still apply.",
    availability: "Asset, route, network, jurisdiction, and compliance-review dependent.",
    fees: "The exchange quote and selected rate mode determine the effective rate; network and service costs vary by route. Use the live quote as the source of truth.",
    sourceUrl: "https://sideshift.ai/",
    sourceLabel: "SideShift.ai official site",
    imageUrl: "https://sideshift.ai/meta/ogimage.jpg",
    imageAlt: "SideShift.ai official brand artwork",
    logoUrl: "https://sideshift.ai/favicon.svg",
    imageSourceNote: "Official SideShift-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A direct-to-wallet flow does not guarantee a fixed rate, settlement time, or absence of compliance review. Verify the deposit address and network.",
    isDex: false,
    isNoKycCandidate: true,
    isKycConditional: true,
    pros: ["Direct-to-wallet flow", "Broad advertised asset coverage", "Fixed and variable rate modes"],
    cons: ["Quote and route costs vary", "Compliance reviews may occur", "Not a self-custody protocol"],
  }),
  service({
    slug: "changenow",
    name: "ChangeNOW",
    provider: "ChangeNOW",
    kind: "instant-swap",
    categories: ["instant swap", "multichain", "KYC-conditional"],
    shortDescription: "An instant crypto exchange service with a broad asset list and variable route pricing.",
    editorialSummary: "ChangeNOW is included as a KYC-conditional instant-swap comparison rather than a guaranteed no-KYC provider. The official site emphasizes fast exchange and a broad asset range, while compliance checks can depend on transaction conditions.",
    bestFor: "Users comparing a simple instant-swap interface and willing to review compliance and rate conditions.",
    chains: ["Multiple networks; live asset list varies"],
    assets: "Broad cryptocurrency selection advertised by the provider",
    access: "KYC may apply",
    verification: "No account may be available for some flows, but the provider can request verification or additional information under its policies, limits, or compliance controls.",
    availability: "Asset, route, transaction, jurisdiction, and compliance dependent.",
    fees: "The effective service fee is reflected in the selected fixed or floating exchange quote, alongside network costs. Compare the final receive amount before sending.",
    sourceUrl: "https://changenow.io/",
    sourceLabel: "ChangeNOW official site",
    imageUrl: "https://changenow.io/images/site-image.png",
    imageAlt: "ChangeNOW official brand artwork",
    logoUrl: "https://changenow.io/images/icons/favicon-32x32.png",
    imageSourceNote: "Official ChangeNOW-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Do not treat an instant-swap flow as a promise of no KYC. Read the provider’s terms and compliance policy before sending funds.",
    isDex: false,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["Simple swap workflow", "Broad advertised asset coverage", "Fixed/floating quote options"],
    cons: ["KYC may be triggered", "Rate includes route economics", "Settlement and support conditions vary"],
  }),
  service({
    slug: "simpleswap",
    name: "SimpleSwap",
    provider: "SimpleSwap",
    kind: "instant-swap",
    categories: ["instant swap", "multichain", "KYC-conditional"],
    shortDescription: "An instant crypto swap service with fixed and floating rate paths across a large asset list.",
    editorialSummary: "SimpleSwap is useful as a comparison point for instant swaps rather than a permissionless DEX. Its official page advertises a large cryptocurrency selection; route availability, pricing, and verification can depend on the transaction.",
    bestFor: "Users who want a straightforward swap interface and will check the final route and compliance terms.",
    chains: ["Multiple networks; live support varies"],
    assets: "2,800+ cryptocurrencies advertised; confirm the current pair list",
    access: "KYC may apply",
    verification: "The provider offers swap flows that may not require an account, but KYC or transaction review can still apply under policy or risk controls.",
    availability: "Pair, network, transaction, jurisdiction, and compliance dependent.",
    fees: "Fixed or floating quotes include the route’s service economics and network costs. Compare the receive amount and review the transaction screen before sending.",
    sourceUrl: "https://simpleswap.io/",
    sourceLabel: "SimpleSwap official site",
    imageUrl: "https://edge.simpleswap.io/images/meta/V1.png",
    imageAlt: "SimpleSwap official brand artwork",
    logoUrl: "https://simpleswap.io/favicon-32x32.png",
    imageSourceNote: "Official SimpleSwap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A no-account path is not a permanent no-KYC guarantee. Keep transaction records and read the provider’s current terms.",
    isDex: false,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["Simple fixed/floating swap flow", "Large advertised asset list", "No conventional order book"],
    cons: ["KYC may be triggered", "Quote economics vary", "Not a self-custody protocol"],
  }),
  service({
    slug: "orangefren",
    name: "OrangeFren",
    provider: "OrangeFren",
    kind: "aggregator",
    categories: ["exchange aggregator", "prepaid cards", "privacy-focused"],
    shortDescription: "A transaction-first comparison service for instant exchanges and prepaid cards, with privacy-oriented filters.",
    editorialSummary: "OrangeFren’s public interface organizes exchange comparisons around a transaction pair and presents prepaid cards as a separate category. It is included here as an aggregator and research reference, not as a promise that every listed route is available without checks.",
    bestFor: "Users comparing multiple instant-swap offers or privacy-oriented prepaid-card options in one interface.",
    chains: ["Varies by listed service and transaction pair"],
    assets: "Varies by provider and selected transaction",
    access: "No account flow",
    verification: "The reviewed public flow presents transaction search without a visible account requirement; individual providers and transactions can impose their own checks.",
    availability: "Offer, provider, asset pair, jurisdiction, and compliance dependent.",
    fees: "Displayed rates and transaction fees depend on the selected provider and pair. Compare the final receive amount, not only the headline rate.",
    sourceUrl: "https://orangefren.com/",
    sourceLabel: "OrangeFren official site",
    imageUrl: "https://orangefren.com/static/logos/OrangeFren%20Logo-11.webp",
    imageAlt: "OrangeFren official logo",
    logoUrl: "https://orangefren.com/static/logos/OrangeFren%20Logo-13.webp",
    imageSourceNote: "Official OrangeFren-hosted logo asset",
    reviewedAt: "2026-08-27",
    caution: "An aggregator is not the counterparty for every listed trade. Check the selected provider’s terms, KYC policy, refund policy, and regional availability.",
    isDex: false,
    isNoKycCandidate: true,
    isKycConditional: true,
    pros: ["Transaction-first comparison", "Separate prepaid-card category", "Rate and policy filters"],
    cons: ["Listed-provider quality varies", "Rates can include hidden route economics", "Individual providers may request checks"],
  }),
];

for (const item of dexServices) item.faqs = faq(item);

export const dexServicesBySlug = new Map(dexServices.map((item) => [item.slug, item]));
export const dexDirectoryServices = dexServices.filter((item) => item.isDex || item.kind === "aggregator");
export const noKycDirectoryServices = dexServices.filter((item) => item.isNoKycCandidate || item.isKycConditional);
export const dexDetailSlugs = dexServices.filter((item) => item.isDex).map((item) => item.slug);
export const noKycDetailSlugs = noKycDirectoryServices.map((item) => item.slug);

export function getDexService(slug: string) {
  return dexServicesBySlug.get(slug);
}
