export type ServiceKind = "dex" | "p2p" | "instant-swap" | "aggregator" | "prediction-market";
export type AccessLabel =
  | "Wallet-first"
  | "No account flow"
  | "Email account"
  | "KYC may apply"
  | "Research profile";

export type DexService = {
  slug: string;
  name: string;
  provider: string;
  kind: ServiceKind;
  categories: string[];
  shortDescription: string;
  editorialSummary: string;
  bestFor: string;
  chains: string[];
  assets: string;
  access: AccessLabel;
  verification: string;
  verificationLabel?: string;
  availability: string;
  fees: string;
  feeSourceUrl?: string;
  partnerUrl?: string;
  partnerLabel?: string;
  sourceUrl: string;
  sourceLabel: string;
  imageUrl: string;
  imageAlt: string;
  logoUrl: string;
  imageSourceNote: string;
  galleryImages?: { url: string; alt: string; source: string }[];
  stats?: {
    coinGeckoExchangeId?: string;
    geckoTerminal?: { network: string; dexId: string };
  };
  reviewedAt: string;
  caution: string;
  isDex: boolean;
  isNoKycCandidate: boolean;
  isKycConditional?: boolean;
  pros: string[];
  cons: string[];
  faqs: { question: string; answer: string }[];
};

const faq = (service: DexService): DexService["faqs"] => service.kind === "prediction-market"
  ? [
      { question: `How does ${service.name} charge users?`, answer: service.fees },
      { question: `How are ${service.name} markets resolved?`, answer: service.verification },
      { question: `What does a ${service.name} position represent?`, answer: `${service.name} uses outcome-based markets rather than a conventional token-swap pair. Read the market wording, resolution source, close time, and settlement terms before taking a position.` },
      { question: `What should I check before using ${service.name}?`, answer: `${service.caution} Consider market-resolution, collateral, smart-contract, liquidity, and loss risks. This profile is educational comparison content, not a personal recommendation.` },
    ]
  : [
      {
        question: `How does ${service.name} charge users?`,
        answer: service.fees,
      },
      {
        question: `Does ${service.name} require KYC?`,
        answer: service.verification,
      },
      {
        question: `Which networks or assets does ${service.name} support?`,
        answer: `${service.name} describes support for ${service.chains.join(", ")}. The current network and token list can change, so confirm the live interface before signing a transaction.`,
      },
      {
        question: `What should I check before using ${service.name}?`,
        answer: `${service.caution} Compare the route, slippage, network fee, contract address, and local obligations before using the service. This profile is educational comparison content, not a personal recommendation.`,
      },
    ];

const service = (entry: Omit<DexService, "faqs">): DexService => ({
  ...entry,
  faqs: [],
});

export const dexServices: DexService[] = [
  service({
    slug: "uniswap",
    name: "Uniswap",
    provider: "Uniswap Labs / Uniswap Protocol",
    kind: "dex",
    categories: ["AMM", "DEX", "multichain"],
    shortDescription: "A wallet-connected automated market maker for token swaps across major EVM networks.",
    editorialSummary: "Uniswap combines a widely used wallet interface with permissionless liquidity pools deployed across several networks. The interface, pool contracts, token permissions, and network all matter when comparing a route.",
    bestFor: "EVM users who want broad token-pool coverage and a familiar wallet-first swap flow.",
    chains: ["Ethereum", "Base", "Arbitrum", "Polygon", "Unichain"],
    assets: "ERC-20 and network-native assets available in the selected pools",
    access: "Wallet-first",
    verification: "The reviewed interface connects a wallet rather than creating a conventional exchange account; wallet, token, network, and legal obligations still apply.",
    availability: "Network and jurisdiction dependent; the protocol and interface are separate layers.",
    fees: "Pool fees, any applicable interface fee, price impact, and network gas depend on the route and network. Review the quote before signing.",
    feeSourceUrl: "https://support.uniswap.org/hc/en-us/articles/8376057376013-What-is-the-Uniswap-Labs-interface-fee",
    sourceUrl: "https://uniswap.org/",
    sourceLabel: "Uniswap official site",
    imageUrl: "https://app.uniswap.org/images/1200x630_Rich_Link_Preview_Image.png",
    imageAlt: "Uniswap official brand artwork",
    logoUrl: "https://app.uniswap.org/favicon.png",
    imageSourceNote: "Official Uniswap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A wallet connection does not make a token safe. Check the contract, pool liquidity, price impact, approvals, and the network selected.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Wallet-first workflow", "Broad EVM ecosystem", "Permissionless pool design"],
    cons: ["Network gas can vary", "Pool liquidity and token risk differ", "Quotes are not guaranteed until settlement"],
  }),
  service({
    slug: "jupiter",
    name: "Jupiter",
    provider: "Jupiter",
    kind: "aggregator",
    categories: ["DEX aggregator", "Solana", "on-chain finance"],
    shortDescription: "A Solana-focused on-chain finance interface with swap routing, perps, lending, and portfolio tools.",
    editorialSummary: "Jupiter began as a Solana swap aggregator and now presents a broader collection of on-chain products. Its key comparison point is route selection across liquidity sources rather than a single pool model.",
    bestFor: "Solana users comparing routed spot swaps and additional on-chain finance tools in one interface.",
    chains: ["Solana"],
    assets: "Solana tokens available through the live route and liquidity sources",
    access: "Wallet-first",
    verification: "The reviewed interface presents wallet connection and on-chain signing rather than a standard exchange account; product and jurisdiction terms can differ by feature.",
    availability: "Feature, network, and location dependent; verify the live interface before use.",
    fees: "Route, priority, liquidity-source, and Solana network costs vary. Inspect the quote and transaction settings before signing.",
    feeSourceUrl: "https://station.jup.ag/docs/apis/fees",
    sourceUrl: "https://jup.ag/",
    sourceLabel: "Jupiter official interface",
    imageUrl: "https://jup.ag/meta-og/jupiter-meta-main.webp",
    imageAlt: "Jupiter official brand artwork",
    logoUrl: "https://jup.ag/favicon.svg",
    imageSourceNote: "Official Jupiter-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Jupiter exposes several products beyond spot swaps. Read the feature-specific terms and verify token addresses before signing.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Solana-native routing", "Multiple on-chain products", "Wallet-connected workflow"],
    cons: ["Primarily Solana-focused", "Feature risk varies by product", "Network congestion can affect execution"],
  }),
  service({
    slug: "pancakeswap",
    name: "PancakeSwap",
    provider: "PancakeSwap",
    kind: "dex",
    categories: ["AMM", "DEX", "multichain"],
    shortDescription: "A multichain DEX with swaps, liquidity, bridging, perpetuals, and other on-chain features.",
    editorialSummary: "PancakeSwap positions itself as a multichain trading and liquidity venue. Its official site advertises 11-chain coverage and swap fees as low as 0.01% in a product context; the actual route, pool, and network costs must be checked live.",
    bestFor: "Users comparing multichain AMM access and a broader DeFi feature set.",
    chains: ["BNB Chain", "Ethereum", "Base", "Arbitrum", "Polygon"],
    assets: "Assets available through the selected chain, pool, and feature",
    access: "Wallet-first",
    verification: "The reviewed DEX interface uses wallet connection; products such as bridging or fiat purchase can have separate provider requirements.",
    availability: "Chain, feature, and jurisdiction dependent.",
    fees: "The provider advertises swap fees as low as 0.01% on its reviewed homepage. Pool fees, routing, price impact, and network gas vary by trade.",
    feeSourceUrl: "https://docs.pancakeswap.finance/products/pancakeswap-exchange/trade",
    sourceUrl: "https://pancakeswap.finance/",
    sourceLabel: "PancakeSwap official site",
    imageUrl: "https://assets.pancakeswap.finance/web/og/v2/hero.jpg",
    imageAlt: "PancakeSwap official brand artwork",
    logoUrl: "https://pancakeswap.finance/favicon.ico",
    imageSourceNote: "Official PancakeSwap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "“As low as” fee language is not a quote for every pool or transaction. Check the selected route, token contract, price impact, and gas.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Multichain coverage", "Swap and liquidity tools", "Wallet-first access"],
    cons: ["Costs vary by pool and chain", "Many product surfaces add complexity", "Permissionless tokens can be risky"],
  }),
  service({
    slug: "curve",
    name: "Curve",
    provider: "Curve Finance",
    kind: "dex",
    categories: ["AMM", "stablecoin swaps", "DEX"],
    shortDescription: "A pool-based DEX interface built around Curve’s deployed smart contracts and liquidity markets.",
    editorialSummary: "Curve’s interface connects users to a set of deployed smart-contract pools. Pool design and asset correlation are central to the comparison: a stablecoin pool behaves differently from a volatile-asset pool.",
    bestFor: "Users assessing stable-asset and specialized liquidity pools rather than a general exchange order book.",
    chains: ["Ethereum and supported Curve deployments"],
    assets: "Pool-specific assets shown in the live Curve interface",
    access: "Wallet-first",
    verification: "The frontend connects to deployed smart contracts through a wallet; no conventional exchange profile is needed for the reviewed flow.",
    availability: "Pool, network, interface, and jurisdiction dependent.",
    fees: "Pool fees and network gas vary by deployment and selected market. Use the live pool interface and transaction preview.",
    sourceUrl: "https://curve.fi/",
    sourceLabel: "Curve official interface",
    imageUrl: "https://cdn.jsdelivr.net/gh/curvefi/curve-assets/branding/logo.png",
    imageAlt: "Curve Finance official logo",
    logoUrl: "https://curve.fi/favicon-32x32.png",
    imageSourceNote: "Official Curve-hosted or project-maintained asset",
    reviewedAt: "2026-08-27",
    caution: "Stable-value pools can still experience depegs, smart-contract failures, liquidity changes, and price impact.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Specialized pool designs", "Wallet-connected swaps", "Deep DeFi composability"],
    cons: ["Pool risk differs materially", "Gas and pool fees vary", "Interface can be harder for first-time users"],
  }),
  service({
    slug: "1inch",
    name: "1inch",
    provider: "1inch Network",
    kind: "aggregator",
    categories: ["DEX aggregator", "cross-chain", "MEV tools"],
    shortDescription: "A DEX aggregator that searches liquidity across networks and routes swaps through multiple venues.",
    editorialSummary: "1inch is best understood as a routing layer rather than one liquidity pool. Its comparison value comes from route selection, cross-chain functionality, wallet tools, and security features, while the quote remains the source of truth for a specific trade.",
    bestFor: "Traders comparing routes across multiple decentralized venues and supported networks.",
    chains: ["13+ networks advertised, including Ethereum, Base, Arbitrum, Polygon, Solana"],
    assets: "Assets supported by the selected route and network",
    access: "Wallet-first",
    verification: "The reviewed product uses wallet and network connections; 1inch products and integrations may have feature-specific requirements.",
    availability: "Route, network, asset, interface, and jurisdiction dependent.",
    fees: "The total depends on route, gas, liquidity-source costs, and any applicable network or product fee. Review the final quote before signing.",
    feeSourceUrl: "https://help.1inch.io/en/articles/4585109-what-are-1inch-network-fees",
    sourceUrl: "https://1inch.io/",
    sourceLabel: "1inch official site",
    imageUrl: "https://1inch.com/assets/1inch-com-cover.png",
    imageAlt: "1inch official brand artwork",
    logoUrl: "https://1inch.com/favicon/favicon.svg",
    imageSourceNote: "Official 1inch-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A routed quote can change with market conditions and gas. Verify the destination token, spender approval, slippage, and network.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Aggregates multiple DEXes", "Cross-chain tooling", "Route comparison"],
    cons: ["Quote complexity can confuse beginners", "Route and gas costs vary", "Token and smart-contract risk remains"],
  }),
  service({
    slug: "cow-swap",
    name: "CoW Swap",
    provider: "CoW Protocol / CoW DAO",
    kind: "aggregator",
    categories: ["intent-based", "DEX aggregator", "MEV protection"],
    shortDescription: "An Ethereum-focused DEX interface and protocol built around intent-based order settlement and routing.",
    editorialSummary: "CoW Swap describes itself as a user-protective product built on the CoW Protocol, an open-source, permissionless DEX aggregation protocol. The distinctive comparison point is its intent and solver model rather than a traditional single-pool interface.",
    bestFor: "Ethereum users who want to compare intent-based execution and MEV-aware routing.",
    chains: ["Ethereum and supported CoW deployments"],
    assets: "Assets available through the current CoW Swap market and route",
    access: "Wallet-first",
    verification: "The reviewed product uses wallet-based trading; no conventional exchange account is presented for the swap flow.",
    availability: "Network, market, solver, and jurisdiction dependent.",
    fees: "The effective price reflects the route, solver execution, and network conditions. Read the order preview rather than assuming a universal fee.",
    sourceUrl: "https://cow.fi/",
    sourceLabel: "CoW DAO official site",
    imageUrl: "https://cow.fi/images/og-meta-cowdao.png",
    imageAlt: "CoW DAO official brand artwork",
    logoUrl: "https://cow.fi/favicon-light-mode.png",
    imageSourceNote: "Official CoW-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "MEV-aware execution does not remove token, approval, smart-contract, network, or price risk.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Intent-based execution", "Open-source protocol", "MEV-aware product focus"],
    cons: ["Ethereum gas can be material", "Execution model differs from a simple AMM", "Market and solver conditions vary"],
  }),
  service({
    slug: "raydium",
    name: "Raydium",
    provider: "Raydium",
    kind: "dex",
    categories: ["AMM", "Solana", "DEX"],
    shortDescription: "A Solana-native DEX interface for token swaps and liquidity markets.",
    editorialSummary: "Raydium is a Solana-native liquidity venue. The most important comparison variables are the selected pool, token contract, pool depth, price impact, and Solana transaction conditions.",
    bestFor: "Solana users comparing token-pool liquidity and a native DEX interface.",
    chains: ["Solana"],
    assets: "Solana tokens available in the selected pool",
    access: "Wallet-first",
    verification: "The reviewed interface uses wallet connection and on-chain signing rather than a conventional exchange account.",
    availability: "Solana network, token, interface, and jurisdiction dependent.",
    fees: "Pool trading fees, routing, price impact, and Solana network costs vary by market. Inspect the live quote.",
    sourceUrl: "https://raydium.io/",
    sourceLabel: "Raydium official site",
    imageUrl: "https://img-v1.raydium.io/share/7be7ee6c-56b2-451e-a010-6c21e0db2ee5.png",
    imageAlt: "Raydium official brand artwork",
    logoUrl: "https://raydium.io/favicon.ico",
    imageSourceNote: "Official Raydium-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Solana meme-token markets can be thin or manipulated. Verify contracts and start with a small test transaction.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Solana-native experience", "Wallet-first trading", "Broad token-pool access"],
    cons: ["Token quality varies widely", "Pool depth can be thin", "Solana network conditions affect execution"],
  }),
  service({
    slug: "dydx",
    name: "dYdX",
    provider: "dYdX",
    kind: "dex",
    categories: ["perpetuals", "order book", "DEX"],
    shortDescription: "A decentralized trading platform focused on perpetual markets, order books, and margin mechanics.",
    editorialSummary: "dYdX is not a simple spot-swap directory entry: its official trading interface emphasizes perpetual markets, funding, leverage, open interest, and liquidation prices. It belongs in a DEX comparison, but users should understand the derivatives risk first.",
    bestFor: "Experienced users comparing decentralized perpetual trading rather than basic token swaps.",
    chains: ["dYdX Chain / supported dYdX markets"],
    assets: "Perpetual markets listed in the current dYdX interface",
    access: "Wallet-first",
    verification: "The trading interface uses wallet and account infrastructure specific to dYdX; product access and eligibility can vary by location and feature.",
    availability: "Market, jurisdiction, product, and account eligibility dependent.",
    fees: "Maker/taker fees, funding, spread, and liquidation conditions depend on the market, volume tier, and position. Use the live fee schedule.",
    feeSourceUrl: "https://docs.dydx.trade/fees",
    sourceUrl: "https://dydx.trade/",
    sourceLabel: "dYdX official trading interface",
    imageUrl: "https://dydx.trade//og-image.png",
    imageAlt: "dYdX official brand artwork",
    logoUrl: "https://dydx.trade/favicon.svg",
    imageSourceNote: "Official dYdX-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Leverage can magnify losses. Funding, margin, liquidation, oracle, and smart-contract risks are separate from spot-swap risk.",
    isDex: true,
    isNoKycCandidate: false,
    pros: ["Decentralized derivatives interface", "Order-book trading model", "Visible funding and margin fields"],
    cons: ["High derivatives complexity", "Liquidation risk", "Eligibility and market availability vary"],
  }),
  service({
    slug: "aerodrome",
    name: "Aerodrome",
    provider: "Aerodrome Finance",
    kind: "dex",
    categories: ["AMM", "Base", "DEX"],
    shortDescription: "A Base-focused liquidity hub for swaps, pools, and protocol-governed markets.",
    editorialSummary: "Aerodrome’s official description positions it as a central liquidity hub on Base. A useful comparison should focus on Base gas, pool selection, liquidity depth, and the difference between swapping and providing liquidity.",
    bestFor: "Base users comparing local liquidity pools and DeFi market incentives.",
    chains: ["Base"],
    assets: "Base assets and pools listed in the live Aerodrome interface",
    access: "Wallet-first",
    verification: "The reviewed interface uses wallet connection and on-chain signing; liquidity or governance features may have separate risks.",
    availability: "Base network, pool, interface, and jurisdiction dependent.",
    fees: "Pool, route, price-impact, and Base network costs vary. Check the live swap or liquidity transaction preview.",
    sourceUrl: "https://aerodrome.finance/",
    sourceLabel: "Aerodrome official site",
    imageUrl: "https://aerodrome.finance/images/aero-banner.png",
    imageAlt: "Aerodrome Finance official brand artwork",
    logoUrl: "https://aerodrome.finance/images/AERO/favicon.ico",
    imageSourceNote: "Official Aerodrome-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Liquidity incentives are not guaranteed returns. Assess pool composition, smart contracts, impermanent loss, and token risk separately.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Base-native liquidity focus", "Wallet-first access", "Swap and liquidity markets"],
    cons: ["Base-only scope", "Pool and token risk varies", "Liquidity incentives can change"],
  }),
  service({
    slug: "basicswap",
    name: "BasicSwap",
    provider: "BasicSwapDEX",
    kind: "p2p",
    categories: ["atomic swaps", "P2P", "DEX"],
    shortDescription: "An open protocol for peer-to-peer atomic swaps across Bitcoin, Monero, and other networks.",
    editorialSummary: "BasicSwap describes a distributed order book where traders meet directly and settle atomic swaps without a custodian or protocol fee. Its desktop/mobile installation model makes it different from a browser-only AMM.",
    bestFor: "Users who understand atomic swaps and want a non-custodial cross-chain P2P model.",
    chains: ["Bitcoin", "Monero", "Litecoin", "Firo", "Particl", "12+ networks advertised"],
    assets: "14 chains advertised on the reviewed official page; confirm the current live list",
    access: "No account flow",
    verification: "The provider states no signup or form is needed for the reviewed desktop/mobile flow; AML, legal, network, and counterparty considerations still apply.",
    availability: "Supported network, client, counterparty, and jurisdiction dependent.",
    fees: "BasicSwap states 0% protocol fee; users still pay underlying network costs and may face offer-spread or counterparty economics.",
    feeSourceUrl: "https://docs.basicswapdex.com/docs/intro",
    sourceUrl: "https://basicswapdex.com/",
    sourceLabel: "BasicSwap official site",
    imageUrl: "https://basicswapdex.com/images/og-home.png",
    imageAlt: "BasicSwap official brand artwork",
    logoUrl: "https://basicswapdex.com/images/favicon-32.png",
    imageSourceNote: "Official BasicSwap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Atomic swaps and P2P offers require technical and counterparty understanding. No protocol fee does not mean no transaction cost or risk.",
    isDex: true,
    isNoKycCandidate: true,
    pros: ["Atomic-swap model", "Non-custodial design", "Provider states 0% protocol fee"],
    cons: ["More technical setup", "Offer liquidity can vary", "Counterparty and network risk remain"],
  }),
  service({
    slug: "bisq",
    name: "Bisq",
    provider: "Bisq Network",
    kind: "p2p",
    categories: ["P2P", "Bitcoin", "open source"],
    shortDescription: "An open-source desktop P2P network for buying and selling Bitcoin without a central order-matching account.",
    editorialSummary: "Bisq describes a peer-to-peer network using open-source desktop software, local data, Tor, and 2-of-2 multisig deposits. It is a P2P Bitcoin market, not a conventional instant-swap or custodial exchange.",
    bestFor: "Bitcoin users who value open-source desktop software and P2P offers over convenience.",
    chains: ["Bitcoin"],
    assets: "Bitcoin against national currencies or supported alternative cryptocurrencies",
    access: "No account flow",
    verification: "Bisq states no registration is required in the reviewed product description and presents a no-identity-verification feature; payment method, legal, and counterparty conditions still apply.",
    availability: "Offer, payment method, software, and jurisdiction dependent.",
    fees: "Trading, mining, and payment-rail costs apply according to the live Bisq fee documentation and selected offer; there is no universal one-line fee for every trade.",
    feeSourceUrl: "https://bisq.wiki/Trading_fees",
    sourceUrl: "https://bisq.network/",
    sourceLabel: "Bisq official site",
    imageUrl: "https://bisq.network/images/bisq-og.jpg",
    imageAlt: "Bisq official brand artwork",
    logoUrl: "/images/dexes/bisq-logo.svg",
    imageSourceNote: "Official Bisq logo copied from bisq.network for reliable local rendering",
    reviewedAt: "2026-08-27",
    caution: "No registration is not the same as legal anonymity or zero risk. Read the offer, payment method, escrow, dispute, and fee documentation first.",
    isDex: false,
    isNoKycCandidate: true,
    pros: ["Open-source desktop software", "P2P and non-custodial design", "Tor and multisig features"],
    cons: ["Bitcoin-centric", "Offers and payment methods vary", "More setup than a web swap"],
  }),
  service({
    slug: "robosats",
    name: "RoboSats",
    provider: "RoboSats",
    kind: "p2p",
    categories: ["P2P", "Lightning", "Bitcoin"],
    shortDescription: "A Tor-oriented Lightning P2P market for exchanging Bitcoin with national currencies.",
    editorialSummary: "RoboSats presents a simple P2P workflow built around Lightning Hodl invoices, one-time robot identities, Tor access, and open-source code. The offer, payment method, and network conditions matter more than a single headline fee.",
    bestFor: "Bitcoin users who understand Lightning and want a P2P workflow with one-time identities.",
    chains: ["Bitcoin", "Lightning"],
    assets: "Bitcoin and national-currency payment methods listed in the live market",
    access: "No account flow",
    verification: "The provider describes the reviewed flow as simple and KYC-free with a random single-use Robot identity; laws, payment counterparties, and operational policies still apply.",
    availability: "Tor access, offer, payment method, and jurisdiction dependent.",
    fees: "Offer premiums, Lightning routing, bond/escrow mechanics, and payment-rail costs vary by trade; the provider does not present one universal transaction fee on the reviewed homepage.",
    sourceUrl: "https://learn.robosats.org/",
    sourceLabel: "RoboSats official learning site",
    imageUrl: "https://learn.robosats.org/assets/images/misc/feature-private.png",
    imageAlt: "RoboSats official privacy feature artwork",
    logoUrl: "https://learn.robosats.org/assets/images/misc/feature-private.png",
    imageSourceNote: "Official RoboSats-hosted product artwork",
    reviewedAt: "2026-08-27",
    caution: "Tor and a one-time identity do not remove payment, counterparty, Lightning, legal, or tax obligations.",
    isDex: false,
    isNoKycCandidate: true,
    pros: ["Lightning-focused P2P flow", "Open-source project", "One-time Robot identities"],
    cons: ["Bitcoin/Lightning scope", "Payment method risk varies", "Tor and Lightning add operational steps"],
  }),
  service({
    slug: "hodl-hodl",
    name: "Hodl Hodl",
    provider: "Hodlex Ltd",
    kind: "p2p",
    categories: ["P2P", "Bitcoin", "multisig escrow"],
    shortDescription: "A non-custodial Bitcoin P2P marketplace using multisig escrow and user-selected payment methods.",
    editorialSummary: "Hodl Hodl combines an account-based offer marketplace with multisig escrow. Its official site says no verification is required in the product section, while its FAQ says users sign up with email; that distinction matters when comparing privacy claims.",
    bestFor: "Bitcoin users comparing P2P offers, payment methods, and non-custodial escrow.",
    chains: ["Bitcoin", "Lightning / Arkade features where offered"],
    assets: "Bitcoin; payment methods and currencies vary by offer",
    access: "Email account",
    verification: "The provider says no verification is required in the reviewed product section, but the FAQ describes email sign-up. Individual offers, laws, and policy checks can differ.",
    availability: "Offer, payment method, account, and jurisdiction dependent.",
    fees: "The provider states that a trading fee is split between buyer and seller and deducted from the BTC amount; see the live fee FAQ for current details.",
    feeSourceUrl: "https://hodlhodl.com/faq#how_do_fees_work",
    sourceUrl: "https://hodlhodl.com/",
    sourceLabel: "Hodl Hodl official site",
    imageUrl: "https://hodlhodl.com/assets/link-preview-image.png",
    imageAlt: "Hodl Hodl official brand artwork",
    logoUrl: "https://hodlhodl.com/assets/favicon.ico",
    imageSourceNote: "Official Hodl Hodl-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "P2P payment methods can create fraud, chargeback, sanctions, and counterparty risks. Read the offer and escrow conditions carefully.",
    isDex: false,
    isNoKycCandidate: true,
    pros: ["Non-custodial multisig escrow", "Many payment methods", "Provider-published fee FAQ"],
    cons: ["Bitcoin-only core market", "Email account is still required", "Counterparty and payment risk vary"],
  }),
  service({
    slug: "sideshift",
    name: "SideShift.ai",
    provider: "SideShift.ai",
    kind: "instant-swap",
    categories: ["instant swap", "direct-to-wallet", "multichain"],
    shortDescription: "A direct-to-wallet crypto swap service covering BTC, ETH, SOL, and other assets across multiple networks.",
    editorialSummary: "SideShift’s reviewed interface is organized around choosing a pair, sending a deposit, and receiving the swapped asset directly in a wallet. It is closer to an instant swap service than a liquidity-pool DEX.",
    bestFor: "Users comparing direct-to-wallet swap workflows without a conventional trading screen.",
    chains: ["45+ networks advertised"],
    assets: "300+ coins advertised; route and network support vary",
    access: "No account flow",
    verification: "The reviewed page shows a direct-to-wallet flow without a visible standard account step; provider compliance checks or transaction reviews may still apply.",
    availability: "Asset, route, network, jurisdiction, and compliance-review dependent.",
    fees: "The exchange quote and selected rate mode determine the effective rate; network and service costs vary by route. Use the live quote as the source of truth.",
    sourceUrl: "https://sideshift.ai/",
    sourceLabel: "SideShift.ai official site",
    imageUrl: "https://sideshift.ai/meta/ogimage.jpg",
    imageAlt: "SideShift.ai official brand artwork",
    logoUrl: "https://sideshift.ai/favicon.svg",
    imageSourceNote: "Official SideShift-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A direct-to-wallet flow does not guarantee a fixed rate, settlement time, or absence of compliance review. Verify the deposit address and network.",
    isDex: false,
    isNoKycCandidate: true,
    isKycConditional: true,
    pros: ["Direct-to-wallet flow", "Broad advertised asset coverage", "Fixed and variable rate modes"],
    cons: ["Quote and route costs vary", "Compliance reviews may occur", "Not a self-custody protocol"],
  }),
  service({
    slug: "changenow",
    name: "ChangeNOW",
    provider: "ChangeNOW",
    kind: "instant-swap",
    categories: ["instant swap", "multichain", "KYC-conditional"],
    shortDescription: "An instant crypto exchange service with a broad asset list and variable route pricing.",
    editorialSummary: "ChangeNOW is included as a KYC-conditional instant-swap comparison rather than a guaranteed no-KYC provider. The official site emphasizes fast exchange and a broad asset range, while compliance checks can depend on transaction conditions.",
    bestFor: "Users comparing a simple instant-swap interface and willing to review compliance and rate conditions.",
    chains: ["Multiple networks; live asset list varies"],
    assets: "Broad cryptocurrency selection advertised by the provider",
    access: "KYC may apply",
    verification: "No account may be available for some flows, but the provider can request verification or additional information under its policies, limits, or compliance controls.",
    availability: "Asset, route, transaction, jurisdiction, and compliance dependent.",
    fees: "The effective service fee is reflected in the selected fixed or floating exchange quote, alongside network costs. Compare the final receive amount before sending.",
    sourceUrl: "https://changenow.io/",
    sourceLabel: "ChangeNOW official site",
    imageUrl: "https://changenow.io/images/site-image.png",
    imageAlt: "ChangeNOW official brand artwork",
    logoUrl: "https://changenow.io/images/icons/favicon-32x32.png",
    imageSourceNote: "Official ChangeNOW-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "Do not treat an instant-swap flow as a promise of no KYC. Read the provider’s terms and compliance policy before sending funds.",
    isDex: false,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["Simple swap workflow", "Broad advertised asset coverage", "Fixed/floating quote options"],
    cons: ["KYC may be triggered", "Rate includes route economics", "Settlement and support conditions vary"],
  }),
  service({
    slug: "simpleswap",
    name: "SimpleSwap",
    provider: "SimpleSwap",
    kind: "instant-swap",
    categories: ["instant swap", "multichain", "KYC-conditional"],
    shortDescription: "An instant crypto swap service with fixed and floating rate paths across a large asset list.",
    editorialSummary: "SimpleSwap is useful as a comparison point for instant swaps rather than a permissionless DEX. Its official page advertises a large cryptocurrency selection; route availability, pricing, and verification can depend on the transaction.",
    bestFor: "Users who want a straightforward swap interface and will check the final route and compliance terms.",
    chains: ["Multiple networks; live support varies"],
    assets: "2,800+ cryptocurrencies advertised; confirm the current pair list",
    access: "KYC may apply",
    verification: "The provider offers swap flows that may not require an account, but KYC or transaction review can still apply under policy or risk controls.",
    availability: "Pair, network, transaction, jurisdiction, and compliance dependent.",
    fees: "Fixed or floating quotes include the route’s service economics and network costs. Compare the receive amount and review the transaction screen before sending.",
    sourceUrl: "https://simpleswap.io/",
    sourceLabel: "SimpleSwap official site",
    imageUrl: "https://edge.simpleswap.io/images/meta/V1.png",
    imageAlt: "SimpleSwap official brand artwork",
    logoUrl: "https://simpleswap.io/favicon-32x32.png",
    imageSourceNote: "Official SimpleSwap-hosted brand asset",
    reviewedAt: "2026-08-27",
    caution: "A no-account path is not a permanent no-KYC guarantee. Keep transaction records and read the provider’s current terms.",
    isDex: false,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["Simple fixed/floating swap flow", "Large advertised asset list", "No conventional order book"],
    cons: ["KYC may be triggered", "Quote economics vary", "Not a self-custody protocol"],
  }),
  service({
    slug: "orangefren",
    name: "OrangeFren",
    provider: "OrangeFren",
    kind: "aggregator",
    categories: ["exchange aggregator", "prepaid cards", "privacy-focused"],
    shortDescription: "A transaction-first comparison service for instant exchanges and prepaid cards, with privacy-oriented filters.",
    editorialSummary: "OrangeFren’s public interface organizes exchange comparisons around a transaction pair and presents prepaid cards as a separate category. It is included here as an aggregator and research reference, not as a promise that every listed route is available without checks.",
    bestFor: "Users comparing multiple instant-swap offers or privacy-oriented prepaid-card options in one interface.",
    chains: ["Varies by listed service and transaction pair"],
    assets: "Varies by provider and selected transaction",
    access: "No account flow",
    verification: "The reviewed public flow presents transaction search without a visible account requirement; individual providers and transactions can impose their own checks.",
    availability: "Offer, provider, asset pair, jurisdiction, and compliance dependent.",
    fees: "Displayed rates and transaction fees depend on the selected provider and pair. Compare the final receive amount, not only the headline rate.",
    sourceUrl: "https://orangefren.com/",
    sourceLabel: "OrangeFren official site",
    imageUrl: "https://orangefren.com/static/logos/OrangeFren%20Logo-11.webp",
    imageAlt: "OrangeFren official logo",
    logoUrl: "https://orangefren.com/static/logos/OrangeFren%20Logo-13.webp",
    imageSourceNote: "Official OrangeFren-hosted logo asset",
    reviewedAt: "2026-08-27",
    caution: "An aggregator is not the counterparty for every listed trade. Check the selected provider’s terms, KYC policy, refund policy, and regional availability.",
    isDex: false,
    isNoKycCandidate: true,
    isKycConditional: true,
    pros: ["Transaction-first comparison", "Separate prepaid-card category", "Rate and policy filters"],
    cons: ["Listed-provider quality varies", "Rates can include hidden route economics", "Individual providers may request checks"],
  }),
  service({
    slug: "hyperliquid",
    name: "Hyperliquid",
    provider: "Hyperliquid protocol / app",
    kind: "dex",
    categories: ["perpetuals", "spot", "on-chain order book", "derivatives"],
    shortDescription: "A fully on-chain trading venue for crypto spot markets and perpetual contracts, with additional outcome-style products visible in the app.",
    editorialSummary: "Hyperliquid puts an order-book trading experience on its own high-throughput chain rather than presenting a simple AMM swap screen. The reviewed app describes spot and perpetual markets and also exposes other outcome-oriented products, so readers should identify the exact instrument before trading. Its public interface can show jurisdictional restrictions and product-specific eligibility.",
    bestFor: "Experienced users comparing an on-chain order book for spot or perpetual markets who understand margin, funding, liquidation, and chain-specific settlement.",
    chains: ["Hyperliquid L1", "HyperEVM where supported"],
    assets: "Crypto spot assets and perpetual contracts listed in the selected market; the app also displays additional market types.",
    access: "Wallet-first",
    verification: "The reviewed app uses wallet connection and showed a restricted-jurisdiction warning; no conventional custodial account flow was relied on for this profile. Eligibility, region, product, and legal checks can still apply.",
    availability: "Market, jurisdiction, wallet, and product eligibility dependent.",
    fees: "Hyperliquid's official schedule separates spot and perpetual fees into 14-day volume tiers. The reviewed perpetual base tier is listed at 0.045% taker and 0.015% maker; funding, spread, liquidation, and any applicable product costs are separate.",
    feeSourceUrl: "https://hyperliquid.gitbook.io/hyperliquid-docs/trading/fees",
    sourceUrl: "https://hyperliquid.xyz/",
    sourceLabel: "Hyperliquid official site",
    imageUrl: "https://app.hyperliquid.xyz/apple-touch-icon.png",
    imageAlt: "Hyperliquid official app icon used as the provider visual",
    logoUrl: "https://app.hyperliquid.xyz/favicon-32x32.png",
    imageSourceNote: "Official Hyperliquid app-hosted icon; the reviewed app did not expose a separate public hero image.",
    galleryImages: [{ url: "/images/dexes/hyperliquid-homepage.webp", alt: "Hyperliquid homepage showing the public spot and perpetuals trading interface with market navigation and wallet controls", source: "Official Hyperliquid homepage capture reviewed 27 August 2026; shown to identify the public product interface, not to represent current execution or liquidity." }],
    stats: { coinGeckoExchangeId: "hyperliquid", geckoTerminal: { network: "hyperliquid", dexId: "hyperliquid" } },
    reviewedAt: "2026-08-27",
    caution: "Perpetuals and other leveraged or outcome-based products can lose collateral quickly. Check the instrument, margin rules, funding, liquidation price, oracle/index mechanics, jurisdiction notice, and signing domain before proceeding.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["On-chain order-book design", "Spot and perpetual market coverage", "Clear separation of fee schedules in official docs"],
    cons: ["Leverage and liquidation risk", "Restricted jurisdictions and product eligibility", "The app includes more than simple spot swaps"],
  }),
  service({
    slug: "orca",
    name: "Orca",
    provider: "Orca Protocol",
    kind: "dex",
    categories: ["AMM", "Solana", "concentrated liquidity", "LP pools"],
    shortDescription: "A Solana-native AMM and liquidity protocol built around Whirlpools with concentrated and full-range liquidity positions.",
    editorialSummary: "Orca is best understood as a Solana liquidity protocol rather than a single universal-price exchange. Its Whirlpools can use different configurations, and liquidity providers earn trading fees according to the selected pool. A swap comparison therefore needs the live quote, pool setting, price impact, and Solana transaction cost—not a single directory-wide fee number.",
    bestFor: "Solana users comparing pool-based swaps or researching concentrated-liquidity positions and their associated management risks.",
    chains: ["Solana"],
    assets: "SPL tokens available in the selected Whirlpool or route.",
    access: "Wallet-first",
    verification: "The reviewed public product is a wallet-connected protocol interface with no conventional account requirement observed. That does not establish anonymity or remove wallet, provider, jurisdiction, or legal obligations.",
    availability: "Pool, token, wallet, route, and network dependent.",
    fees: "Orca does not have one universal swap fee for every pool. Trading fees are configured at the pool level and distributed to liquidity providers under the protocol design; network fees, price impact, and any route economics are additional.",
    feeSourceUrl: "https://docs.orca.so/reference/fees",
    sourceUrl: "https://www.orca.so/",
    sourceLabel: "Orca official site",
    imageUrl: "https://orca.so/og.png",
    imageAlt: "Orca official brand artwork",
    logoUrl: "https://www.orca.so/images/favicon.png",
    imageSourceNote: "Official Orca-hosted OG image and favicon",
    galleryImages: [{ url: "/images/dexes/orca-interface.webp", alt: "Orca website visual showing Solana token-swap and liquidity-pool products in a desktop-and-mobile layout", source: "Official Orca homepage visual reviewed 27 August 2026; it illustrates the provider’s product interface and is not a live performance measure." }],
    stats: { coinGeckoExchangeId: "orca", geckoTerminal: { network: "solana", dexId: "orca" } },
    reviewedAt: "2026-08-27",
    caution: "AMM users face smart-contract, token, pool, impermanent-loss, price-impact, slippage, and Solana transaction risks. Concentrated liquidity can require active range management and is not a passive-return guarantee.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: false,
    pros: ["Solana-native liquidity infrastructure", "Concentrated and full-range pool designs", "Wallet-first swap flow"],
    cons: ["Pool-specific fees and liquidity", "LP range and impermanent-loss exposure", "SPL token and smart-contract risk"],
  }),
  service({
    slug: "apex",
    name: "ApeX Omni",
    provider: "ApeX Protocol",
    kind: "dex",
    categories: ["perpetuals", "multichain", "order book", "derivatives"],
    shortDescription: "A decentralized perpetuals platform with cross-chain deposits, an order-book trading model, and additional product modules.",
    editorialSummary: "ApeX Omni is a derivatives-focused venue rather than a general-purpose token-swap AMM. Official materials describe more than 100 perpetual contracts, cross-chain deposit support, and leverage marketing up to 100x. Its current product and API documentation also describe margin, funding, liquidation, and wallet-signature flows, so the useful comparison is about instrument design and risk controls as much as headline access.",
    bestFor: "Experienced derivatives users who want to compare an on-chain perpetuals venue and are prepared to evaluate margin, funding, liquidation, and cross-chain transfer details.",
    chains: ["Ethereum", "BNB Chain", "Base", "Mantle", "Arbitrum"],
    assets: "USDT-settled perpetual contracts plus supported collateral and product-specific markets.",
    access: "Wallet-first",
    verification: "The public product is built around wallet-based onboarding and account signatures, but eligibility and product-specific checks can change. A wallet-first flow is not a promise of no KYC, unrestricted access, or legal anonymity.",
    availability: "Jurisdiction, wallet onboarding, market, collateral, and product dependent.",
    fees: "ApeX's official Omni materials use 0.02% maker and 0.05% taker as a standard perpetuals reference, while VIP, volume, campaign, and product terms can change the rate. Funding, liquidation, withdrawal, and cross-chain costs are separate.",
    feeSourceUrl: "https://apex-pro.gitbook.io/apex-pro/apex-omni-live-now/trading-perpetual-contracts/trading-fees",
    partnerUrl: "https://join.omni.apex.exchange/AFF-741",
    partnerLabel: "ApeX referral link",
    sourceUrl: "https://www.apex.exchange/",
    sourceLabel: "ApeX official site",
    imageUrl: "https://static-pro.apex.exchange/icon/apex-exchange.jpeg",
    imageAlt: "ApeX Omni official brand artwork",
    logoUrl: "https://www.apex.exchange/_next/static/media/logo_header.0n90rs_w_ixm7.svg",
    imageSourceNote: "Official ApeX-hosted brand asset",
    galleryImages: [{ url: "/images/dexes/apex-interface.png", alt: "ApeX Omni interface artwork showing perpetual-market charts, order panels, and mobile trading screens", source: "Official ApeX homepage interface artwork reviewed 27 August 2026; it illustrates the product layout, not current execution, liquidity, or returns." }],
    stats: { coinGeckoExchangeId: "apex-omni" },
    reviewedAt: "2026-08-27",
    caution: "Perpetual contracts and leverage can amplify losses and trigger liquidation. Verify the market, oracle/index price, margin mode, funding interval, collateral, cross-chain route, and exact order details before signing.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["Derivatives-first product focus", "Cross-chain deposit documentation", "Official API and market-data documentation"],
    cons: ["Leverage, funding, and liquidation exposure", "Product and fee programs can change", "Cross-chain transfer and collateral complexity"],
  }),
  service({
    slug: "aster",
    name: "Aster",
    provider: "Aster DEX",
    kind: "dex",
    categories: ["perpetuals", "multichain", "derivatives", "yield features"],
    shortDescription: "A multichain perpetuals venue with Simple and Pro interfaces, multiple contract fee schedules, and wallet-based access.",
    editorialSummary: "Aster presents a derivatives interface with separate Simple and Pro modes and more than one contract family. Its official fee documentation distinguishes USDT perpetuals, USD1 perpetuals, and stock perpetuals rather than offering one blended rate. That separation matters: contract type, funding, margin, liquidation, and any token-based discount can change the actual cost and risk profile.",
    bestFor: "Experienced users comparing perpetual-contract interfaces and reading the contract-specific fee and risk terms before using leverage.",
    chains: ["Multiple supported networks; confirm the live network selector"],
    assets: "USDT, USD1, and stock-perpetual markets listed in the selected product mode.",
    access: "Wallet-first",
    verification: "The public interface is wallet-oriented, but the reviewed product is a derivatives venue where market, regional, account, and compliance policies may apply. This profile does not make a no-KYC or unrestricted-access claim.",
    availability: "Market, chain, jurisdiction, account, and product mode dependent.",
    fees: "Aster's official schedule lists USDT perps at 0% maker / 0.04% taker, USD1 perps at 0% maker / 0.005% taker, and stock perps at 0% maker / 0.009% taker. Paying fees in $ASTER is documented with a 5% discount; funding and other costs remain separate.",
    feeSourceUrl: "https://docs.asterdex.com/trading/perpetuals/fees-and-specs/fees",
    partnerUrl: "https://www.asterdex.com/en/referral/A022fd",
    partnerLabel: "Aster referral link",
    sourceUrl: "https://www.asterdex.com/en",
    sourceLabel: "Aster official site",
    imageUrl: "https://static.asterdexfx.com/cloud-futures/static/images/dex/aster/og_image.png",
    imageAlt: "Aster official brand artwork",
    logoUrl: "https://static.asterdexfx.com/cloud-futures/static/images/aster/logo.svg",
    imageSourceNote: "Official Aster-hosted brand asset",
    galleryImages: [
      { url: "/images/dexes/aster-mobile.png", alt: "Aster mobile trading screen showing perpetual-market charts, order controls, and account navigation", source: "Official Aster homepage mobile-app visual reviewed 27 August 2026; it illustrates the interface, not a fee or performance quote." },
      { url: "/images/dexes/aster-frame.jpg", alt: "Aster dark-mode derivatives dashboard with a market chart, order controls, and position panels", source: "Official Aster homepage interface frame reviewed 27 August 2026; provider visual, not independent evidence of execution or liquidity." },
    ],
    stats: { coinGeckoExchangeId: "aster" },
    reviewedAt: "2026-08-27",
    caution: "Perpetuals and stock-perpetual products carry leverage, liquidation, funding, oracle, counterparty, and market-structure risks. Read the exact contract specification and regional eligibility notice before connecting a wallet.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: true,
    pros: ["Contract-specific published fee schedule", "Simple and Pro interface modes", "Multichain product positioning"],
    cons: ["Leveraged derivatives risk", "Different products have different fees", "Token discounts and live terms require verification"],
  }),
  service({
    slug: "kuru",
    name: "Kuru",
    provider: "Kuru Exchange",
    kind: "dex",
    categories: ["on-chain order book", "smart aggregator", "Monad", "spot trading"],
    shortDescription: "A fully on-chain order-book DEX and smart aggregator on Monad with trade, swap, discovery, liquidity, and vault features.",
    editorialSummary: "Kuru combines an on-chain order book with aggregation and a broader set of portfolio, liquidity, and vault surfaces. That makes it different from a single-pool AMM: the quote can reflect order-book depth, route selection, market liquidity, and Monad transaction costs. Readers should distinguish a spot order from a vault or liquidity action because each has a different risk and fee lens.",
    bestFor: "Monad users comparing an on-chain order-book experience with smart-aggregation and liquidity tools.",
    chains: ["Monad"],
    assets: "Assets and markets listed by Kuru on Monad; confirm the live market and token contracts.",
    access: "Wallet-first",
    verification: "Kuru's public documentation describes a wallet-connected, fully on-chain product. No conventional account flow was relied on for this profile, but that is not a statement about legal identity requirements, eligibility, or anonymity.",
    availability: "Monad network, market, wallet, and product surface dependent.",
    fees: "Kuru's official fee documentation is the source of truth for its current order-book, swap, aggregation, and related product charges. The fee can depend on the product and route; Monad gas, spread, slippage, and liquidity costs are separate.",
    feeSourceUrl: "https://docs.kuru.io/liquidity/how-fees-work",
    stats: { coinGeckoExchangeId: "kuru" },
    sourceUrl: "https://www.kuru.io/",
    sourceLabel: "Kuru official site",
    imageUrl: "https://www.kuru.io/img/og.png",
    imageAlt: "Kuru official brand artwork",
    logoUrl: "https://www.kuru.io/favicon-96x96.png",
    imageSourceNote: "Official Kuru-hosted OG image and favicon",
    reviewedAt: "2026-08-27",
    caution: "On-chain order books and vault features carry smart-contract, liquidity, token, signing, and market-depth risks. Confirm the Monad network, contract addresses, order type, spread, gas, and any vault terms before proceeding.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: false,
    pros: ["Fully on-chain order-book model", "Monad-native product scope", "Aggregation and liquidity surfaces"],
    cons: ["Newer network and market-liquidity considerations", "Fee details vary by product and route", "Vault and liquidity features add separate risks"],
  }),
  service({
    slug: "pump-fun-pumpswap",
    name: "PumpSwap",
    provider: "Pump.fun ecosystem",
    kind: "dex",
    categories: ["AMM", "Solana", "meme-coin markets", "launch ecosystem"],
    shortDescription: "A Solana decentralized exchange for Pump.fun tokens, designed around fast-moving meme-coin markets and token-launch activity.",
    editorialSummary: "PumpSwap is the swap venue linked from the Pump.fun ecosystem, not a general-purpose exchange with a curated asset list. The official description emphasizes Pump.fun tokens and instant meme-coin swaps. That focus can mean rapidly changing pools, thin or uneven liquidity, volatile pricing, and heightened token-contract risk; the live pool and quote matter more than a static directory label.",
    bestFor: "Users researching the Pump.fun token ecosystem who understand Solana swaps, meme-coin volatility, pool mechanics, and contract risk.",
    chains: ["Solana"],
    assets: "Pump.fun ecosystem tokens and other assets available through the selected PumpSwap pool or route.",
    access: "Wallet-first",
    verification: "The reviewed PumpSwap interface is wallet-oriented and does not rely on a conventional exchange account for the swap screen. That does not establish no-KYC status, token legitimacy, unrestricted access, or legal anonymity.",
    availability: "Pool, token, wallet, network, and jurisdiction dependent.",
    fees: "Pump.fun's fee page (last updated 20 May 2026) lists PumpSwap canonical-pool total fees that vary by market-cap band from 1.25% down to 0.30%; other PumpSwap pools are listed at 0.30%. Creator, protocol, LP, wallet, and Solana network charges can be separate or change.",
    feeSourceUrl: "https://pump.fun/docs/fees",
    stats: { coinGeckoExchangeId: "pumpswap", geckoTerminal: { network: "solana", dexId: "pumpswap" } },
    partnerUrl: "https://join.pump.fun/HSag/kjs0qp0n",
    partnerLabel: "Pump.fun referral link",
    sourceUrl: "https://swap.pump.fun/",
    sourceLabel: "PumpSwap official app",
    imageUrl: "https://pump.fun/OpenGraphRetail_v4.png",
    imageAlt: "Pump.fun official brand artwork for the PumpSwap ecosystem",
    logoUrl: "https://pump.fun/logo.png",
    imageSourceNote: "Official Pump.fun-hosted brand assets",
    reviewedAt: "2026-08-27",
    caution: "Meme-coin markets can move sharply and may include malicious, illiquid, or highly concentrated tokens. Verify the token mint, pool, slippage, holder distribution, signing prompt, and final receive amount; a swap interface is not a token-quality endorsement.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: false,
    pros: ["Direct Solana ecosystem access", "Purpose-built Pump.fun token venue", "Wallet-first swap flow"],
    cons: ["Extreme meme-coin and token risk", "Pool liquidity and fees vary", "A live token listing is not due diligence"],
  }),
  service({
    slug: "meteora",
    name: "Meteora",
    provider: "Meteora Protocol",
    kind: "dex",
    categories: ["liquidity pools", "Solana", "DLMM", "DAMM"],
    shortDescription: "A Solana liquidity protocol offering dynamic and concentrated pool designs, including DLMM and DAMM products.",
    editorialSummary: "Meteora is a liquidity-pool protocol with multiple pool designs rather than one flat exchange fee. Its DLMM and DAMM products expose different liquidity and position mechanics, while the live app surfaces pool-specific rates and statistics. We use generalized fee language here so a changing pool quote is not mistaken for an evergreen protocol-wide rate.",
    bestFor: "Solana users comparing pool-based swaps or studying liquidity-position mechanics across Meteora products.",
    chains: ["Solana"],
    assets: "SPL tokens available in the selected Meteora pool, vault, or route.",
    access: "Wallet-first",
    verification: "The public app is wallet-oriented and no conventional account flow was relied on for this profile. That is not a claim of no KYC, anonymity, safety, or universal access.",
    availability: "Pool, token, wallet, network, and product dependent.",
    fees: "Meteora fees are pool- and product-specific. The live quote can include swap or dynamic-pool fees, Solana network cost, price impact, and route economics; protocol-revenue documentation should be checked alongside the selected pool.",
    feeSourceUrl: "https://docs.meteora.ag/protocol/protocol-revenues",
    stats: { coinGeckoExchangeId: "meteora", geckoTerminal: { network: "solana", dexId: "meteora" } },
    sourceUrl: "https://app.meteora.ag/",
    sourceLabel: "Meteora official app",
    imageUrl: "https://app.meteora.ag/seo/og_image.png",
    imageAlt: "Meteora official brand artwork",
    logoUrl: "https://app.meteora.ag/apple/apple-icon-57x57.png",
    imageSourceNote: "Official Meteora-hosted OG image and app icon",
    reviewedAt: "2026-08-27",
    caution: "Liquidity providers and traders face smart-contract, token, pool, impermanent-loss, price-impact, slippage, and Solana transaction risks. Do not infer future yield from a live APY, volume, or pool statistic.",
    isDex: true,
    isNoKycCandidate: false,
    isKycConditional: false,
    pros: ["Multiple Solana pool designs", "DLMM and DAMM liquidity tooling", "Wallet-first app experience"],
    cons: ["Pool-specific mechanics and fees", "LP and impermanent-loss exposure", "Live statistics are not durable forecasts"],
  }),
  service({
    slug: "limitless",
    name: "Limitless",
    provider: "Limitless Exchange",
    kind: "prediction-market",
    categories: ["prediction market", "Base", "CLOB", "outcome shares"],
    shortDescription: "A decentralized prediction market on Base where users trade outcome shares on crypto, sports, politics, and other events—not a conventional token-swap DEX.",
    editorialSummary: "Limitless should be read as a prediction-market profile, not as a token-exchange recommendation. Its official documentation describes YES/NO outcome shares, USDC collateral, market resolution, and a central-limit-order-book model. The key research questions are the market wording, close time, resolution source, settlement rules, spread, collateral, and fee—not only whether a wallet can connect.",
    bestFor: "Readers researching decentralized event markets who are prepared to understand outcome pricing, resolution rules, collateral loss, and Base transactions.",
    chains: ["Base"],
    assets: "USDC collateral and market-specific YES/NO outcome shares described in the selected market.",
    access: "Wallet-first",
    verification: "Markets resolve under the provider's published market rules and designated resolution sources. Official documentation describes automatic resolution for many markets and different oracle or manual paths by market type; read the specific market page before taking a position.",
    verificationLabel: "Resolution rules",
    availability: "Market, collateral, wallet, jurisdiction, resolution, and event timing dependent.",
    fees: "Limitless' official documentation describes dynamic taker fees for CLOB markets: buy fees of 0.40%–3.00% and sell fees of 0.42%–1.50%, while resting maker limit orders are fee-free. AMM markets use a 0.40% flat fee, with possible market-specific or promotional changes; Base gas and collateral still matter.",
    feeSourceUrl: "https://docs.limitless.exchange/user-guide/fees",
    partnerUrl: "https://limitless.exchange?r=JDDJ4LOQ9T",
    partnerLabel: "Limitless referral link",
    sourceUrl: "https://limitless.exchange/",
    sourceLabel: "Limitless official site",
    imageUrl: "https://limitless.exchange/api/og",
    imageAlt: "Limitless official prediction-market artwork",
    logoUrl: "https://limitless.exchange/favicon.svg",
    imageSourceNote: "Official Limitless-hosted OG endpoint and favicon",
    reviewedAt: "2026-08-27",
    caution: "This is a prediction market, not a token-swap DEX. A position can lose collateral if the outcome is wrong or a resolution rule is misunderstood; review the market definition, oracle or resolution source, close time, liquidity, smart-contract terms, and local obligations.",
    isDex: false,
    isNoKycCandidate: false,
    isKycConditional: false,
    pros: ["Explicit outcome-market product", "Published resolution and security documentation", "Base-native USDC market design"],
    cons: ["Not a conventional token-swap DEX", "Resolution and event-definition risk", "Outcome pricing, liquidity, and collateral can change"],
  }),
];

for (const item of dexServices) item.faqs = faq(item);

export const dexServicesBySlug = new Map(dexServices.map((item) => [item.slug, item]));
export const dexDirectoryServices = dexServices.filter((item) => item.isDex || item.kind === "aggregator");
export const noKycDirectoryServices = dexServices.filter((item) => item.isNoKycCandidate || (item.isKycConditional && !item.isDex));
export const dexDetailSlugs = dexServices.filter((item) => item.isDex).map((item) => item.slug);
export const noKycDetailSlugs = noKycDirectoryServices.map((item) => item.slug);

export function getDexService(slug: string) {
  return dexServicesBySlug.get(slug);
}
