export type Lifecycle = "enforcement" | "insolvency" | "protocol-failure" | "abandoned" | "obsolete";
export type Confidence = "low" | "medium" | "high";
export type ProjectStatus =
  | "Abandoned development"
  | "Website offline"
  | "Chain halted"
  | "Liquidity disappeared"
  | "Protocol failure"
  | "Exploit"
  | "Insolvency"
  | "Delisted"
  | "Migrated"
  | "Official sunset"
  | "Never launched"
  | "Confirmed enforcement action";

export type EvidenceLink = { label: string; href: string };

export type DeadProject = {
  slug: string;
  name: string;
  ticker?: string;
  type: "Token" | "Protocol" | "Exchange" | "Investment scheme" | "Fund" | "Corporate project";
  lifecycle: Lifecycle;
  status: ProjectStatus;
  secondaryStatus?: ProjectStatus;
  era: string;
  launched: string;
  lastKnownActivity: string;
  summary: string;
  whatHappened: string;
  whatFailed: string;
  currentStatus: string;
  userGuidance: string[];
  lessons: string[];
  evidence: EvidenceLink[];
  confidence: Confidence;
  stillTrades?: boolean;
  image: { src: string; alt: string };
  reviewedAt: string;
};

export const lifecycleLabels: Record<Lifecycle, string> = {
  enforcement: "Enforcement",
  insolvency: "Insolvency",
  "protocol-failure": "Protocol failure",
  abandoned: "Abandoned",
  obsolete: "Obsolete / sunset",
};

export const deadProjects: DeadProject[] = [
  {
    slug: "onecoin",
    name: "OneCoin",
    ticker: "OneCoin",
    type: "Investment scheme",
    lifecycle: "enforcement",
    status: "Confirmed enforcement action",
    secondaryStatus: "Abandoned development",
    era: "2014–2019",
    launched: "2014",
    lastKnownActivity: "2019",
    summary: "US authorities describe OneCoin as a global investment scheme that marketed a purported cryptocurrency and defrauded investors of more than $4 billion.",
    whatHappened: "According to the US Department of Justice, OneCoin operated between 2014 and 2019 and sold a purported cryptocurrency through a global marketing network. Several associates have been convicted. In April 2026 the Justice Department opened a remission process for eligible purchasers.",
    whatFailed: "US authorities say OneCoin was marketed as a cryptocurrency while functioning as a fraudulent investment scheme.",
    currentStatus: "The original scheme is defunct. Recovery, if any, is through official legal processes such as onecoinremission.com.",
    userGuidance: ["Use only official government portals for claims.", "Do not send a seed phrase to anyone promising a refund."],
    lessons: ["A professional website does not make a token real."],
    evidence: [{ label: "US Department of Justice remission announcement", href: "https://www.justice.gov/opa/pr/justice-department-announces-compensation-process-onecoin-fraud-victims-funds-recovered" }],
    confidence: "high",
    stillTrades: false,
    image: { src: "/images/projects/failure-directory-hero.svg", alt: "Research graphic for enforcement-linked crypto cases" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "bitconnect",
    name: "BitConnect",
    ticker: "BCC",
    type: "Investment scheme",
    lifecycle: "enforcement",
    status: "Confirmed enforcement action",
    secondaryStatus: "Liquidity disappeared",
    era: "2016–2018",
    launched: "2016",
    lastKnownActivity: "2018",
    summary: "BitConnect promoted a high-yield lending programme around BCC. The SEC later charged that it operated a multi-billion-dollar unregistered securities offering that collapsed in early 2018.",
    whatHappened: "In January 2018 BitConnect shut its lending operation and the token price collapsed. In 2021 the SEC charged BitConnect and associated actors.",
    whatFailed: "The advertised returns depended on new inflows and a rising token price.",
    currentStatus: "The original lending platform is gone. BCC or copycat tickers may still appear on obscure markets.",
    userGuidance: ["Treat new BitConnect-named sites as unrelated unless you can prove legal continuity."],
    lessons: ["Guaranteed daily returns in crypto are a major warning sign."],
    evidence: [{ label: "SEC press release on BitConnect charges", href: "https://www.sec.gov/news/press-release/2021-90" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/failure-directory-hero.svg", alt: "Research graphic for enforcement-linked crypto cases" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "terra-luna-ust",
    name: "TerraUSD and original LUNA",
    ticker: "UST / LUNA",
    type: "Protocol",
    lifecycle: "protocol-failure",
    status: "Protocol failure",
    secondaryStatus: "Confirmed enforcement action",
    era: "2022 contagion",
    launched: "2018",
    lastKnownActivity: "2022 collapse; later court and bankruptcy process",
    summary: "TerraUSD was marketed as an algorithmic stablecoin that would stay near one US dollar through LUNA. In May 2022 that mechanism failed. Later US cases targeted Terraform Labs and Do Kwon.",
    whatHappened: "In May 2022 UST lost its peg and LUNA hyperinflated. Common sourced ranges for the break are about $40 billion to $45 billion, not a precise $60 billion figure. In December 2025 Do Kwon was sentenced to 15 years in prison for fraud offences connected to the Terraform cryptocurrencies.",
    whatFailed: "The peg did not have durable reserves sufficient to absorb a run.",
    currentStatus: "The original UST/LUNA economic design is dead. LUNC and Terra 2.0 are not a restored peg.",
    userGuidance: ["Do not confuse LUNC or Terra 2.0 tokens with restored UST value."],
    lessons: ["A token that still trades can still represent a failed product."],
    evidence: [
      { label: "SDNY announcement of Do Kwon sentence", href: "https://www.justice.gov/usao-sdny/pr/crypto-enabled-fraudster-sentenced-orchestrating-40-billion-fraud" },
      { label: "SEC charges against Terraform Labs and Do Kwon", href: "https://www.sec.gov/newsroom/press-releases/2023-32" },
    ],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic including the 2022 Terra collapse" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "ftx",
    name: "FTX and FTT",
    ticker: "FTT",
    type: "Exchange",
    lifecycle: "insolvency",
    status: "Insolvency",
    secondaryStatus: "Confirmed enforcement action",
    era: "2022 contagion",
    launched: "2019",
    lastKnownActivity: "2022 collapse; later criminal and bankruptcy process",
    summary: "FTX filed for bankruptcy in November 2022. US prosecutors later convicted founder Samuel Bankman-Fried of fraud offences connected to the misuse of customer funds.",
    whatHappened: "Reports about Alameda Research and FTT collateral triggered a run. The often-cited customer shortfall was about $8 billion.",
    whatFailed: "Customer funds were not safely segregated in the way many users had been led to expect.",
    currentStatus: "The original FTX exchange is not an operating retail venue in its pre-collapse form.",
    userGuidance: ["Use only official FTX bankruptcy or claims channels."],
    lessons: ["Withdrawal delays are a reason to stop depositing."],
    evidence: [{ label: "SDNY statement on Bankman-Fried conviction", href: "https://www.justice.gov/usao-sdny/pr/statement-us-attorney-damian-williams-conviction-samuel-bankman-fried" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic including the 2022 FTX collapse" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "celsius-network",
    name: "Celsius Network",
    ticker: "CEL",
    type: "Exchange",
    lifecycle: "insolvency",
    status: "Insolvency",
    era: "2022 contagion",
    launched: "2017",
    lastKnownActivity: "2022 pause and bankruptcy",
    summary: "Celsius marketed high-yield crypto accounts, paused withdrawals in June 2022 and filed for US bankruptcy protection the following month.",
    whatHappened: "In June 2022 Celsius paused withdrawals, swaps and transfers. In July 2022 it filed for Chapter 11.",
    whatFailed: "Users thought they could withdraw on demand. Their assets were exposed to lending and market risk inside a centralised company.",
    currentStatus: "The original Celsius yield product is gone. Any distribution belongs to the court-supervised process.",
    userGuidance: ["Follow official bankruptcy notices rather than social-media payout rumours."],
    lessons: ["If a platform can pause withdrawals, your deposit is not cash in a wallet you control."],
    evidence: [{ label: "Celsius bankruptcy case information", href: "https://cases.stretto.com/celsius" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/lifecycle-map.svg", alt: "Label map showing insolvency as a research category" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "voyager-digital",
    name: "Voyager Digital",
    ticker: "VGX",
    type: "Exchange",
    lifecycle: "insolvency",
    status: "Insolvency",
    era: "2022 contagion",
    launched: "2018",
    lastKnownActivity: "2022 bankruptcy; liquidation continuing",
    summary: "Voyager was a centralised crypto broker that filed for Chapter 11 in July 2022 after the Three Arrows Capital default.",
    whatHappened: "Voyager filed for Chapter 11 on 5 July 2022. In March 2026 the Texas State Securities Board entered a consent order stating Voyager is no longer operating and is liquidating assets for creditors.",
    whatFailed: "Customer balances depended on Voyager’s credit book, including exposure to 3AC.",
    currentStatus: "Voyager is in liquidation. Recovery, if any, is through the court-supervised process.",
    userGuidance: ["Use official bankruptcy or state-securities notices only."],
    lessons: ["A broker that lends customer assets has credit risk."],
    evidence: [{ label: "Texas State Securities Board Voyager consent order", href: "https://www.ssb.texas.gov/news-publications/texas-state-securities-board-enters-consent-order-voyager-digital-entities" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic including 2022 lending-platform failures" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "three-arrows-capital",
    name: "Three Arrows Capital",
    ticker: "3AC",
    type: "Fund",
    lifecycle: "insolvency",
    status: "Insolvency",
    era: "2022 contagion",
    launched: "2012",
    lastKnownActivity: "2022 liquidation",
    summary: "Three Arrows Capital was a large crypto hedge fund ordered into liquidation in the British Virgin Islands on 27 June 2022.",
    whatHappened: "After Terra collapsed, 3AC missed margin calls. A BVI court ordered liquidation on 27 June 2022. The fund transmitted losses into Celsius, Voyager and other lenders.",
    whatFailed: "Concentrated leveraged bets left the fund unable to meet margin calls.",
    currentStatus: "The fund is in liquidation. There is no 3AC product for retail users to revive.",
    userGuidance: ["Do not confuse leftover commentary tokens with a claim on the 3AC estate."],
    lessons: ["Hidden leverage in a fund can become a retail withdrawal problem."],
    evidence: [{ label: "Background on the BVI liquidation and later US process", href: "https://iwpfinance.com/case-studies/three-arrows-capital-2022" }],
    confidence: "high",
    stillTrades: false,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic including the 2022 fund contagion" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "quadrigacx",
    name: "QuadrigaCX",
    type: "Exchange",
    lifecycle: "insolvency",
    status: "Insolvency",
    era: "2018–2019",
    launched: "2013",
    lastKnownActivity: "2019",
    summary: "QuadrigaCX collapsed after founder Gerald Cotten died and customers could not access funds. The OSC later published a staff investigation report.",
    whatHappened: "After Cotten's death was reported in late 2018, the company said it could not access cold wallets. The exchange sought creditor protection in 2019.",
    whatFailed: "Customers relied on a platform whose keys were not independently verifiable.",
    currentStatus: "The exchange is closed. Remaining recovery, if any, is through the court process.",
    userGuidance: ["Do not send funds to anyone claiming to reopen old Quadriga accounts."],
    lessons: ["If you do not control the keys, you hold an IOU."],
    evidence: [{ label: "Ontario Securities Commission QuadrigaCX materials", href: "https://www.osc.ca/en/news-events/news/osc-releases-report-quadrigacx" }],
    confidence: "high",
    stillTrades: false,
    image: { src: "/images/projects/lifecycle-map.svg", alt: "Label map showing insolvency as a research category" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "mt-gox",
    name: "Mt. Gox",
    type: "Exchange",
    lifecycle: "insolvency",
    status: "Insolvency",
    era: "2010–2014",
    launched: "2010",
    lastKnownActivity: "2014 halt; rehabilitation continuing",
    summary: "Mt. Gox halted withdrawals in 2014 after a massive loss of customer bitcoin and entered Japanese legal proceedings that have continued for years.",
    whatHappened: "In February 2014 Mt. Gox stopped withdrawals and later said it had lost hundreds of thousands of bitcoin.",
    whatFailed: "The exchange could not safeguard or account for customer bitcoin.",
    currentStatus: "Mt. Gox is not an operating exchange. Official updates come from the trustee and mtgox.com notices.",
    userGuidance: ["Use only trustee or court-linked Mt. Gox notices."],
    lessons: ["Market dominance does not prevent operational failure."],
    evidence: [{ label: "Mt. Gox official site and trustee notices", href: "https://www.mtgox.com/" }],
    confidence: "high",
    stillTrades: false,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic starting with the 2014 Mt. Gox halt" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "iron-finance-titan",
    name: "Iron Finance TITAN",
    ticker: "TITAN",
    type: "Protocol",
    lifecycle: "protocol-failure",
    status: "Protocol failure",
    secondaryStatus: "Liquidity disappeared",
    era: "2021 DeFi experiments",
    launched: "2021",
    lastKnownActivity: "June 2021",
    summary: "Iron Finance suffered a bank run on 16 June 2021. This is a documented design failure, not a confirmed fraud judgment.",
    whatHappened: "IRON lost its peg and the mint/redeem loop destroyed TITAN's price. Iron Finance published a post-mortem describing a bank run.",
    whatFailed: "Partial collateral plus a volatile recapitalisation token can fail in a run even if the contracts keep operating.",
    currentStatus: "The original product is not a working dollar substitute.",
    userGuidance: ["Do not assume every collapsed token was stolen."],
    lessons: ["A smart contract can execute perfectly and still wipe out users."],
    evidence: [{ label: "Iron Finance post-mortem (16-17 June 2021)", href: "https://ironfinance.medium.com/iron-finance-post-mortem-17-june-2021-9e86b1f53c3b" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/lifecycle-map.svg", alt: "Label map showing protocol failure as a research category" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "beanstalk",
    name: "Beanstalk",
    ticker: "BEAN",
    type: "Protocol",
    lifecycle: "protocol-failure",
    status: "Exploit",
    secondaryStatus: "Protocol failure",
    era: "2021–2022 DeFi experiments",
    launched: "2021",
    lastKnownActivity: "April 2022 attack",
    summary: "In April 2022 an attacker used a flash loan to seize Beanstalk governance and drain about $182 million.",
    whatHappened: "On 17 April 2022 an attacker borrowed governance power, passed a malicious proposal and transferred protocol assets.",
    whatFailed: "Emergency governance could be bought for one transaction.",
    currentStatus: "The original Beanstalk credit system failed.",
    userGuidance: ["Be cautious with protocols where flash-loaned tokens can vote immediately."],
    lessons: ["Governance is part of the attack surface."],
    evidence: [{ label: "Rekt reporting on the $182 million attack", href: "https://rekt.news/beanstalk-rekt" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/lifecycle-map.svg", alt: "Label map showing protocol failure and exploit cases" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "wonderland-time",
    name: "Wonderland TIME",
    ticker: "TIME",
    type: "Protocol",
    lifecycle: "abandoned",
    status: "Abandoned development",
    era: "2021–2022 DeFi experiments",
    launched: "2021",
    lastKnownActivity: "2022 treasury crisis",
    summary: "Wonderland lost trust in January 2022 after treasury manager 0xSifu was identified as Michael Patryn, a QuadrigaCX co-founder.",
    whatHappened: "The community revolt ended the project’s original operating thesis after the Sifu identity became public.",
    whatFailed: "Anonymous treasury control plus a leveraged rebase token meant users were trusting unidentified operators.",
    currentStatus: "TIME may still trade. That is a remnant market, not the original 2021 product.",
    userGuidance: ["Ask who can move the treasury and whether that person is identified."],
    lessons: ["Anonymous treasury admins are a governance risk."],
    evidence: [{ label: "Contemporary reporting on the Sifu / Patryn identification", href: "https://forklog.com/en/community-accuses-wonderland-co-founder-of-involvement-with-quadrigacx/" }],
    confidence: "medium",
    stillTrades: true,
    image: { src: "/images/projects/lifecycle-map.svg", alt: "Label map showing abandoned projects as a research category" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "diem-libra",
    name: "Diem / Libra",
    type: "Corporate project",
    lifecycle: "abandoned",
    status: "Never launched",
    secondaryStatus: "Abandoned development",
    era: "2019–2022 corporate",
    launched: "Announced 2019",
    lastKnownActivity: "2022 wind-down",
    summary: "Libra, later Diem, was Meta/Facebook’s planned global payment coin. It never launched. The Diem Association sold assets to Silvergate and wound down in 2022.",
    whatHappened: "Facebook announced Libra in June 2019. Regulatory opposition blocked a public launch. In January 2022 the association sold assets to Silvergate and shut down.",
    whatFailed: "This is a political and regulatory abandonment, not a rug pull.",
    currentStatus: "There is no official consumer Diem coin to buy. DEX tokens using those names should be treated as unrelated.",
    userGuidance: ["Do not buy unofficial Libra or Diem tokens claiming to be the Meta project."],
    lessons: ["A large corporate backer does not guarantee a launch."],
    evidence: [{ label: "Summary of the Diem wind-down and Silvergate sale", href: "https://en.wikipedia.org/wiki/Diem_(digital_currency)" }],
    confidence: "high",
    stillTrades: false,
    image: { src: "/images/projects/lifecycle-map.svg", alt: "Label map showing abandoned and never-launched projects" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "loopring-dex",
    name: "Loopring DEX",
    ticker: "LRC",
    type: "Protocol",
    lifecycle: "obsolete",
    status: "Official sunset",
    era: "2024–2026 sunsets",
    launched: "2017",
    lastKnownActivity: "28 June 2026",
    summary: "On 28 June 2026 Loopring announced that it was shutting the DEX, AMM and relayer immediately and returning remaining user balances to Ethereum wallets.",
    whatHappened: "Loopring said it had failed to gain meaningful adoption and had been surpassed by modern zkEVM systems. This is an official product sunset, not a hidden rug pull.",
    whatFailed: "The original Loopring DEX architecture did not keep users as cheaper L2s arrived. LRC can still exist after the DEX is gone.",
    currentStatus: "The Loopring DEX/relayer product is obsolete. LRC listings are not proof that the DEX still works.",
    userGuidance: ["Use official Loopring notices for refunds. Do not pay a helper to claim a Loopring balance."],
    lessons: ["Early infrastructure can be sunset when newer designs win."],
    evidence: [
      { label: "Loopring sunset announcement on X", href: "https://x.com/loopringorg/status/2071253250725322987" },
      { label: "The Block report on the DEX sunset", href: "https://www.theblock.co/news/defi/2026-06-29-loopring-sunsets-dex-406492" },
    ],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic including 2026 official sunsets" },
    reviewedAt: "2026-08-27",
  },
  {
    slug: "goldfinch",
    name: "Goldfinch",
    ticker: "GFI",
    type: "Protocol",
    lifecycle: "obsolete",
    status: "Official sunset",
    secondaryStatus: "Abandoned development",
    era: "2024–2026 sunsets",
    launched: "2020",
    lastKnownActivity: "June 2026 wind-down vote",
    summary: "In June 2026 Goldfinch token holders backed GIP-87 to wind down Goldfinch Prime, stop new development and move into maintenance mode.",
    whatHappened: "Coverage of the June 2026 vote says the community approved an orderly shutdown of Goldfinch Prime after borrower-pool stress. This is a documented wind-down, not a sudden rug pull.",
    whatFailed: "On-chain credit still depended on off-chain borrowers paying back.",
    currentStatus: "Core development has stopped. GFI may still trade. That remnant market is not a live credit marketplace.",
    userGuidance: ["Follow official Goldfinch governance and trustee notices for repayments."],
    lessons: ["Real-world credit risk does not disappear because the loan is tokenised."],
    evidence: [{ label: "The Block report on the Goldfinch Prime wind-down vote", href: "https://www.theblock.co/news/defi/2026-06-23-goldfinch-set-shutter-prime-community-vote-backs-wind-down-proposal-405825" }],
    confidence: "high",
    stillTrades: true,
    image: { src: "/images/projects/contagion-timeline.svg", alt: "Timeline graphic including the 2026 Goldfinch wind-down" },
    reviewedAt: "2026-08-27",
  },
];

export const projectStatuses: ProjectStatus[] = [
  "Abandoned development",
  "Website offline",
  "Chain halted",
  "Liquidity disappeared",
  "Protocol failure",
  "Exploit",
  "Insolvency",
  "Delisted",
  "Migrated",
  "Official sunset",
  "Never launched",
  "Confirmed enforcement action",
];

export function getDeadProject(slug: string) {
  return deadProjects.find((project) => project.slug === slug);
}

export function countByLifecycle() {
  return deadProjects.reduce(
    (acc, project) => {
      acc[project.lifecycle] += 1;
      return acc;
    },
    {
      enforcement: 0,
      insolvency: 0,
      "protocol-failure": 0,
      abandoned: 0,
      obsolete: 0,
    } as Record<Lifecycle, number>
  );
}
